apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apisix
resources:
  - certificates.yaml
  - sync.yaml
configMapGenerator:
  - name: vela-gateway-tls-sync
    files:
      - sync.sh
