global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - vela-lab-alertmanager.vela-observability.svc.cluster.local:9093

rule_files:
  - /etc/prometheus/rules/rules.yaml
  - /etc/prometheus/rules/lab-rules.yaml

scrape_configs:
  - job_name: vela-lab-control
    metrics_path: /metrics
    static_configs:
      - targets:
          - vela-lab-control.vela-lab.svc.cluster.local:8081
        labels:
          environment: non-production-lab
