apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../object-store/ha-six
patches:
  - target:
      kind: StatefulSet
      name: minio-ha
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          vela.ai/deployment-profile: isolated-migration-staging
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 8Gi
