apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vela-postgres
  labels:
    app.kubernetes.io/part-of: vela
spec:
  minAvailable: 2
  selector:
    matchLabels:
      cnpg.io/cluster: vela-postgres
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nats
  labels:
    app.kubernetes.io/part-of: vela
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
