apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vela-postgres
  labels:
    app.kubernetes.io/part-of: vela
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4@sha256:99be063781d171d3971089b49c992706bdab9ccbd2b57cdf126c7542773aedfe
  primaryUpdateStrategy: unsupervised
  storage:
    size: 100Gi
    storageClass: local-path
  walStorage:
    size: 50Gi
    storageClass: local-path
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      cpu: "8"
      memory: 32Gi
  postgresql:
    parameters:
      vela.require_synchronous_quorum: "on"
    synchronous:
      dataDurability: required
      method: any
      number: 1
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: vela-postgres-backup
