apiVersion: v1
kind: ServiceAccount
metadata:
  name: vela-worker
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-stage-worker
    app.kubernetes.io/part-of: vela
automountServiceAccountToken: false
