apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: llm-api-applications
  namespace: monitoring
  labels: {release: monitoring, app.kubernetes.io/part-of: vela}
spec:
  namespaceSelector: {matchNames: [llm-api]}
  selector:
    matchLabels: {vela.ai/metrics: enabled}
  sampleLimit: 5000
  targetLimit: 48
  labelLimit: 30
  labelNameLengthLimit: 128
  labelValueLengthLimit: 512
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
      honorLabels: false
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: llm-models-applications
  namespace: monitoring
  labels: {release: monitoring, app.kubernetes.io/part-of: vela}
spec:
  namespaceSelector: {matchNames: [llm-models]}
  selector:
    matchLabels: {vela.ai/metrics: enabled}
  sampleLimit: 5000
  targetLimit: 48
  labelLimit: 30
  labelNameLengthLimit: 128
  labelValueLengthLimit: 512
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
      honorLabels: false
