driver:
  enabled: false
toolkit:
  enabled: false
mig:
  strategy: none
migManager:
  enabled: false
cdi:
  enabled: true
nfd:
  enabled: true
node-feature-discovery:
  image:
    repository: 10.1.200.17:5443/nfd/node-feature-discovery
  worker:
    nodeSelector:
      vela.ai/worker-profile: h3
    tolerations:
      - key: vela.ai/h3
        operator: Equal
        value: "true"
        effect: NoSchedule
operator:
  repository: 10.1.200.17:5443/nvidia
  runtimeClass: nvidia
  nodeSelector:
    vela.ai/node-role: control-storage
daemonsets:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: vela.ai/h3
      operator: Equal
      value: "true"
      effect: NoSchedule
validator:
  repository: 10.1.200.17:5443/nvidia
devicePlugin:
  enabled: true
  repository: 10.1.200.17:5443/nvidia
gfd:
  enabled: true
  repository: 10.1.200.17:5443/nvidia
dcgm:
  enabled: false
dcgmExporter:
  enabled: true
  repository: 10.1.200.17:5443/nvidia/k8s
vgpuDeviceManager:
  enabled: false
vfioManager:
  enabled: false
sandboxDevicePlugin:
  enabled: false
kataSandboxDevicePlugin:
  enabled: false
ccManager:
  enabled: false
