write-kubeconfig-mode: "0600"
node-name: vela-lab-control-1
node-ip: 10.1.200.17
advertise-address: 10.1.200.17
tls-san:
  - 10.1.200.17
cni: canal
cluster-cidr: 10.42.0.0/16
service-cidr: 10.43.0.0/16
system-default-registry: 10.1.200.17:5443
kubelet-arg:
  - fail-swap-on=false
node-label:
  - vela.ai/node-role=control-storage
  - nvidia.com/gpu.deploy.operands=false
