server: https://10.1.200.17:9345
token-file: /etc/rancher/rke2/agent-token
node-name: vela-lab-worker-2
node-ip: 10.1.200.16
system-default-registry: 10.1.200.17:5443
kubelet-arg:
  - fail-swap-on=false
node-label:
  - vela.ai/worker-profile=h3
  - vela.ai/worker-pool=launch
node-taint:
  - vela.ai/h3=true:NoSchedule
