apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vela-system
resources:
  - namespace.yaml
  - service-account.yaml
  - priority-class.yaml
  - runtime-config.yaml
  - node-agent-config.yaml
  - deployment.yaml
  - services.yaml
  - disruption-budget.yaml
  - network-policies.yaml
