apiVersion: v1
kind: ServiceAccount
metadata:
  name: vela-control
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-control
    app.kubernetes.io/part-of: vela
automountServiceAccountToken: false
