apiVersion: v1
kind: Service
metadata:
  name: vela-api
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-control
    app.kubernetes.io/component: public-api
    app.kubernetes.io/part-of: vela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vela-control
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
---
apiVersion: v1
kind: Service
metadata:
  name: vela-control
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-control
    app.kubernetes.io/component: fleet-maintenance
    app.kubernetes.io/part-of: vela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vela-control
  ports:
    - name: grpc
      port: 8444
      targetPort: fleet-grpc
      protocol: TCP
      appProtocol: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: vela-stage-worker-control
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-control
    app.kubernetes.io/component: stage-worker-control
    app.kubernetes.io/part-of: vela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vela-control
  ports:
    - name: grpc
      port: 8447
      targetPort: stage-wkr-grpc
      protocol: TCP
      appProtocol: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: vela-finance-reconciliation
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-control
    app.kubernetes.io/component: finance-reconciliation
    app.kubernetes.io/part-of: vela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vela-control
  ports:
    - name: https
      port: 8445
      targetPort: finance-https
      protocol: TCP
      appProtocol: https
---
apiVersion: v1
kind: Service
metadata:
  name: vela-compliance
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-control
    app.kubernetes.io/component: compliance
    app.kubernetes.io/part-of: vela
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vela-control
  ports:
    - name: https
      port: 8446
      targetPort: compliance-https
      protocol: TCP
      appProtocol: https
