# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vela.v1 import runner_pb2 as vela_dot_v1_dot_runner__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vela/v1/runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunnerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/vela.v1.RunnerService/Prepare',
                request_serializer=vela_dot_v1_dot_runner__pb2.PrepareRequest.SerializeToString,
                response_deserializer=vela_dot_v1_dot_runner__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/vela.v1.RunnerService/Start',
                request_serializer=vela_dot_v1_dot_runner__pb2.StartRequest.SerializeToString,
                response_deserializer=vela_dot_v1_dot_runner__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/vela.v1.RunnerService/Cancel',
                request_serializer=vela_dot_v1_dot_runner__pb2.CancelRequest.SerializeToString,
                response_deserializer=vela_dot_v1_dot_runner__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/vela.v1.RunnerService/Status',
                request_serializer=vela_dot_v1_dot_runner__pb2.StatusRequest.SerializeToString,
                response_deserializer=vela_dot_v1_dot_runner__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.CollectOutputs = channel.unary_unary(
                '/vela.v1.RunnerService/CollectOutputs',
                request_serializer=vela_dot_v1_dot_runner__pb2.CollectOutputsRequest.SerializeToString,
                response_deserializer=vela_dot_v1_dot_runner__pb2.CollectOutputsResponse.FromString,
                _registered_method=True)


class RunnerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectOutputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=vela_dot_v1_dot_runner__pb2.PrepareRequest.FromString,
                    response_serializer=vela_dot_v1_dot_runner__pb2.PrepareResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=vela_dot_v1_dot_runner__pb2.StartRequest.FromString,
                    response_serializer=vela_dot_v1_dot_runner__pb2.StartResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=vela_dot_v1_dot_runner__pb2.CancelRequest.FromString,
                    response_serializer=vela_dot_v1_dot_runner__pb2.CancelResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=vela_dot_v1_dot_runner__pb2.StatusRequest.FromString,
                    response_serializer=vela_dot_v1_dot_runner__pb2.StatusResponse.SerializeToString,
            ),
            'CollectOutputs': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectOutputs,
                    request_deserializer=vela_dot_v1_dot_runner__pb2.CollectOutputsRequest.FromString,
                    response_serializer=vela_dot_v1_dot_runner__pb2.CollectOutputsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vela.v1.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vela.v1.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vela.v1.RunnerService/Prepare',
            vela_dot_v1_dot_runner__pb2.PrepareRequest.SerializeToString,
            vela_dot_v1_dot_runner__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vela.v1.RunnerService/Start',
            vela_dot_v1_dot_runner__pb2.StartRequest.SerializeToString,
            vela_dot_v1_dot_runner__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vela.v1.RunnerService/Cancel',
            vela_dot_v1_dot_runner__pb2.CancelRequest.SerializeToString,
            vela_dot_v1_dot_runner__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vela.v1.RunnerService/Status',
            vela_dot_v1_dot_runner__pb2.StatusRequest.SerializeToString,
            vela_dot_v1_dot_runner__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vela.v1.RunnerService/CollectOutputs',
            vela_dot_v1_dot_runner__pb2.CollectOutputsRequest.SerializeToString,
            vela_dot_v1_dot_runner__pb2.CollectOutputsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
