// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admission.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vivym/vela/internal/execution"
)

const getIdempotencyResult = `-- name: GetIdempotencyResult :one
SELECT request_hash, job_id
FROM idempotency_results
WHERE organization_id = $1
  AND project_id = $2
  AND idempotency_key = $3
`

type GetIdempotencyResultParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
}

type GetIdempotencyResultRow struct {
	RequestHash []byte    `db:"request_hash" json:"request_hash"`
	JobID       uuid.UUID `db:"job_id" json:"job_id"`
}

func (q *Queries) GetIdempotencyResult(ctx context.Context, arg GetIdempotencyResultParams) (GetIdempotencyResultRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyResult, arg.OrganizationID, arg.ProjectID, arg.IdempotencyKey)
	var i GetIdempotencyResultRow
	err := row.Scan(&i.RequestHash, &i.JobID)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT
    j.id,
    j.project_id,
    j.state,
    j.execution_phase,
    j.pricing_rate_card_revision_id,
    j.pricing_rate_line_id,
    j.pricing_unit_amount_minor,
    j.pricing_quantity,
    j.pricing_quoted_amount_minor,
    j.pricing_currency,
    rts.attempts_started,
    rts.next_retry_at,
    ap.phase_progress,
    ap.estimated_finish_at,
    ap.progress_updated_at,
    j.job_expires_at,
    j.created_at
FROM jobs AS j
JOIN vela_request_job_runtime AS rts ON rts.job_id = j.id
LEFT JOIN vela_request_job_progress AS ap ON ap.job_id = j.id
WHERE j.organization_id = $1
  AND j.project_id = $2
  AND j.id = $3
`

type GetJobParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
}

type GetJobRow struct {
	ID                        uuid.UUID          `db:"id" json:"id"`
	ProjectID                 uuid.UUID          `db:"project_id" json:"project_id"`
	State                     JobState           `db:"state" json:"state"`
	ExecutionPhase            *execution.Phase   `db:"execution_phase" json:"execution_phase"`
	PricingRateCardRevisionID uuid.UUID          `db:"pricing_rate_card_revision_id" json:"pricing_rate_card_revision_id"`
	PricingRateLineID         uuid.UUID          `db:"pricing_rate_line_id" json:"pricing_rate_line_id"`
	PricingUnitAmountMinor    int64              `db:"pricing_unit_amount_minor" json:"pricing_unit_amount_minor"`
	PricingQuantity           int32              `db:"pricing_quantity" json:"pricing_quantity"`
	PricingQuotedAmountMinor  int64              `db:"pricing_quoted_amount_minor" json:"pricing_quoted_amount_minor"`
	PricingCurrency           string             `db:"pricing_currency" json:"pricing_currency"`
	AttemptsStarted           int32              `db:"attempts_started" json:"attempts_started"`
	NextRetryAt               pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	PhaseProgress             *float64           `db:"phase_progress" json:"phase_progress"`
	EstimatedFinishAt         pgtype.Timestamptz `db:"estimated_finish_at" json:"estimated_finish_at"`
	ProgressUpdatedAt         pgtype.Timestamptz `db:"progress_updated_at" json:"progress_updated_at"`
	JobExpiresAt              pgtype.Timestamptz `db:"job_expires_at" json:"job_expires_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, arg.OrganizationID, arg.ProjectID, arg.JobID)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.State,
		&i.ExecutionPhase,
		&i.PricingRateCardRevisionID,
		&i.PricingRateLineID,
		&i.PricingUnitAmountMinor,
		&i.PricingQuantity,
		&i.PricingQuotedAmountMinor,
		&i.PricingCurrency,
		&i.AttemptsStarted,
		&i.NextRetryAt,
		&i.PhaseProgress,
		&i.EstimatedFinishAt,
		&i.ProgressUpdatedAt,
		&i.JobExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPoolQueued = `-- name: IncrementPoolQueued :execrows
UPDATE worker_pools
SET queued_count = queued_count + 1
WHERE id = $1
  AND admission_open
  AND queued_count - retry_wait_count < queued_limit
`

func (q *Queries) IncrementPoolQueued(ctx context.Context, workerPoolID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementPoolQueued, workerPoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementProjectQueued = `-- name: IncrementProjectQueued :execrows
UPDATE projects
SET queued_count = queued_count + 1
WHERE organization_id = $1
  AND id = $2
  AND queued_count - retry_wait_count < queued_limit
`

type IncrementProjectQueuedParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) IncrementProjectQueued(ctx context.Context, arg IncrementProjectQueuedParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementProjectQueued, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCreditReservation = `-- name: InsertCreditReservation :exec
INSERT INTO credit_reservations (
    id, organization_id, project_id, job_id, amount_minor, currency
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertCreditReservationParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
	AmountMinor    int64     `db:"amount_minor" json:"amount_minor"`
	Currency       string    `db:"currency" json:"currency"`
}

func (q *Queries) InsertCreditReservation(ctx context.Context, arg InsertCreditReservationParams) error {
	_, err := q.db.Exec(ctx, insertCreditReservation,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const insertIdempotencyResult = `-- name: InsertIdempotencyResult :exec
INSERT INTO idempotency_results (
    organization_id, project_id, idempotency_key, request_hash, job_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertIdempotencyResultParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
	IdempotencyKey string    `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    []byte    `db:"request_hash" json:"request_hash"`
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
}

func (q *Queries) InsertIdempotencyResult(ctx context.Context, arg InsertIdempotencyResultParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyResult,
		arg.OrganizationID,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.JobID,
	)
	return err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (
    id,
    organization_id,
    project_id,
    created_by_principal_id,
    model_revision_id,
    generation_preset_revision_id,
    service_class_revision_id,
    output_spec_id,
    worker_pool_id,
    request_hash,
    request_content,
    request_content_expires_at,
    pricing_rate_card_revision_id,
    pricing_rate_line_id,
    pricing_unit_amount_minor,
    pricing_quantity,
    pricing_quoted_amount_minor,
    pricing_currency,
    execution_max_attempts,
    execution_max_total_compute_seconds,
    execution_max_finalization_seconds_per_attempt,
    execution_retry_backoff_policy,
    execution_retryable_failure_classes,
    execution_circuit_breaker_policy,
	execution_circuit_fingerprint_window_seconds,
	execution_circuit_min_distinct_healthy_workers,
    job_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    transaction_timestamp() + interval '30 days',
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
	$24,
	$25,
	transaction_timestamp() + $26::bigint * interval '1 second'
)
`

type InsertJobParams struct {
	ID                                        uuid.UUID `db:"id" json:"id"`
	OrganizationID                            uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID                                 uuid.UUID `db:"project_id" json:"project_id"`
	CreatedByPrincipalID                      uuid.UUID `db:"created_by_principal_id" json:"created_by_principal_id"`
	ModelRevisionID                           uuid.UUID `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID                uuid.UUID `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	ServiceClassRevisionID                    uuid.UUID `db:"service_class_revision_id" json:"service_class_revision_id"`
	OutputSpecID                              uuid.UUID `db:"output_spec_id" json:"output_spec_id"`
	WorkerPoolID                              uuid.UUID `db:"worker_pool_id" json:"worker_pool_id"`
	RequestHash                               []byte    `db:"request_hash" json:"request_hash"`
	RequestContent                            []byte    `db:"request_content" json:"request_content"`
	PricingRateCardRevisionID                 uuid.UUID `db:"pricing_rate_card_revision_id" json:"pricing_rate_card_revision_id"`
	PricingRateLineID                         uuid.UUID `db:"pricing_rate_line_id" json:"pricing_rate_line_id"`
	PricingUnitAmountMinor                    int64     `db:"pricing_unit_amount_minor" json:"pricing_unit_amount_minor"`
	PricingQuantity                           int32     `db:"pricing_quantity" json:"pricing_quantity"`
	PricingQuotedAmountMinor                  int64     `db:"pricing_quoted_amount_minor" json:"pricing_quoted_amount_minor"`
	PricingCurrency                           string    `db:"pricing_currency" json:"pricing_currency"`
	ExecutionMaxAttempts                      int32     `db:"execution_max_attempts" json:"execution_max_attempts"`
	ExecutionMaxTotalComputeSeconds           int64     `db:"execution_max_total_compute_seconds" json:"execution_max_total_compute_seconds"`
	ExecutionMaxFinalizationSecondsPerAttempt int32     `db:"execution_max_finalization_seconds_per_attempt" json:"execution_max_finalization_seconds_per_attempt"`
	ExecutionRetryBackoffPolicy               []byte    `db:"execution_retry_backoff_policy" json:"execution_retry_backoff_policy"`
	ExecutionRetryableFailureClasses          []string  `db:"execution_retryable_failure_classes" json:"execution_retryable_failure_classes"`
	ExecutionCircuitBreakerPolicy             []byte    `db:"execution_circuit_breaker_policy" json:"execution_circuit_breaker_policy"`
	ExecutionCircuitFingerprintWindowSeconds  int32     `db:"execution_circuit_fingerprint_window_seconds" json:"execution_circuit_fingerprint_window_seconds"`
	ExecutionCircuitMinDistinctHealthyWorkers int32     `db:"execution_circuit_min_distinct_healthy_workers" json:"execution_circuit_min_distinct_healthy_workers"`
	JobLifetimeSeconds                        int64     `db:"job_lifetime_seconds" json:"job_lifetime_seconds"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.CreatedByPrincipalID,
		arg.ModelRevisionID,
		arg.GenerationPresetRevisionID,
		arg.ServiceClassRevisionID,
		arg.OutputSpecID,
		arg.WorkerPoolID,
		arg.RequestHash,
		arg.RequestContent,
		arg.PricingRateCardRevisionID,
		arg.PricingRateLineID,
		arg.PricingUnitAmountMinor,
		arg.PricingQuantity,
		arg.PricingQuotedAmountMinor,
		arg.PricingCurrency,
		arg.ExecutionMaxAttempts,
		arg.ExecutionMaxTotalComputeSeconds,
		arg.ExecutionMaxFinalizationSecondsPerAttempt,
		arg.ExecutionRetryBackoffPolicy,
		arg.ExecutionRetryableFailureClasses,
		arg.ExecutionCircuitBreakerPolicy,
		arg.ExecutionCircuitFingerprintWindowSeconds,
		arg.ExecutionCircuitMinDistinctHealthyWorkers,
		arg.JobLifetimeSeconds,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    organization_id,
    project_id,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_type,
    schema_version,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    'Job',
    $4,
    1,
    'job.ready',
    1,
    $5,
    $6
)
`

type InsertOutboxEventParams struct {
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	Payload        []byte             `db:"payload" json:"payload"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertRetryRuntimeState = `-- name: InsertRetryRuntimeState :exec
INSERT INTO retry_runtime_states (job_id, organization_id, project_id)
VALUES ($1, $2, $3)
`

type InsertRetryRuntimeStateParams struct {
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) InsertRetryRuntimeState(ctx context.Context, arg InsertRetryRuntimeStateParams) error {
	_, err := q.db.Exec(ctx, insertRetryRuntimeState, arg.JobID, arg.OrganizationID, arg.ProjectID)
	return err
}

const lockCompatiblePool = `-- name: LockCompatiblePool :one
SELECT
	pool.id::uuid AS id,
	pool.admission_open::boolean AS admission_open,
	pool.queued_count::integer AS queued_count,
	pool.queued_limit::integer AS queued_limit,
	pool.retry_after_seconds::integer AS retry_after_seconds
FROM vela_lock_compatible_pool(
	$1,
	$2,
	$3
) AS pool(id, admission_open, queued_count, queued_limit, retry_after_seconds)
`

type LockCompatiblePoolParams struct {
	ModelRevisionID            uuid.UUID `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID uuid.UUID `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	OutputSpecID               uuid.UUID `db:"output_spec_id" json:"output_spec_id"`
}

type LockCompatiblePoolRow struct {
	ID                uuid.UUID `db:"id" json:"id"`
	AdmissionOpen     bool      `db:"admission_open" json:"admission_open"`
	QueuedCount       int32     `db:"queued_count" json:"queued_count"`
	QueuedLimit       int32     `db:"queued_limit" json:"queued_limit"`
	RetryAfterSeconds int32     `db:"retry_after_seconds" json:"retry_after_seconds"`
}

func (q *Queries) LockCompatiblePool(ctx context.Context, arg LockCompatiblePoolParams) (LockCompatiblePoolRow, error) {
	row := q.db.QueryRow(ctx, lockCompatiblePool, arg.ModelRevisionID, arg.GenerationPresetRevisionID, arg.OutputSpecID)
	var i LockCompatiblePoolRow
	err := row.Scan(
		&i.ID,
		&i.AdmissionOpen,
		&i.QueuedCount,
		&i.QueuedLimit,
		&i.RetryAfterSeconds,
	)
	return i, err
}

const lockCreditAccount = `-- name: LockCreditAccount :one
SELECT
    currency,
    contract_credit_limit_minor,
    reserved_minor,
    unsettled_posted_minor
FROM organization_credit_accounts
WHERE organization_id = $1
FOR UPDATE
`

type LockCreditAccountRow struct {
	Currency                 string `db:"currency" json:"currency"`
	ContractCreditLimitMinor int64  `db:"contract_credit_limit_minor" json:"contract_credit_limit_minor"`
	ReservedMinor            int64  `db:"reserved_minor" json:"reserved_minor"`
	UnsettledPostedMinor     int64  `db:"unsettled_posted_minor" json:"unsettled_posted_minor"`
}

func (q *Queries) LockCreditAccount(ctx context.Context, organizationID uuid.UUID) (LockCreditAccountRow, error) {
	row := q.db.QueryRow(ctx, lockCreditAccount, organizationID)
	var i LockCreditAccountRow
	err := row.Scan(
		&i.Currency,
		&i.ContractCreditLimitMinor,
		&i.ReservedMinor,
		&i.UnsettledPostedMinor,
	)
	return i, err
}

const lockIdempotencyKey = `-- name: LockIdempotencyKey :one
SELECT pg_advisory_xact_lock(
    hashtext($1::text),
    hashtext($2::text)
) AS acquired
`

type LockIdempotencyKeyParams struct {
	ProjectID      string `db:"project_id" json:"project_id"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var acquired interface{}
	err := row.Scan(&acquired)
	return acquired, err
}

const lockProjectForAdmission = `-- name: LockProjectForAdmission :one
SELECT
    p.queued_count - p.retry_wait_count AS queued_count,
    p.queued_limit,
    p.retry_after_seconds,
    p.running_count,
    p.running_limit,
    o.status AS organization_status
FROM projects AS p
JOIN customer_organizations AS o ON o.id = p.organization_id
WHERE p.organization_id = $1
  AND p.id = $2
FOR UPDATE OF p
`

type LockProjectForAdmissionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

type LockProjectForAdmissionRow struct {
	QueuedCount        int32  `db:"queued_count" json:"queued_count"`
	QueuedLimit        int32  `db:"queued_limit" json:"queued_limit"`
	RetryAfterSeconds  int32  `db:"retry_after_seconds" json:"retry_after_seconds"`
	RunningCount       int32  `db:"running_count" json:"running_count"`
	RunningLimit       int32  `db:"running_limit" json:"running_limit"`
	OrganizationStatus string `db:"organization_status" json:"organization_status"`
}

func (q *Queries) LockProjectForAdmission(ctx context.Context, arg LockProjectForAdmissionParams) (LockProjectForAdmissionRow, error) {
	row := q.db.QueryRow(ctx, lockProjectForAdmission, arg.OrganizationID, arg.ProjectID)
	var i LockProjectForAdmissionRow
	err := row.Scan(
		&i.QueuedCount,
		&i.QueuedLimit,
		&i.RetryAfterSeconds,
		&i.RunningCount,
		&i.RunningLimit,
		&i.OrganizationStatus,
	)
	return i, err
}

const reserveOrganizationCredit = `-- name: ReserveOrganizationCredit :execrows
UPDATE organization_credit_accounts
SET reserved_minor = reserved_minor + $1,
    version = version + 1,
    updated_at = clock_timestamp()
WHERE organization_id = $2
  AND currency = $3
  AND contract_credit_limit_minor - unsettled_posted_minor - reserved_minor >= $1
`

type ReserveOrganizationCreditParams struct {
	AmountMinor    int64     `db:"amount_minor" json:"amount_minor"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Currency       string    `db:"currency" json:"currency"`
}

func (q *Queries) ReserveOrganizationCredit(ctx context.Context, arg ReserveOrganizationCreditParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveOrganizationCredit, arg.AmountMinor, arg.OrganizationID, arg.Currency)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveActiveSKU = `-- name: ResolveActiveSKU :one
SELECT
	resolved.model_revision_id::uuid AS model_revision_id,
	resolved.generation_preset_revision_id::uuid AS generation_preset_revision_id,
	resolved.certified_p95_compute_seconds::integer AS certified_p95_compute_seconds,
	resolved.service_class_revision_id::uuid AS service_class_revision_id,
	resolved.queue_retry_allowance_seconds::integer AS queue_retry_allowance_seconds,
	resolved.max_attempts::integer AS max_attempts,
	resolved.max_total_compute_multiplier_milli::integer AS max_total_compute_multiplier_milli,
	resolved.max_finalization_seconds_per_attempt::integer AS max_finalization_seconds_per_attempt,
	resolved.retry_backoff_policy::jsonb AS retry_backoff_policy,
	resolved.retryable_failure_classes::text[] AS retryable_failure_classes,
	resolved.circuit_breaker_policy::jsonb AS circuit_breaker_policy,
	resolved.output_spec_id::uuid AS output_spec_id,
	resolved.rate_card_revision_id::uuid AS rate_card_revision_id,
	resolved.rate_line_id::uuid AS rate_line_id,
	resolved.unit_amount_minor::bigint AS unit_amount_minor,
	resolved.currency::text AS currency,
	resolved.circuit_fingerprint_window_seconds::integer AS circuit_fingerprint_window_seconds,
	resolved.circuit_min_distinct_healthy_workers::integer AS circuit_min_distinct_healthy_workers
FROM vela_resolve_active_sku(
	$1,
	$2,
	$3,
	$4
) AS resolved(
	model_revision_id,
	generation_preset_revision_id,
	certified_p95_compute_seconds,
	service_class_revision_id,
	queue_retry_allowance_seconds,
	max_attempts,
	max_total_compute_multiplier_milli,
	max_finalization_seconds_per_attempt,
	retry_backoff_policy,
	retryable_failure_classes,
	circuit_breaker_policy,
	output_spec_id,
	rate_card_revision_id,
	rate_line_id,
	unit_amount_minor,
	currency,
	circuit_fingerprint_window_seconds,
	circuit_min_distinct_healthy_workers
)
`

type ResolveActiveSKUParams struct {
	Model            string `db:"model" json:"model"`
	GenerationPreset string `db:"generation_preset" json:"generation_preset"`
	ServiceClass     string `db:"service_class" json:"service_class"`
	OutputSpec       string `db:"output_spec" json:"output_spec"`
}

type ResolveActiveSKURow struct {
	ModelRevisionID                  uuid.UUID `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID       uuid.UUID `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	CertifiedP95ComputeSeconds       int32     `db:"certified_p95_compute_seconds" json:"certified_p95_compute_seconds"`
	ServiceClassRevisionID           uuid.UUID `db:"service_class_revision_id" json:"service_class_revision_id"`
	QueueRetryAllowanceSeconds       int32     `db:"queue_retry_allowance_seconds" json:"queue_retry_allowance_seconds"`
	MaxAttempts                      int32     `db:"max_attempts" json:"max_attempts"`
	MaxTotalComputeMultiplierMilli   int32     `db:"max_total_compute_multiplier_milli" json:"max_total_compute_multiplier_milli"`
	MaxFinalizationSecondsPerAttempt int32     `db:"max_finalization_seconds_per_attempt" json:"max_finalization_seconds_per_attempt"`
	RetryBackoffPolicy               []byte    `db:"retry_backoff_policy" json:"retry_backoff_policy"`
	RetryableFailureClasses          []string  `db:"retryable_failure_classes" json:"retryable_failure_classes"`
	CircuitBreakerPolicy             []byte    `db:"circuit_breaker_policy" json:"circuit_breaker_policy"`
	OutputSpecID                     uuid.UUID `db:"output_spec_id" json:"output_spec_id"`
	RateCardRevisionID               uuid.UUID `db:"rate_card_revision_id" json:"rate_card_revision_id"`
	RateLineID                       uuid.UUID `db:"rate_line_id" json:"rate_line_id"`
	UnitAmountMinor                  int64     `db:"unit_amount_minor" json:"unit_amount_minor"`
	Currency                         string    `db:"currency" json:"currency"`
	CircuitFingerprintWindowSeconds  int32     `db:"circuit_fingerprint_window_seconds" json:"circuit_fingerprint_window_seconds"`
	CircuitMinDistinctHealthyWorkers int32     `db:"circuit_min_distinct_healthy_workers" json:"circuit_min_distinct_healthy_workers"`
}

func (q *Queries) ResolveActiveSKU(ctx context.Context, arg ResolveActiveSKUParams) (ResolveActiveSKURow, error) {
	row := q.db.QueryRow(ctx, resolveActiveSKU,
		arg.Model,
		arg.GenerationPreset,
		arg.ServiceClass,
		arg.OutputSpec,
	)
	var i ResolveActiveSKURow
	err := row.Scan(
		&i.ModelRevisionID,
		&i.GenerationPresetRevisionID,
		&i.CertifiedP95ComputeSeconds,
		&i.ServiceClassRevisionID,
		&i.QueueRetryAllowanceSeconds,
		&i.MaxAttempts,
		&i.MaxTotalComputeMultiplierMilli,
		&i.MaxFinalizationSecondsPerAttempt,
		&i.RetryBackoffPolicy,
		&i.RetryableFailureClasses,
		&i.CircuitBreakerPolicy,
		&i.OutputSpecID,
		&i.RateCardRevisionID,
		&i.RateLineID,
		&i.UnitAmountMinor,
		&i.Currency,
		&i.CircuitFingerprintWindowSeconds,
		&i.CircuitMinDistinctHealthyWorkers,
	)
	return i, err
}

const setRequestContext = `-- name: SetRequestContext :one
SELECT
    context.organization_id::uuid AS organization_id,
    context.project_id::uuid AS project_id,
    context.principal_id::uuid AS principal_id,
    context.transaction_time::timestamptz AS transaction_time
FROM vela_set_request_context(
    $1::uuid,
    $2::bytea,
    $3::text
) AS context
`

type SetRequestContextParams struct {
	CredentialID    uuid.UUID `db:"credential_id" json:"credential_id"`
	CredentialProof []byte    `db:"credential_proof" json:"credential_proof"`
	RequiredScope   string    `db:"required_scope" json:"required_scope"`
}

type SetRequestContextRow struct {
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID       uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID     uuid.UUID          `db:"principal_id" json:"principal_id"`
	TransactionTime pgtype.Timestamptz `db:"transaction_time" json:"transaction_time"`
}

func (q *Queries) SetRequestContext(ctx context.Context, arg SetRequestContextParams) (SetRequestContextRow, error) {
	row := q.db.QueryRow(ctx, setRequestContext, arg.CredentialID, arg.CredentialProof, arg.RequiredScope)
	var i SetRequestContextRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.PrincipalID,
		&i.TransactionTime,
	)
	return i, err
}
