// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_cleanup.sql

package store

import (
	"context"
)

const isArtifactMultipartUploadRecorded = `-- name: IsArtifactMultipartUploadRecorded :one
SELECT EXISTS (
    SELECT 1
    FROM artifact_uploads AS upload
    JOIN artifacts AS artifact ON artifact.id = upload.artifact_id
    WHERE artifact.object_key = $1
      AND upload.multipart_upload_id = $2
)
`

type IsArtifactMultipartUploadRecordedParams struct {
	ObjectKey         string  `db:"object_key" json:"object_key"`
	MultipartUploadID *string `db:"multipart_upload_id" json:"multipart_upload_id"`
}

func (q *Queries) IsArtifactMultipartUploadRecorded(ctx context.Context, arg IsArtifactMultipartUploadRecordedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isArtifactMultipartUploadRecorded, arg.ObjectKey, arg.MultipartUploadID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
