// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_access.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listReadableArtifactSet = `-- name: ListReadableArtifactSet :many
SELECT
    artifact_set.id AS artifact_set_id,
    artifact_set.job_id,
    artifact_set.retention_expires_at,
    artifact_set.committed_at,
    item.artifact_id,
    item.kind,
    item.ordinal,
    item.object_key,
    item.object_version_id,
    item.size_bytes,
    item.sha256,
    item.content_type
FROM jobs AS job
JOIN artifact_sets AS artifact_set
  ON artifact_set.id = job.result_artifact_set_id
 AND artifact_set.job_id = job.id
JOIN artifact_access_grants AS access_grant
  ON access_grant.artifact_set_id = artifact_set.id
 AND access_grant.job_id = job.id
JOIN artifact_set_items AS item
  ON item.artifact_set_id = artifact_set.id
WHERE job.organization_id = $1
  AND job.project_id = $2
  AND job.id = $3
  AND job.state = 'SUCCEEDED'
  AND access_grant.eligible_at <= $4
  AND access_grant.retention_expires_at > $4
  AND access_grant.revoked_at IS NULL
ORDER BY CASE item.kind WHEN 'VIDEO' THEN 0 ELSE 1 END, item.ordinal
`

type ListReadableArtifactSetParams struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	ReadAt         pgtype.Timestamptz `db:"read_at" json:"read_at"`
}

type ListReadableArtifactSetRow struct {
	ArtifactSetID      uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	JobID              uuid.UUID          `db:"job_id" json:"job_id"`
	RetentionExpiresAt pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	CommittedAt        pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	ArtifactID         uuid.UUID          `db:"artifact_id" json:"artifact_id"`
	Kind               ArtifactKind       `db:"kind" json:"kind"`
	Ordinal            int32              `db:"ordinal" json:"ordinal"`
	ObjectKey          string             `db:"object_key" json:"object_key"`
	ObjectVersionID    string             `db:"object_version_id" json:"object_version_id"`
	SizeBytes          int64              `db:"size_bytes" json:"size_bytes"`
	Sha256             []byte             `db:"sha256" json:"sha256"`
	ContentType        string             `db:"content_type" json:"content_type"`
}

func (q *Queries) ListReadableArtifactSet(ctx context.Context, arg ListReadableArtifactSetParams) ([]ListReadableArtifactSetRow, error) {
	rows, err := q.db.Query(ctx, listReadableArtifactSet,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.ReadAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadableArtifactSetRow{}
	for rows.Next() {
		var i ListReadableArtifactSetRow
		if err := rows.Scan(
			&i.ArtifactSetID,
			&i.JobID,
			&i.RetentionExpiresAt,
			&i.CommittedAt,
			&i.ArtifactID,
			&i.Kind,
			&i.Ordinal,
			&i.ObjectKey,
			&i.ObjectVersionID,
			&i.SizeBytes,
			&i.Sha256,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArtifactRequestContext = `-- name: SetArtifactRequestContext :one
SELECT
    organization_id::uuid,
    project_id::uuid,
    principal_id::uuid,
    transaction_time::timestamptz
FROM vela_set_artifact_request_context(
    $1::uuid,
    $2::bytea
)
`

type SetArtifactRequestContextParams struct {
	CredentialID    uuid.UUID `db:"credential_id" json:"credential_id"`
	CredentialProof []byte    `db:"credential_proof" json:"credential_proof"`
}

type SetArtifactRequestContextRow struct {
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID       uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID     uuid.UUID          `db:"principal_id" json:"principal_id"`
	TransactionTime pgtype.Timestamptz `db:"transaction_time" json:"transaction_time"`
}

func (q *Queries) SetArtifactRequestContext(ctx context.Context, arg SetArtifactRequestContextParams) (SetArtifactRequestContextRow, error) {
	row := q.db.QueryRow(ctx, setArtifactRequestContext, arg.CredentialID, arg.CredentialProof)
	var i SetArtifactRequestContextRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.PrincipalID,
		&i.TransactionTime,
	)
	return i, err
}
