// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignment.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decrementPoolQueuedForAssignment = `-- name: DecrementPoolQueuedForAssignment :execrows
UPDATE worker_pools
SET queued_count = queued_count - 1
WHERE id = $1
  AND queued_count > 0
`

func (q *Queries) DecrementPoolQueuedForAssignment(ctx context.Context, workerPoolID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decrementPoolQueuedForAssignment, workerPoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveWorkerAssignment = `-- name: GetActiveWorkerAssignment :one
SELECT
    a.id AS attempt_id,
    a.job_id,
    a.execution_profile_revision_id,
    a.attempt_number,
    a.worker_id,
    a.worker_epoch,
    a.fence,
    l.signing_key_id,
    l.token_digest,
    l.issued_at,
    l.token_claim_expires_at,
    l.expires_at
FROM attempts AS a
JOIN attempt_leases AS l ON l.attempt_id = a.id
WHERE a.worker_id = $1
  AND a.worker_epoch = $2
  AND a.state IN ('ASSIGNED', 'RUNNING', 'FINALIZING')
  AND l.phase = 'EXECUTION'
  AND l.owner_kind = 'WORKER'
  AND l.owner_id = $3
  AND l.revoked_at IS NULL
ORDER BY a.assigned_at DESC
LIMIT 1
FOR UPDATE OF a, l
`

type GetActiveWorkerAssignmentParams struct {
	WorkerID    uuid.UUID `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64     `db:"worker_epoch" json:"worker_epoch"`
	OwnerID     string    `db:"owner_id" json:"owner_id"`
}

type GetActiveWorkerAssignmentRow struct {
	AttemptID                  uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	JobID                      uuid.UUID          `db:"job_id" json:"job_id"`
	ExecutionProfileRevisionID uuid.UUID          `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	AttemptNumber              int32              `db:"attempt_number" json:"attempt_number"`
	WorkerID                   uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch                int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence                      int64              `db:"fence" json:"fence"`
	SigningKeyID               string             `db:"signing_key_id" json:"signing_key_id"`
	TokenDigest                []byte             `db:"token_digest" json:"token_digest"`
	IssuedAt                   pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	TokenClaimExpiresAt        pgtype.Timestamptz `db:"token_claim_expires_at" json:"token_claim_expires_at"`
	ExpiresAt                  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetActiveWorkerAssignment(ctx context.Context, arg GetActiveWorkerAssignmentParams) (GetActiveWorkerAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkerAssignment, arg.WorkerID, arg.WorkerEpoch, arg.OwnerID)
	var i GetActiveWorkerAssignmentRow
	err := row.Scan(
		&i.AttemptID,
		&i.JobID,
		&i.ExecutionProfileRevisionID,
		&i.AttemptNumber,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.Fence,
		&i.SigningKeyID,
		&i.TokenDigest,
		&i.IssuedAt,
		&i.TokenClaimExpiresAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPostgresTime = `-- name: GetPostgresTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) GetPostgresTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPostgresTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementAttemptsStarted = `-- name: IncrementAttemptsStarted :execrows
UPDATE retry_runtime_states
SET attempts_started = attempts_started + 1,
    next_retry_at = NULL,
    version = version + 1,
    updated_at = $1
WHERE job_id = $2
  AND attempts_started = $3
  AND version = $4
`

type IncrementAttemptsStartedParams struct {
	AssignedAt              pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	JobID                   uuid.UUID          `db:"job_id" json:"job_id"`
	PreviousAttemptsStarted int32              `db:"previous_attempts_started" json:"previous_attempts_started"`
	ExpectedVersion         int64              `db:"expected_version" json:"expected_version"`
}

func (q *Queries) IncrementAttemptsStarted(ctx context.Context, arg IncrementAttemptsStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementAttemptsStarted,
		arg.AssignedAt,
		arg.JobID,
		arg.PreviousAttemptsStarted,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAssignmentOutboxEvent = `-- name: InsertAssignmentOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    organization_id,
    project_id,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_type,
    schema_version,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    'Job',
    $4,
    $5,
    'job.assigned',
    1,
    $6,
    $7
)
`

type InsertAssignmentOutboxEventParams struct {
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	JobVersion     int64              `db:"job_version" json:"job_version"`
	Payload        []byte             `db:"payload" json:"payload"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertAssignmentOutboxEvent(ctx context.Context, arg InsertAssignmentOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertAssignmentOutboxEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.JobVersion,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO attempts (
    id,
    organization_id,
    project_id,
    job_id,
    attempt_number,
    execution_profile_revision_id,
    worker_pool_id,
    worker_id,
    worker_epoch,
    state,
    fence,
    assigned_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'ASSIGNED',
    $10,
    $11
)
`

type InsertAttemptParams struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	OrganizationID             uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                  uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                      uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptNumber              int32              `db:"attempt_number" json:"attempt_number"`
	ExecutionProfileRevisionID uuid.UUID          `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	WorkerPoolID               uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	WorkerID                   uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch                int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence                      int64              `db:"fence" json:"fence"`
	AssignedAt                 pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptNumber,
		arg.ExecutionProfileRevisionID,
		arg.WorkerPoolID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
		arg.AssignedAt,
	)
	return err
}

const insertExecutionLease = `-- name: InsertExecutionLease :exec
INSERT INTO attempt_leases (
    id,
    organization_id,
    project_id,
    attempt_id,
    worker_id,
    worker_epoch,
    phase,
    owner_kind,
    owner_id,
    fence,
    token_digest,
    signing_key_id,
    issued_at,
    renewal_protocol_version,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'EXECUTION',
    'WORKER',
    $7,
    $8,
    $9,
    $10,
    $11,
    2,
    $12
)
`

type InsertExecutionLeaseParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	AttemptID      uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID       uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch    int64              `db:"worker_epoch" json:"worker_epoch"`
	OwnerID        string             `db:"owner_id" json:"owner_id"`
	Fence          int64              `db:"fence" json:"fence"`
	TokenDigest    []byte             `db:"token_digest" json:"token_digest"`
	SigningKeyID   string             `db:"signing_key_id" json:"signing_key_id"`
	IssuedAt       pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertExecutionLease(ctx context.Context, arg InsertExecutionLeaseParams) error {
	_, err := q.db.Exec(ctx, insertExecutionLease,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.OwnerID,
		arg.Fence,
		arg.TokenDigest,
		arg.SigningKeyID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const listActiveLeaseSigningKeyIDs = `-- name: ListActiveLeaseSigningKeyIDs :many
SELECT DISTINCT signing_key_id
FROM attempt_leases
WHERE revoked_at IS NULL
  AND expires_at > clock_timestamp()
ORDER BY signing_key_id
`

func (q *Queries) ListActiveLeaseSigningKeyIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveLeaseSigningKeyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var signing_key_id string
		if err := rows.Scan(&signing_key_id); err != nil {
			return nil, err
		}
		items = append(items, signing_key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJobForAssignment = `-- name: LockJobForAssignment :one
SELECT
    j.id,
    j.organization_id,
    j.project_id,
    j.state,
    j.version,
    j.model_revision_id,
    j.generation_preset_revision_id,
    scr.state AS service_class_revision_state,
    j.output_spec_id,
    j.worker_pool_id,
    j.execution_max_attempts,
    j.execution_max_total_compute_seconds,
    j.job_expires_at,
    j.current_fence,
    cr.state AS credit_reservation_state,
    rts.attempts_started,
    rts.compute_seconds_consumed,
    rts.next_retry_at,
	ere.excluded_workers,
    rts.version AS retry_runtime_version
FROM jobs AS j
JOIN credit_reservations AS cr ON cr.job_id = j.id
JOIN retry_runtime_states AS rts ON rts.job_id = j.id
JOIN execution_retry_evidence AS ere ON ere.job_id = j.id
JOIN service_class_revisions AS scr ON scr.id = j.service_class_revision_id
WHERE j.id = $1
FOR UPDATE OF j, cr, rts, ere
FOR SHARE OF scr
`

type LockJobForAssignmentRow struct {
	ID                              uuid.UUID              `db:"id" json:"id"`
	OrganizationID                  uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID                       uuid.UUID              `db:"project_id" json:"project_id"`
	State                           JobState               `db:"state" json:"state"`
	Version                         int64                  `db:"version" json:"version"`
	ModelRevisionID                 uuid.UUID              `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID      uuid.UUID              `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	ServiceClassRevisionState       CatalogState           `db:"service_class_revision_state" json:"service_class_revision_state"`
	OutputSpecID                    uuid.UUID              `db:"output_spec_id" json:"output_spec_id"`
	WorkerPoolID                    uuid.UUID              `db:"worker_pool_id" json:"worker_pool_id"`
	ExecutionMaxAttempts            int32                  `db:"execution_max_attempts" json:"execution_max_attempts"`
	ExecutionMaxTotalComputeSeconds int64                  `db:"execution_max_total_compute_seconds" json:"execution_max_total_compute_seconds"`
	JobExpiresAt                    pgtype.Timestamptz     `db:"job_expires_at" json:"job_expires_at"`
	CurrentFence                    int64                  `db:"current_fence" json:"current_fence"`
	CreditReservationState          CreditReservationState `db:"credit_reservation_state" json:"credit_reservation_state"`
	AttemptsStarted                 int32                  `db:"attempts_started" json:"attempts_started"`
	ComputeSecondsConsumed          int64                  `db:"compute_seconds_consumed" json:"compute_seconds_consumed"`
	NextRetryAt                     pgtype.Timestamptz     `db:"next_retry_at" json:"next_retry_at"`
	ExcludedWorkers                 []byte                 `db:"excluded_workers" json:"excluded_workers"`
	RetryRuntimeVersion             int64                  `db:"retry_runtime_version" json:"retry_runtime_version"`
}

func (q *Queries) LockJobForAssignment(ctx context.Context, jobID uuid.UUID) (LockJobForAssignmentRow, error) {
	row := q.db.QueryRow(ctx, lockJobForAssignment, jobID)
	var i LockJobForAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.State,
		&i.Version,
		&i.ModelRevisionID,
		&i.GenerationPresetRevisionID,
		&i.ServiceClassRevisionState,
		&i.OutputSpecID,
		&i.WorkerPoolID,
		&i.ExecutionMaxAttempts,
		&i.ExecutionMaxTotalComputeSeconds,
		&i.JobExpiresAt,
		&i.CurrentFence,
		&i.CreditReservationState,
		&i.AttemptsStarted,
		&i.ComputeSecondsConsumed,
		&i.NextRetryAt,
		&i.ExcludedWorkers,
		&i.RetryRuntimeVersion,
	)
	return i, err
}

const lockProjectForAssignment = `-- name: LockProjectForAssignment :one
SELECT queued_count, retry_wait_count, running_count, running_limit
FROM projects
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockProjectForAssignmentParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

type LockProjectForAssignmentRow struct {
	QueuedCount    int32 `db:"queued_count" json:"queued_count"`
	RetryWaitCount int32 `db:"retry_wait_count" json:"retry_wait_count"`
	RunningCount   int32 `db:"running_count" json:"running_count"`
	RunningLimit   int32 `db:"running_limit" json:"running_limit"`
}

func (q *Queries) LockProjectForAssignment(ctx context.Context, arg LockProjectForAssignmentParams) (LockProjectForAssignmentRow, error) {
	row := q.db.QueryRow(ctx, lockProjectForAssignment, arg.OrganizationID, arg.ProjectID)
	var i LockProjectForAssignmentRow
	err := row.Scan(
		&i.QueuedCount,
		&i.RetryWaitCount,
		&i.RunningCount,
		&i.RunningLimit,
	)
	return i, err
}

const lockWorkerAuthority = `-- name: LockWorkerAuthority :one
SELECT id, worker_pool_id, spiffe_id, epoch, lifecycle_state, reachability_condition
FROM workers
WHERE id = $1
FOR UPDATE
`

type LockWorkerAuthorityRow struct {
	ID                    uuid.UUID                   `db:"id" json:"id"`
	WorkerPoolID          uuid.UUID                   `db:"worker_pool_id" json:"worker_pool_id"`
	SpiffeID              string                      `db:"spiffe_id" json:"spiffe_id"`
	Epoch                 int64                       `db:"epoch" json:"epoch"`
	LifecycleState        WorkerLifecycleState        `db:"lifecycle_state" json:"lifecycle_state"`
	ReachabilityCondition WorkerReachabilityCondition `db:"reachability_condition" json:"reachability_condition"`
}

func (q *Queries) LockWorkerAuthority(ctx context.Context, workerID uuid.UUID) (LockWorkerAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockWorkerAuthority, workerID)
	var i LockWorkerAuthorityRow
	err := row.Scan(
		&i.ID,
		&i.WorkerPoolID,
		&i.SpiffeID,
		&i.Epoch,
		&i.LifecycleState,
		&i.ReachabilityCondition,
	)
	return i, err
}

const markJobAssigned = `-- name: MarkJobAssigned :one
UPDATE jobs
SET state = 'ASSIGNED',
    version = version + 1,
    current_fence = $1,
    updated_at = $2
WHERE id = $3
  AND version = $4
  AND state IN ('QUEUED', 'RETRY_WAIT')
RETURNING version
`

type MarkJobAssignedParams struct {
	Fence           int64              `db:"fence" json:"fence"`
	AssignedAt      pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion int64              `db:"expected_version" json:"expected_version"`
}

func (q *Queries) MarkJobAssigned(ctx context.Context, arg MarkJobAssignedParams) (int64, error) {
	row := q.db.QueryRow(ctx, markJobAssigned,
		arg.Fence,
		arg.AssignedAt,
		arg.JobID,
		arg.ExpectedVersion,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const markWorkerBusy = `-- name: MarkWorkerBusy :execrows
UPDATE workers
SET lifecycle_state = 'BUSY', updated_at = $1
WHERE id = $2
  AND epoch = $3
  AND lifecycle_state = 'READY'
  AND reachability_condition = 'HEALTHY'
`

type MarkWorkerBusyParams struct {
	AssignedAt  pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
}

func (q *Queries) MarkWorkerBusy(ctx context.Context, arg MarkWorkerBusyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkerBusy, arg.AssignedAt, arg.WorkerID, arg.WorkerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveProjectCountersToRunning = `-- name: MoveProjectCountersToRunning :execrows
UPDATE projects
SET queued_count = queued_count - 1,
    running_count = running_count + 1
WHERE organization_id = $1
  AND id = $2
  AND queued_count > 0
  AND running_count < running_limit
`

type MoveProjectCountersToRunningParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) MoveProjectCountersToRunning(ctx context.Context, arg MoveProjectCountersToRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveProjectCountersToRunning, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveWorkerBySPIFFEID = `-- name: ResolveWorkerBySPIFFEID :one
SELECT id
FROM workers
WHERE spiffe_id = $1
`

func (q *Queries) ResolveWorkerBySPIFFEID(ctx context.Context, spiffeID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveWorkerBySPIFFEID, spiffeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const validateProfileForAssignment = `-- name: ValidateProfileForAssignment :one
SELECT epr.id
FROM execution_profile_revisions AS epr
JOIN profile_certifications AS pc
  ON pc.execution_profile_revision_id = epr.id
WHERE epr.id = $1
  AND epr.model_revision_id = $2
  AND epr.worker_pool_id = $3
  AND epr.state = 'ACTIVE'
  AND pc.model_revision_id = $2
  AND pc.generation_preset_revision_id = $4
  AND pc.output_spec_id = $5
  AND pc.state = 'ACTIVE'
  AND pc.invalidated_at IS NULL
LIMIT 1
FOR SHARE OF epr, pc
`

type ValidateProfileForAssignmentParams struct {
	ExecutionProfileRevisionID uuid.UUID `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	ModelRevisionID            uuid.UUID `db:"model_revision_id" json:"model_revision_id"`
	WorkerPoolID               uuid.UUID `db:"worker_pool_id" json:"worker_pool_id"`
	GenerationPresetRevisionID uuid.UUID `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	OutputSpecID               uuid.UUID `db:"output_spec_id" json:"output_spec_id"`
}

func (q *Queries) ValidateProfileForAssignment(ctx context.Context, arg ValidateProfileForAssignmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, validateProfileForAssignment,
		arg.ExecutionProfileRevisionID,
		arg.ModelRevisionID,
		arg.WorkerPoolID,
		arg.GenerationPresetRevisionID,
		arg.OutputSpecID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
