// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cancellation.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
SELECT
    coalesce(
        result.cancellation_id,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS cancellation_id,
    result.job_id::uuid AS job_id,
    result.decision::cancellation_decision AS decision,
    result.job_state::job_state AS job_state,
    result.previous_job_state::job_state AS previous_job_state,
    result.job_version::bigint AS job_version,
    result.cancellation_fence::bigint AS cancellation_fence,
    coalesce(
        result.attempt_id,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS attempt_id,
    coalesce(
        result.worker_id,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS worker_id,
    coalesce(result.worker_epoch, 0)::bigint AS worker_epoch,
    coalesce(result.attempt_fence, 0)::bigint AS attempt_fence,
    coalesce(
        result.authority_lease_id,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS authority_lease_id,
    coalesce(result.authority_lease_phase::text, '')::text AS authority_lease_phase,
    coalesce(result.authority_lease_owner_kind::text, '')::text AS authority_lease_owner_kind,
    coalesce(result.authority_lease_owner_id, '')::text AS authority_lease_owner_id,
    coalesce(
        result.authority_lease_expires_at,
        'epoch'::timestamptz
    )::timestamptz AS authority_lease_expires_at,
    result.billable::boolean AS billable,
    coalesce(
        result.charge_id,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS charge_id,
    coalesce(result.charge_amount_minor, 0)::bigint AS charge_amount_minor,
    coalesce(result.charge_currency, '')::text AS charge_currency,
    coalesce(result.charge_reason::text, '')::text AS charge_reason,
    coalesce(result.charge_posted_at, 'epoch'::timestamptz)::timestamptz AS charge_posted_at,
    result.decided_at::timestamptz AS decided_at,
    result.created::boolean AS created
FROM vela_cancel_job(
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::uuid,
    $5::uuid,
    $6::uuid,
    $7::uuid,
    $8::uuid
) AS result
`

type CancelJobParams struct {
	JobID                  uuid.UUID `db:"job_id" json:"job_id"`
	CancellationID         uuid.UUID `db:"cancellation_id" json:"cancellation_id"`
	ChargeID               uuid.UUID `db:"charge_id" json:"charge_id"`
	CancelRequestedEventID uuid.UUID `db:"cancel_requested_event_id" json:"cancel_requested_event_id"`
	CancelingEventID       uuid.UUID `db:"canceling_event_id" json:"canceling_event_id"`
	CanceledEventID        uuid.UUID `db:"canceled_event_id" json:"canceled_event_id"`
	ChargePostedEventID    uuid.UUID `db:"charge_posted_event_id" json:"charge_posted_event_id"`
	InvoiceExportEventID   uuid.UUID `db:"invoice_export_event_id" json:"invoice_export_event_id"`
}

type CancelJobRow struct {
	CancellationID          uuid.UUID            `db:"cancellation_id" json:"cancellation_id"`
	JobID                   uuid.UUID            `db:"job_id" json:"job_id"`
	Decision                CancellationDecision `db:"decision" json:"decision"`
	JobState                JobState             `db:"job_state" json:"job_state"`
	PreviousJobState        JobState             `db:"previous_job_state" json:"previous_job_state"`
	JobVersion              int64                `db:"job_version" json:"job_version"`
	CancellationFence       int64                `db:"cancellation_fence" json:"cancellation_fence"`
	AttemptID               uuid.UUID            `db:"attempt_id" json:"attempt_id"`
	WorkerID                uuid.UUID            `db:"worker_id" json:"worker_id"`
	WorkerEpoch             int64                `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence            int64                `db:"attempt_fence" json:"attempt_fence"`
	AuthorityLeaseID        uuid.UUID            `db:"authority_lease_id" json:"authority_lease_id"`
	AuthorityLeasePhase     string               `db:"authority_lease_phase" json:"authority_lease_phase"`
	AuthorityLeaseOwnerKind string               `db:"authority_lease_owner_kind" json:"authority_lease_owner_kind"`
	AuthorityLeaseOwnerID   string               `db:"authority_lease_owner_id" json:"authority_lease_owner_id"`
	AuthorityLeaseExpiresAt pgtype.Timestamptz   `db:"authority_lease_expires_at" json:"authority_lease_expires_at"`
	Billable                bool                 `db:"billable" json:"billable"`
	ChargeID                uuid.UUID            `db:"charge_id" json:"charge_id"`
	ChargeAmountMinor       int64                `db:"charge_amount_minor" json:"charge_amount_minor"`
	ChargeCurrency          string               `db:"charge_currency" json:"charge_currency"`
	ChargeReason            string               `db:"charge_reason" json:"charge_reason"`
	ChargePostedAt          pgtype.Timestamptz   `db:"charge_posted_at" json:"charge_posted_at"`
	DecidedAt               pgtype.Timestamptz   `db:"decided_at" json:"decided_at"`
	Created                 bool                 `db:"created" json:"created"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (CancelJobRow, error) {
	row := q.db.QueryRow(ctx, cancelJob,
		arg.JobID,
		arg.CancellationID,
		arg.ChargeID,
		arg.CancelRequestedEventID,
		arg.CancelingEventID,
		arg.CanceledEventID,
		arg.ChargePostedEventID,
		arg.InvoiceExportEventID,
	)
	var i CancelJobRow
	err := row.Scan(
		&i.CancellationID,
		&i.JobID,
		&i.Decision,
		&i.JobState,
		&i.PreviousJobState,
		&i.JobVersion,
		&i.CancellationFence,
		&i.AttemptID,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.AttemptFence,
		&i.AuthorityLeaseID,
		&i.AuthorityLeasePhase,
		&i.AuthorityLeaseOwnerKind,
		&i.AuthorityLeaseOwnerID,
		&i.AuthorityLeaseExpiresAt,
		&i.Billable,
		&i.ChargeID,
		&i.ChargeAmountMinor,
		&i.ChargeCurrency,
		&i.ChargeReason,
		&i.ChargePostedAt,
		&i.DecidedAt,
		&i.Created,
	)
	return i, err
}

const completeCancelingJob = `-- name: CompleteCancelingJob :one
UPDATE jobs
SET state = 'CANCELED',
    version = version + 1,
    updated_at = $1
WHERE id = $2
  AND state = 'CANCELING'
  AND version = $3
  AND current_fence = $4
RETURNING version
`

type CompleteCancelingJobParams struct {
	StoppedAt         pgtype.Timestamptz `db:"stopped_at" json:"stopped_at"`
	JobID             uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion   int64              `db:"expected_version" json:"expected_version"`
	CancellationFence int64              `db:"cancellation_fence" json:"cancellation_fence"`
}

func (q *Queries) CompleteCancelingJob(ctx context.Context, arg CompleteCancelingJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, completeCancelingJob,
		arg.StoppedAt,
		arg.JobID,
		arg.ExpectedVersion,
		arg.CancellationFence,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const findNextCancellationStopCandidate = `-- name: FindNextCancellationStopCandidate :one
SELECT
    d.id AS cancellation_id,
    d.attempt_id::uuid AS attempt_id,
    d.worker_id::uuid AS worker_id,
    d.authority_lease_id::uuid AS authority_lease_id
FROM job_cancellation_decisions AS d
JOIN attempt_leases AS l ON l.id = d.authority_lease_id
LEFT JOIN cancellation_stop_receipts AS r ON r.cancellation_id = d.id
WHERE d.attempt_id IS NOT NULL
  AND d.worker_id IS NOT NULL
  AND d.authority_lease_id IS NOT NULL
  AND d.authority_lease_phase IS NOT NULL
  AND d.authority_lease_owner_kind IS NOT NULL
  AND d.authority_lease_expires_at IS NOT NULL
  AND l.revoked_at IS NOT NULL
  AND d.authority_lease_expires_at <= clock_timestamp()
  AND r.id IS NULL
ORDER BY d.authority_lease_expires_at, d.decided_at, d.id
LIMIT 1
`

type FindNextCancellationStopCandidateRow struct {
	CancellationID   uuid.UUID `db:"cancellation_id" json:"cancellation_id"`
	AttemptID        uuid.UUID `db:"attempt_id" json:"attempt_id"`
	WorkerID         uuid.UUID `db:"worker_id" json:"worker_id"`
	AuthorityLeaseID uuid.UUID `db:"authority_lease_id" json:"authority_lease_id"`
}

func (q *Queries) FindNextCancellationStopCandidate(ctx context.Context) (FindNextCancellationStopCandidateRow, error) {
	row := q.db.QueryRow(ctx, findNextCancellationStopCandidate)
	var i FindNextCancellationStopCandidateRow
	err := row.Scan(
		&i.CancellationID,
		&i.AttemptID,
		&i.WorkerID,
		&i.AuthorityLeaseID,
	)
	return i, err
}

const getCancellationStopLeaseID = `-- name: GetCancellationStopLeaseID :one
SELECT authority_lease_id::uuid
FROM job_cancellation_decisions
WHERE id = $1
  AND attempt_id = $2::uuid
  AND authority_lease_id IS NOT NULL
`

type GetCancellationStopLeaseIDParams struct {
	CancellationID uuid.UUID `db:"cancellation_id" json:"cancellation_id"`
	AttemptID      uuid.UUID `db:"attempt_id" json:"attempt_id"`
}

func (q *Queries) GetCancellationStopLeaseID(ctx context.Context, arg GetCancellationStopLeaseIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCancellationStopLeaseID, arg.CancellationID, arg.AttemptID)
	var authority_lease_id uuid.UUID
	err := row.Scan(&authority_lease_id)
	return authority_lease_id, err
}

const insertCancellationStopReceipt = `-- name: InsertCancellationStopReceipt :exec
INSERT INTO cancellation_stop_receipts (
    id,
    organization_id,
    project_id,
    job_id,
    cancellation_id,
    attempt_id,
    worker_id,
    worker_epoch,
    attempt_fence,
    cancellation_fence,
    source,
    terminal_job_version,
    stopped_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::cancellation_stop_source,
    $12,
    $13
)
`

type InsertCancellationStopReceiptParams struct {
	ID                 uuid.UUID              `db:"id" json:"id"`
	OrganizationID     uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID          uuid.UUID              `db:"project_id" json:"project_id"`
	JobID              uuid.UUID              `db:"job_id" json:"job_id"`
	CancellationID     uuid.UUID              `db:"cancellation_id" json:"cancellation_id"`
	AttemptID          uuid.UUID              `db:"attempt_id" json:"attempt_id"`
	WorkerID           uuid.UUID              `db:"worker_id" json:"worker_id"`
	WorkerEpoch        int64                  `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence       int64                  `db:"attempt_fence" json:"attempt_fence"`
	CancellationFence  int64                  `db:"cancellation_fence" json:"cancellation_fence"`
	Source             CancellationStopSource `db:"source" json:"source"`
	TerminalJobVersion int64                  `db:"terminal_job_version" json:"terminal_job_version"`
	StoppedAt          pgtype.Timestamptz     `db:"stopped_at" json:"stopped_at"`
}

func (q *Queries) InsertCancellationStopReceipt(ctx context.Context, arg InsertCancellationStopReceiptParams) error {
	_, err := q.db.Exec(ctx, insertCancellationStopReceipt,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.CancellationID,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.AttemptFence,
		arg.CancellationFence,
		arg.Source,
		arg.TerminalJobVersion,
		arg.StoppedAt,
	)
	return err
}

const insertCancellationStoppedOutboxEvent = `-- name: InsertCancellationStoppedOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    organization_id,
    project_id,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_type,
    schema_version,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    'Job',
    $4,
    $5,
    'job.canceled',
    1,
    $6,
    $7
)
`

type InsertCancellationStoppedOutboxEventParams struct {
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	JobVersion     int64              `db:"job_version" json:"job_version"`
	Payload        []byte             `db:"payload" json:"payload"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertCancellationStoppedOutboxEvent(ctx context.Context, arg InsertCancellationStoppedOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertCancellationStoppedOutboxEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.JobVersion,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listSucceededArtifactSetForCancellation = `-- name: ListSucceededArtifactSetForCancellation :many
SELECT
    artifact_set.id::uuid AS artifact_set_id,
    artifact_set.manifest_sha256::bytea AS manifest_sha256,
    artifact_set.retention_expires_at::timestamptz AS retention_expires_at,
    completion.completed_at::timestamptz AS completed_at,
    completion.charge_id::uuid AS charge_id,
    item.artifact_id::uuid AS artifact_id,
    item.kind::text AS kind,
    item.ordinal::integer AS ordinal,
    item.object_key::text AS object_key,
    item.object_version_id::text AS object_version_id,
    item.size_bytes::bigint AS size_bytes,
    item.sha256::bytea AS sha256,
    item.content_type::text AS content_type
FROM jobs AS job
JOIN artifact_sets AS artifact_set
  ON artifact_set.id = job.result_artifact_set_id
 AND artifact_set.job_id = job.id
JOIN visible_completions AS completion
  ON completion.artifact_set_id = artifact_set.id
 AND completion.job_id = job.id
JOIN artifact_set_items AS item
  ON item.artifact_set_id = artifact_set.id
WHERE job.id = $1::uuid
  AND job.organization_id = $2::uuid
  AND job.project_id = $3::uuid
  AND job.state = 'SUCCEEDED'
ORDER BY CASE item.kind WHEN 'VIDEO' THEN 0 ELSE 1 END, item.ordinal
`

type ListSucceededArtifactSetForCancellationParams struct {
	JobID          uuid.UUID `db:"job_id" json:"job_id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

type ListSucceededArtifactSetForCancellationRow struct {
	ArtifactSetID      uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	ManifestSha256     []byte             `db:"manifest_sha256" json:"manifest_sha256"`
	RetentionExpiresAt pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ChargeID           uuid.UUID          `db:"charge_id" json:"charge_id"`
	ArtifactID         uuid.UUID          `db:"artifact_id" json:"artifact_id"`
	Kind               string             `db:"kind" json:"kind"`
	Ordinal            int32              `db:"ordinal" json:"ordinal"`
	ObjectKey          string             `db:"object_key" json:"object_key"`
	ObjectVersionID    string             `db:"object_version_id" json:"object_version_id"`
	SizeBytes          int64              `db:"size_bytes" json:"size_bytes"`
	Sha256             []byte             `db:"sha256" json:"sha256"`
	ContentType        string             `db:"content_type" json:"content_type"`
}

func (q *Queries) ListSucceededArtifactSetForCancellation(ctx context.Context, arg ListSucceededArtifactSetForCancellationParams) ([]ListSucceededArtifactSetForCancellationRow, error) {
	rows, err := q.db.Query(ctx, listSucceededArtifactSetForCancellation, arg.JobID, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSucceededArtifactSetForCancellationRow{}
	for rows.Next() {
		var i ListSucceededArtifactSetForCancellationRow
		if err := rows.Scan(
			&i.ArtifactSetID,
			&i.ManifestSha256,
			&i.RetentionExpiresAt,
			&i.CompletedAt,
			&i.ChargeID,
			&i.ArtifactID,
			&i.Kind,
			&i.Ordinal,
			&i.ObjectKey,
			&i.ObjectVersionID,
			&i.SizeBytes,
			&i.Sha256,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCancellationAttempt = `-- name: LockCancellationAttempt :one
SELECT
    id,
    organization_id,
    project_id,
    job_id,
    worker_id,
    worker_epoch,
    fence,
    state,
    ended_at
FROM attempts
WHERE id = $1
FOR UPDATE
`

type LockCancellationAttemptRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	WorkerID       uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch    int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence          int64              `db:"fence" json:"fence"`
	State          AttemptState       `db:"state" json:"state"`
	EndedAt        pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
}

func (q *Queries) LockCancellationAttempt(ctx context.Context, attemptID uuid.UUID) (LockCancellationAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockCancellationAttempt, attemptID)
	var i LockCancellationAttemptRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.JobID,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.Fence,
		&i.State,
		&i.EndedAt,
	)
	return i, err
}

const lockCancellationLease = `-- name: LockCancellationLease :one
SELECT
    id,
    attempt_id,
    worker_id,
    worker_epoch,
    phase,
    owner_kind,
    owner_id,
    fence,
    token_digest,
    expires_at,
    revoked_at
FROM attempt_leases
WHERE id = $1
  AND attempt_id = $2
FOR UPDATE
`

type LockCancellationLeaseParams struct {
	AuthorityLeaseID uuid.UUID `db:"authority_lease_id" json:"authority_lease_id"`
	AttemptID        uuid.UUID `db:"attempt_id" json:"attempt_id"`
}

type LockCancellationLeaseRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	AttemptID   uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
	Phase       LeasePhase         `db:"phase" json:"phase"`
	OwnerKind   LeaseOwnerKind     `db:"owner_kind" json:"owner_kind"`
	OwnerID     string             `db:"owner_id" json:"owner_id"`
	Fence       int64              `db:"fence" json:"fence"`
	TokenDigest []byte             `db:"token_digest" json:"token_digest"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) LockCancellationLease(ctx context.Context, arg LockCancellationLeaseParams) (LockCancellationLeaseRow, error) {
	row := q.db.QueryRow(ctx, lockCancellationLease, arg.AuthorityLeaseID, arg.AttemptID)
	var i LockCancellationLeaseRow
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.Phase,
		&i.OwnerKind,
		&i.OwnerID,
		&i.Fence,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockCancellationStopAuthority = `-- name: LockCancellationStopAuthority :one
SELECT
    d.id AS cancellation_id,
    d.organization_id,
    d.project_id,
    d.job_id,
    d.decision,
    d.billable,
    coalesce(d.attempt_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid
        AS attempt_id,
    coalesce(d.worker_id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid
        AS worker_id,
    coalesce(d.worker_epoch, 0)::bigint AS worker_epoch,
    coalesce(d.attempt_fence, 0)::bigint AS attempt_fence,
    coalesce(
        d.authority_lease_id,
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS authority_lease_id,
    coalesce(d.authority_lease_phase::text, '')::text AS authority_lease_phase,
    coalesce(d.authority_lease_owner_kind::text, '')::text AS authority_lease_owner_kind,
    coalesce(d.authority_lease_owner_id, '')::text AS authority_lease_owner_id,
    coalesce(d.authority_lease_expires_at, 'epoch'::timestamptz)::timestamptz
        AS authority_lease_expires_at,
    d.cancellation_fence,
    d.job_version AS decision_job_version,
    d.decided_at,
    j.state AS job_state,
    j.version AS job_version,
    coalesce(c.id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS charge_id,
    coalesce(r.id, '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS receipt_id,
    coalesce(r.source::text, '')::text AS receipt_source,
    coalesce(r.terminal_job_version, 0)::bigint AS receipt_job_version,
    coalesce(r.stopped_at, 'epoch'::timestamptz)::timestamptz AS receipt_stopped_at
FROM job_cancellation_decisions AS d
JOIN jobs AS j ON j.id = d.job_id
LEFT JOIN charges AS c ON c.cancellation_id = d.id
LEFT JOIN cancellation_stop_receipts AS r ON r.cancellation_id = d.id
WHERE d.id = $1
FOR UPDATE OF j
`

type LockCancellationStopAuthorityRow struct {
	CancellationID          uuid.UUID            `db:"cancellation_id" json:"cancellation_id"`
	OrganizationID          uuid.UUID            `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID            `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID            `db:"job_id" json:"job_id"`
	Decision                CancellationDecision `db:"decision" json:"decision"`
	Billable                bool                 `db:"billable" json:"billable"`
	AttemptID               uuid.UUID            `db:"attempt_id" json:"attempt_id"`
	WorkerID                uuid.UUID            `db:"worker_id" json:"worker_id"`
	WorkerEpoch             int64                `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence            int64                `db:"attempt_fence" json:"attempt_fence"`
	AuthorityLeaseID        uuid.UUID            `db:"authority_lease_id" json:"authority_lease_id"`
	AuthorityLeasePhase     string               `db:"authority_lease_phase" json:"authority_lease_phase"`
	AuthorityLeaseOwnerKind string               `db:"authority_lease_owner_kind" json:"authority_lease_owner_kind"`
	AuthorityLeaseOwnerID   string               `db:"authority_lease_owner_id" json:"authority_lease_owner_id"`
	AuthorityLeaseExpiresAt pgtype.Timestamptz   `db:"authority_lease_expires_at" json:"authority_lease_expires_at"`
	CancellationFence       int64                `db:"cancellation_fence" json:"cancellation_fence"`
	DecisionJobVersion      int64                `db:"decision_job_version" json:"decision_job_version"`
	DecidedAt               pgtype.Timestamptz   `db:"decided_at" json:"decided_at"`
	JobState                JobState             `db:"job_state" json:"job_state"`
	JobVersion              int64                `db:"job_version" json:"job_version"`
	ChargeID                uuid.UUID            `db:"charge_id" json:"charge_id"`
	ReceiptID               uuid.UUID            `db:"receipt_id" json:"receipt_id"`
	ReceiptSource           string               `db:"receipt_source" json:"receipt_source"`
	ReceiptJobVersion       int64                `db:"receipt_job_version" json:"receipt_job_version"`
	ReceiptStoppedAt        pgtype.Timestamptz   `db:"receipt_stopped_at" json:"receipt_stopped_at"`
}

func (q *Queries) LockCancellationStopAuthority(ctx context.Context, cancellationID uuid.UUID) (LockCancellationStopAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockCancellationStopAuthority, cancellationID)
	var i LockCancellationStopAuthorityRow
	err := row.Scan(
		&i.CancellationID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.JobID,
		&i.Decision,
		&i.Billable,
		&i.AttemptID,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.AttemptFence,
		&i.AuthorityLeaseID,
		&i.AuthorityLeasePhase,
		&i.AuthorityLeaseOwnerKind,
		&i.AuthorityLeaseOwnerID,
		&i.AuthorityLeaseExpiresAt,
		&i.CancellationFence,
		&i.DecisionJobVersion,
		&i.DecidedAt,
		&i.JobState,
		&i.JobVersion,
		&i.ChargeID,
		&i.ReceiptID,
		&i.ReceiptSource,
		&i.ReceiptJobVersion,
		&i.ReceiptStoppedAt,
	)
	return i, err
}

const releaseWorkerAfterCancellationStop = `-- name: ReleaseWorkerAfterCancellationStop :execrows
UPDATE workers
SET lifecycle_state = 'READY',
    updated_at = $1
WHERE id = $2
  AND epoch = $3
  AND lifecycle_state = 'DRAINING'
  AND reachability_condition = 'HEALTHY'
`

type ReleaseWorkerAfterCancellationStopParams struct {
	StoppedAt   pgtype.Timestamptz `db:"stopped_at" json:"stopped_at"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
}

func (q *Queries) ReleaseWorkerAfterCancellationStop(ctx context.Context, arg ReleaseWorkerAfterCancellationStopParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseWorkerAfterCancellationStop, arg.StoppedAt, arg.WorkerID, arg.WorkerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCancellationRequestContext = `-- name: SetCancellationRequestContext :one
SELECT
    organization_id::uuid,
    project_id::uuid,
    principal_id::uuid,
    transaction_time::timestamptz
FROM vela_set_cancellation_request_context(
    $1::uuid,
    $2::bytea
)
`

type SetCancellationRequestContextParams struct {
	CredentialID    uuid.UUID `db:"credential_id" json:"credential_id"`
	CredentialProof []byte    `db:"credential_proof" json:"credential_proof"`
}

type SetCancellationRequestContextRow struct {
	OrganizationID  uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID       uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID     uuid.UUID          `db:"principal_id" json:"principal_id"`
	TransactionTime pgtype.Timestamptz `db:"transaction_time" json:"transaction_time"`
}

func (q *Queries) SetCancellationRequestContext(ctx context.Context, arg SetCancellationRequestContextParams) (SetCancellationRequestContextRow, error) {
	row := q.db.QueryRow(ctx, setCancellationRequestContext, arg.CredentialID, arg.CredentialProof)
	var i SetCancellationRequestContextRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.PrincipalID,
		&i.TransactionTime,
	)
	return i, err
}
