// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: failure.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decrementPoolWaitingForFailure = `-- name: DecrementPoolWaitingForFailure :execrows
UPDATE worker_pools
SET queued_count = queued_count - 1,
    retry_wait_count = retry_wait_count - CASE WHEN $1::boolean THEN 1 ELSE 0 END
WHERE id = $2
  AND (
      ($1::boolean AND retry_wait_count > 0 AND queued_count > 0)
      OR (NOT $1::boolean AND queued_count - retry_wait_count > 0)
  )
`

type DecrementPoolWaitingForFailureParams struct {
	FromRetry    bool      `db:"from_retry" json:"from_retry"`
	WorkerPoolID uuid.UUID `db:"worker_pool_id" json:"worker_pool_id"`
}

func (q *Queries) DecrementPoolWaitingForFailure(ctx context.Context, arg DecrementPoolWaitingForFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementPoolWaitingForFailure, arg.FromRetry, arg.WorkerPoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decrementProjectRunningForFailure = `-- name: DecrementProjectRunningForFailure :execrows
UPDATE projects
SET running_count = running_count - 1
WHERE organization_id = $1
  AND id = $2
  AND running_count > 0
`

type DecrementProjectRunningForFailureParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) DecrementProjectRunningForFailure(ctx context.Context, arg DecrementProjectRunningForFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementProjectRunningForFailure, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decrementProjectWaitingForFailure = `-- name: DecrementProjectWaitingForFailure :execrows
UPDATE projects
SET queued_count = queued_count - 1,
    retry_wait_count = retry_wait_count - CASE WHEN $1::boolean THEN 1 ELSE 0 END
WHERE organization_id = $2
  AND id = $3
  AND (
      ($1::boolean AND retry_wait_count > 0 AND queued_count > 0)
      OR (NOT $1::boolean AND queued_count - retry_wait_count > 0)
  )
`

type DecrementProjectWaitingForFailureParams struct {
	FromRetry      bool      `db:"from_retry" json:"from_retry"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) DecrementProjectWaitingForFailure(ctx context.Context, arg DecrementProjectWaitingForFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementProjectWaitingForFailure, arg.FromRetry, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findExpiredExecutionLeaseCandidate = `-- name: FindExpiredExecutionLeaseCandidate :one
SELECT a.job_id, a.id AS attempt_id, a.worker_id
FROM attempt_leases AS l
JOIN attempts AS a ON a.id = l.attempt_id
JOIN jobs AS j ON j.id = a.job_id
WHERE l.phase = 'EXECUTION'
  AND l.owner_kind = 'WORKER'
  AND l.revoked_at IS NULL
  AND a.state IN ('ASSIGNED', 'RUNNING')
  AND j.state IN ('ASSIGNED', 'RUNNING')
  AND j.job_expires_at > clock_timestamp()
  AND l.expires_at
      + $1::bigint * interval '1 second'
      <= clock_timestamp()
ORDER BY l.expires_at, l.id
LIMIT 1
`

type FindExpiredExecutionLeaseCandidateRow struct {
	JobID     uuid.UUID `db:"job_id" json:"job_id"`
	AttemptID uuid.UUID `db:"attempt_id" json:"attempt_id"`
	WorkerID  uuid.UUID `db:"worker_id" json:"worker_id"`
}

func (q *Queries) FindExpiredExecutionLeaseCandidate(ctx context.Context, workerLostGraceSeconds int64) (FindExpiredExecutionLeaseCandidateRow, error) {
	row := q.db.QueryRow(ctx, findExpiredExecutionLeaseCandidate, workerLostGraceSeconds)
	var i FindExpiredExecutionLeaseCandidateRow
	err := row.Scan(&i.JobID, &i.AttemptID, &i.WorkerID)
	return i, err
}

const findExpiredJobFailureCandidate = `-- name: FindExpiredJobFailureCandidate :one
SELECT
    j.id AS job_id,
    coalesce(active_attempt.id, '00000000-0000-0000-0000-000000000000'::uuid) AS attempt_id,
    coalesce(active_attempt.worker_id, '00000000-0000-0000-0000-000000000000'::uuid) AS worker_id
FROM jobs AS j
LEFT JOIN LATERAL (
    SELECT a.id, a.worker_id
    FROM attempts AS a
    WHERE a.job_id = j.id
      AND a.state IN ('ASSIGNED', 'RUNNING')
    LIMIT 1
) AS active_attempt ON true
WHERE j.state IN ('QUEUED', 'RETRY_WAIT', 'ASSIGNED', 'RUNNING')
  AND j.job_expires_at <= clock_timestamp()
ORDER BY j.job_expires_at, j.id
LIMIT 1
`

type FindExpiredJobFailureCandidateRow struct {
	JobID     uuid.UUID `db:"job_id" json:"job_id"`
	AttemptID uuid.UUID `db:"attempt_id" json:"attempt_id"`
	WorkerID  uuid.UUID `db:"worker_id" json:"worker_id"`
}

func (q *Queries) FindExpiredJobFailureCandidate(ctx context.Context) (FindExpiredJobFailureCandidateRow, error) {
	row := q.db.QueryRow(ctx, findExpiredJobFailureCandidate)
	var i FindExpiredJobFailureCandidateRow
	err := row.Scan(&i.JobID, &i.AttemptID, &i.WorkerID)
	return i, err
}

const getExecutionFailureDecision = `-- name: GetExecutionFailureDecision :one
SELECT
    id,
    request_hash,
    disposition,
    failure_class,
    attempt_id,
    job_id,
    attempt_state,
    attempt_compute_seconds,
    total_compute_seconds,
    next_retry_at,
    job_fence,
    job_version,
    decided_at
FROM execution_failure_decisions
WHERE attempt_id = $1
`

type GetExecutionFailureDecisionRow struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	RequestHash           []byte             `db:"request_hash" json:"request_hash"`
	Disposition           RetryDisposition   `db:"disposition" json:"disposition"`
	FailureClass          string             `db:"failure_class" json:"failure_class"`
	AttemptID             uuid.NullUUID      `db:"attempt_id" json:"attempt_id"`
	JobID                 uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptState          *AttemptState      `db:"attempt_state" json:"attempt_state"`
	AttemptComputeSeconds int64              `db:"attempt_compute_seconds" json:"attempt_compute_seconds"`
	TotalComputeSeconds   int64              `db:"total_compute_seconds" json:"total_compute_seconds"`
	NextRetryAt           pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	JobFence              int64              `db:"job_fence" json:"job_fence"`
	JobVersion            int64              `db:"job_version" json:"job_version"`
	DecidedAt             pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

func (q *Queries) GetExecutionFailureDecision(ctx context.Context, attemptID uuid.NullUUID) (GetExecutionFailureDecisionRow, error) {
	row := q.db.QueryRow(ctx, getExecutionFailureDecision, attemptID)
	var i GetExecutionFailureDecisionRow
	err := row.Scan(
		&i.ID,
		&i.RequestHash,
		&i.Disposition,
		&i.FailureClass,
		&i.AttemptID,
		&i.JobID,
		&i.AttemptState,
		&i.AttemptComputeSeconds,
		&i.TotalComputeSeconds,
		&i.NextRetryAt,
		&i.JobFence,
		&i.JobVersion,
		&i.DecidedAt,
	)
	return i, err
}

const incrementPoolRetryWait = `-- name: IncrementPoolRetryWait :execrows
UPDATE worker_pools
SET queued_count = queued_count + 1,
    retry_wait_count = retry_wait_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPoolRetryWait(ctx context.Context, workerPoolID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementPoolRetryWait, workerPoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertExecutionFailureDecision = `-- name: InsertExecutionFailureDecision :exec
INSERT INTO execution_failure_decisions (
    id,
    organization_id,
    project_id,
    job_id,
    attempt_id,
    worker_id,
    worker_epoch,
    attempt_fence,
    source,
    disposition,
    attempt_state,
    failure_class,
    failure_fingerprint,
    request_hash,
    error_summary,
    backend_stage,
    gpu_uuids,
    inference_backend_revision,
    retry_recommended,
    worker_reusable,
    attempt_compute_seconds,
    total_compute_seconds,
    next_retry_at,
    job_fence,
    job_version,
    decided_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26
)
`

type InsertExecutionFailureDecisionParams struct {
	ID                       uuid.UUID              `db:"id" json:"id"`
	OrganizationID           uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID                uuid.UUID              `db:"project_id" json:"project_id"`
	JobID                    uuid.UUID              `db:"job_id" json:"job_id"`
	AttemptID                uuid.NullUUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID                 uuid.NullUUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch              *int64                 `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence             *int64                 `db:"attempt_fence" json:"attempt_fence"`
	Source                   ExecutionFailureSource `db:"source" json:"source"`
	Disposition              RetryDisposition       `db:"disposition" json:"disposition"`
	AttemptState             *AttemptState          `db:"attempt_state" json:"attempt_state"`
	FailureClass             string                 `db:"failure_class" json:"failure_class"`
	FailureFingerprint       string                 `db:"failure_fingerprint" json:"failure_fingerprint"`
	RequestHash              []byte                 `db:"request_hash" json:"request_hash"`
	ErrorSummary             string                 `db:"error_summary" json:"error_summary"`
	BackendStage             string                 `db:"backend_stage" json:"backend_stage"`
	GpuUuids                 []byte                 `db:"gpu_uuids" json:"gpu_uuids"`
	InferenceBackendRevision string                 `db:"inference_backend_revision" json:"inference_backend_revision"`
	RetryRecommended         bool                   `db:"retry_recommended" json:"retry_recommended"`
	WorkerReusable           bool                   `db:"worker_reusable" json:"worker_reusable"`
	AttemptComputeSeconds    int64                  `db:"attempt_compute_seconds" json:"attempt_compute_seconds"`
	TotalComputeSeconds      int64                  `db:"total_compute_seconds" json:"total_compute_seconds"`
	NextRetryAt              pgtype.Timestamptz     `db:"next_retry_at" json:"next_retry_at"`
	JobFence                 int64                  `db:"job_fence" json:"job_fence"`
	JobVersion               int64                  `db:"job_version" json:"job_version"`
	DecidedAt                pgtype.Timestamptz     `db:"decided_at" json:"decided_at"`
}

func (q *Queries) InsertExecutionFailureDecision(ctx context.Context, arg InsertExecutionFailureDecisionParams) error {
	_, err := q.db.Exec(ctx, insertExecutionFailureDecision,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.AttemptFence,
		arg.Source,
		arg.Disposition,
		arg.AttemptState,
		arg.FailureClass,
		arg.FailureFingerprint,
		arg.RequestHash,
		arg.ErrorSummary,
		arg.BackendStage,
		arg.GpuUuids,
		arg.InferenceBackendRevision,
		arg.RetryRecommended,
		arg.WorkerReusable,
		arg.AttemptComputeSeconds,
		arg.TotalComputeSeconds,
		arg.NextRetryAt,
		arg.JobFence,
		arg.JobVersion,
		arg.DecidedAt,
	)
	return err
}

const insertJobFailedOutboxEvent = `-- name: InsertJobFailedOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    organization_id,
    project_id,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_type,
    schema_version,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    'Job',
    $4,
    $5,
    'job.failed',
    1,
    $6,
    $7
)
`

type InsertJobFailedOutboxEventParams struct {
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	JobVersion     int64              `db:"job_version" json:"job_version"`
	Payload        []byte             `db:"payload" json:"payload"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertJobFailedOutboxEvent(ctx context.Context, arg InsertJobFailedOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertJobFailedOutboxEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.JobVersion,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertRetryWaitOutboxEvent = `-- name: InsertRetryWaitOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    organization_id,
    project_id,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_type,
    schema_version,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    'Job',
    $4,
    $5,
    'job.retry_wait',
    1,
    $6,
    $7
)
`

type InsertRetryWaitOutboxEventParams struct {
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	JobVersion     int64              `db:"job_version" json:"job_version"`
	Payload        []byte             `db:"payload" json:"payload"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertRetryWaitOutboxEvent(ctx context.Context, arg InsertRetryWaitOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertRetryWaitOutboxEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.JobVersion,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const lockFailureAuthority = `-- name: LockFailureAuthority :one
SELECT
    l.id AS lease_id,
    l.token_digest,
    l.expires_at AS lease_expires_at,
    l.revoked_at AS lease_revoked_at,
	 l.phase AS lease_phase,
	 l.owner_kind AS lease_owner_kind,
	 l.owner_id AS lease_owner_id,
    a.id AS attempt_id,
    a.job_id,
    a.attempt_number,
    a.state AS attempt_state,
    a.started_at AS attempt_started_at,
    a.worker_id,
    a.worker_epoch,
    a.fence AS attempt_fence,
    j.organization_id,
    j.project_id,
    j.worker_pool_id,
    j.state AS job_state,
    j.version AS job_version,
    j.current_fence,
    j.execution_max_attempts,
    j.execution_max_total_compute_seconds,
    j.execution_retry_backoff_policy,
    j.execution_retryable_failure_classes,
    j.job_expires_at,
    rts.attempts_started,
    rts.compute_seconds_consumed,
    ere.excluded_workers,
    ere.failure_fingerprints,
    rts.version AS retry_runtime_version
FROM attempt_leases AS l
JOIN attempts AS a ON a.id = l.attempt_id
JOIN jobs AS j ON j.id = a.job_id
JOIN retry_runtime_states AS rts ON rts.job_id = j.id
JOIN execution_retry_evidence AS ere ON ere.job_id = j.id
WHERE l.attempt_id = $1
LIMIT 1
FOR UPDATE OF l, a, j, rts, ere
`

type LockFailureAuthorityRow struct {
	LeaseID                          uuid.UUID          `db:"lease_id" json:"lease_id"`
	TokenDigest                      []byte             `db:"token_digest" json:"token_digest"`
	LeaseExpiresAt                   pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LeaseRevokedAt                   pgtype.Timestamptz `db:"lease_revoked_at" json:"lease_revoked_at"`
	LeasePhase                       LeasePhase         `db:"lease_phase" json:"lease_phase"`
	LeaseOwnerKind                   LeaseOwnerKind     `db:"lease_owner_kind" json:"lease_owner_kind"`
	LeaseOwnerID                     string             `db:"lease_owner_id" json:"lease_owner_id"`
	AttemptID                        uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	JobID                            uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptNumber                    int32              `db:"attempt_number" json:"attempt_number"`
	AttemptState                     AttemptState       `db:"attempt_state" json:"attempt_state"`
	AttemptStartedAt                 pgtype.Timestamptz `db:"attempt_started_at" json:"attempt_started_at"`
	WorkerID                         uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch                      int64              `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence                     int64              `db:"attempt_fence" json:"attempt_fence"`
	OrganizationID                   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                        uuid.UUID          `db:"project_id" json:"project_id"`
	WorkerPoolID                     uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	JobState                         JobState           `db:"job_state" json:"job_state"`
	JobVersion                       int64              `db:"job_version" json:"job_version"`
	CurrentFence                     int64              `db:"current_fence" json:"current_fence"`
	ExecutionMaxAttempts             int32              `db:"execution_max_attempts" json:"execution_max_attempts"`
	ExecutionMaxTotalComputeSeconds  int64              `db:"execution_max_total_compute_seconds" json:"execution_max_total_compute_seconds"`
	ExecutionRetryBackoffPolicy      []byte             `db:"execution_retry_backoff_policy" json:"execution_retry_backoff_policy"`
	ExecutionRetryableFailureClasses []string           `db:"execution_retryable_failure_classes" json:"execution_retryable_failure_classes"`
	JobExpiresAt                     pgtype.Timestamptz `db:"job_expires_at" json:"job_expires_at"`
	AttemptsStarted                  int32              `db:"attempts_started" json:"attempts_started"`
	ComputeSecondsConsumed           int64              `db:"compute_seconds_consumed" json:"compute_seconds_consumed"`
	ExcludedWorkers                  []byte             `db:"excluded_workers" json:"excluded_workers"`
	FailureFingerprints              []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	RetryRuntimeVersion              int64              `db:"retry_runtime_version" json:"retry_runtime_version"`
}

func (q *Queries) LockFailureAuthority(ctx context.Context, attemptID uuid.UUID) (LockFailureAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockFailureAuthority, attemptID)
	var i LockFailureAuthorityRow
	err := row.Scan(
		&i.LeaseID,
		&i.TokenDigest,
		&i.LeaseExpiresAt,
		&i.LeaseRevokedAt,
		&i.LeasePhase,
		&i.LeaseOwnerKind,
		&i.LeaseOwnerID,
		&i.AttemptID,
		&i.JobID,
		&i.AttemptNumber,
		&i.AttemptState,
		&i.AttemptStartedAt,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.AttemptFence,
		&i.OrganizationID,
		&i.ProjectID,
		&i.WorkerPoolID,
		&i.JobState,
		&i.JobVersion,
		&i.CurrentFence,
		&i.ExecutionMaxAttempts,
		&i.ExecutionMaxTotalComputeSeconds,
		&i.ExecutionRetryBackoffPolicy,
		&i.ExecutionRetryableFailureClasses,
		&i.JobExpiresAt,
		&i.AttemptsStarted,
		&i.ComputeSecondsConsumed,
		&i.ExcludedWorkers,
		&i.FailureFingerprints,
		&i.RetryRuntimeVersion,
	)
	return i, err
}

const lockFailureCreditReservation = `-- name: LockFailureCreditReservation :one
SELECT id, organization_id, project_id, amount_minor, currency, state
FROM credit_reservations
WHERE job_id = $1
FOR UPDATE
`

type LockFailureCreditReservationRow struct {
	ID             uuid.UUID              `db:"id" json:"id"`
	OrganizationID uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID              `db:"project_id" json:"project_id"`
	AmountMinor    int64                  `db:"amount_minor" json:"amount_minor"`
	Currency       string                 `db:"currency" json:"currency"`
	State          CreditReservationState `db:"state" json:"state"`
}

func (q *Queries) LockFailureCreditReservation(ctx context.Context, jobID uuid.UUID) (LockFailureCreditReservationRow, error) {
	row := q.db.QueryRow(ctx, lockFailureCreditReservation, jobID)
	var i LockFailureCreditReservationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.AmountMinor,
		&i.Currency,
		&i.State,
	)
	return i, err
}

const lockFailureOrganizationCredit = `-- name: LockFailureOrganizationCredit :one
SELECT currency, reserved_minor
FROM organization_credit_accounts
WHERE organization_id = $1
FOR UPDATE
`

type LockFailureOrganizationCreditRow struct {
	Currency      string `db:"currency" json:"currency"`
	ReservedMinor int64  `db:"reserved_minor" json:"reserved_minor"`
}

func (q *Queries) LockFailureOrganizationCredit(ctx context.Context, organizationID uuid.UUID) (LockFailureOrganizationCreditRow, error) {
	row := q.db.QueryRow(ctx, lockFailureOrganizationCredit, organizationID)
	var i LockFailureOrganizationCreditRow
	err := row.Scan(&i.Currency, &i.ReservedMinor)
	return i, err
}

const lockFailurePoolCounters = `-- name: LockFailurePoolCounters :one
SELECT queued_count, retry_wait_count
FROM worker_pools
WHERE id = $1
FOR UPDATE
`

type LockFailurePoolCountersRow struct {
	QueuedCount    int32 `db:"queued_count" json:"queued_count"`
	RetryWaitCount int32 `db:"retry_wait_count" json:"retry_wait_count"`
}

func (q *Queries) LockFailurePoolCounters(ctx context.Context, workerPoolID uuid.UUID) (LockFailurePoolCountersRow, error) {
	row := q.db.QueryRow(ctx, lockFailurePoolCounters, workerPoolID)
	var i LockFailurePoolCountersRow
	err := row.Scan(&i.QueuedCount, &i.RetryWaitCount)
	return i, err
}

const lockFailureProjectCounters = `-- name: LockFailureProjectCounters :one
SELECT queued_count, retry_wait_count, running_count, running_limit
FROM projects
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockFailureProjectCountersParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

type LockFailureProjectCountersRow struct {
	QueuedCount    int32 `db:"queued_count" json:"queued_count"`
	RetryWaitCount int32 `db:"retry_wait_count" json:"retry_wait_count"`
	RunningCount   int32 `db:"running_count" json:"running_count"`
	RunningLimit   int32 `db:"running_limit" json:"running_limit"`
}

func (q *Queries) LockFailureProjectCounters(ctx context.Context, arg LockFailureProjectCountersParams) (LockFailureProjectCountersRow, error) {
	row := q.db.QueryRow(ctx, lockFailureProjectCounters, arg.OrganizationID, arg.ProjectID)
	var i LockFailureProjectCountersRow
	err := row.Scan(
		&i.QueuedCount,
		&i.RetryWaitCount,
		&i.RunningCount,
		&i.RunningLimit,
	)
	return i, err
}

const lockJobExpiryWithoutAttempt = `-- name: LockJobExpiryWithoutAttempt :one
SELECT
    j.organization_id,
    j.project_id,
    j.worker_pool_id,
    j.state AS job_state,
    j.version AS job_version,
    j.current_fence,
    j.job_expires_at,
    rts.compute_seconds_consumed,
    ere.failure_fingerprints,
    rts.version AS retry_runtime_version
FROM jobs AS j
JOIN retry_runtime_states AS rts ON rts.job_id = j.id
JOIN execution_retry_evidence AS ere ON ere.job_id = j.id
WHERE j.id = $1
  AND j.state IN ('QUEUED', 'RETRY_WAIT')
  AND j.job_expires_at <= clock_timestamp()
  AND NOT EXISTS (
      SELECT 1
      FROM attempts AS a
      WHERE a.job_id = j.id
        AND a.state IN ('ASSIGNED', 'RUNNING', 'FINALIZING')
  )
FOR UPDATE OF j, rts, ere
`

type LockJobExpiryWithoutAttemptRow struct {
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID              uuid.UUID          `db:"project_id" json:"project_id"`
	WorkerPoolID           uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	JobState               JobState           `db:"job_state" json:"job_state"`
	JobVersion             int64              `db:"job_version" json:"job_version"`
	CurrentFence           int64              `db:"current_fence" json:"current_fence"`
	JobExpiresAt           pgtype.Timestamptz `db:"job_expires_at" json:"job_expires_at"`
	ComputeSecondsConsumed int64              `db:"compute_seconds_consumed" json:"compute_seconds_consumed"`
	FailureFingerprints    []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	RetryRuntimeVersion    int64              `db:"retry_runtime_version" json:"retry_runtime_version"`
}

func (q *Queries) LockJobExpiryWithoutAttempt(ctx context.Context, jobID uuid.UUID) (LockJobExpiryWithoutAttemptRow, error) {
	row := q.db.QueryRow(ctx, lockJobExpiryWithoutAttempt, jobID)
	var i LockJobExpiryWithoutAttemptRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.WorkerPoolID,
		&i.JobState,
		&i.JobVersion,
		&i.CurrentFence,
		&i.JobExpiresAt,
		&i.ComputeSecondsConsumed,
		&i.FailureFingerprints,
		&i.RetryRuntimeVersion,
	)
	return i, err
}

const markAttemptFailed = `-- name: MarkAttemptFailed :execrows
UPDATE attempts
SET state = 'FAILED',
    ended_at = $1,
    updated_at = $1
WHERE id = $2
  AND worker_id = $3
  AND worker_epoch = $4
  AND fence = $5
  AND state IN ('ASSIGNED', 'RUNNING')
  AND ended_at IS NULL
`

type MarkAttemptFailedParams struct {
	DecidedAt   pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	AttemptID   uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence       int64              `db:"fence" json:"fence"`
}

func (q *Queries) MarkAttemptFailed(ctx context.Context, arg MarkAttemptFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAttemptFailed,
		arg.DecidedAt,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAttemptLost = `-- name: MarkAttemptLost :execrows
UPDATE attempts
SET state = 'LOST',
    ended_at = $1,
    updated_at = $1
WHERE id = $2
  AND worker_id = $3
  AND worker_epoch = $4
  AND fence = $5
  AND state IN ('ASSIGNED', 'RUNNING')
  AND ended_at IS NULL
`

type MarkAttemptLostParams struct {
	DecidedAt   pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	AttemptID   uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence       int64              `db:"fence" json:"fence"`
}

func (q *Queries) MarkAttemptLost(ctx context.Context, arg MarkAttemptLostParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAttemptLost,
		arg.DecidedAt,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobFailedFromActive = `-- name: MarkJobFailedFromActive :one
UPDATE jobs
SET state = 'FAILED',
    current_fence = $1,
    version = version + 1,
    updated_at = $2
WHERE id = $3
  AND version = $4
  AND current_fence = $5
  AND state IN ('ASSIGNED', 'RUNNING')
RETURNING version
`

type MarkJobFailedFromActiveParams struct {
	JobFence        int64              `db:"job_fence" json:"job_fence"`
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion int64              `db:"expected_version" json:"expected_version"`
	PreviousFence   int64              `db:"previous_fence" json:"previous_fence"`
}

func (q *Queries) MarkJobFailedFromActive(ctx context.Context, arg MarkJobFailedFromActiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, markJobFailedFromActive,
		arg.JobFence,
		arg.DecidedAt,
		arg.JobID,
		arg.ExpectedVersion,
		arg.PreviousFence,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const markJobFailedWithoutAttempt = `-- name: MarkJobFailedWithoutAttempt :one
UPDATE jobs
SET state = 'FAILED',
    current_fence = $1,
    version = version + 1,
    updated_at = $2
WHERE id = $3
  AND version = $4
  AND current_fence = $5
  AND state = $6
  AND state IN ('QUEUED', 'RETRY_WAIT')
RETURNING version
`

type MarkJobFailedWithoutAttemptParams struct {
	JobFence        int64              `db:"job_fence" json:"job_fence"`
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion int64              `db:"expected_version" json:"expected_version"`
	PreviousFence   int64              `db:"previous_fence" json:"previous_fence"`
	ExpectedState   JobState           `db:"expected_state" json:"expected_state"`
}

func (q *Queries) MarkJobFailedWithoutAttempt(ctx context.Context, arg MarkJobFailedWithoutAttemptParams) (int64, error) {
	row := q.db.QueryRow(ctx, markJobFailedWithoutAttempt,
		arg.JobFence,
		arg.DecidedAt,
		arg.JobID,
		arg.ExpectedVersion,
		arg.PreviousFence,
		arg.ExpectedState,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const markJobRetryWait = `-- name: MarkJobRetryWait :one
UPDATE jobs
SET state = 'RETRY_WAIT',
    current_fence = $1,
    version = version + 1,
    updated_at = $2
WHERE id = $3
  AND version = $4
  AND current_fence = $5
  AND state IN ('ASSIGNED', 'RUNNING')
RETURNING version
`

type MarkJobRetryWaitParams struct {
	JobFence        int64              `db:"job_fence" json:"job_fence"`
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion int64              `db:"expected_version" json:"expected_version"`
	PreviousFence   int64              `db:"previous_fence" json:"previous_fence"`
}

func (q *Queries) MarkJobRetryWait(ctx context.Context, arg MarkJobRetryWaitParams) (int64, error) {
	row := q.db.QueryRow(ctx, markJobRetryWait,
		arg.JobFence,
		arg.DecidedAt,
		arg.JobID,
		arg.ExpectedVersion,
		arg.PreviousFence,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const markWorkerDrainingAfterFailure = `-- name: MarkWorkerDrainingAfterFailure :execrows
UPDATE workers
SET lifecycle_state = CASE
        WHEN lifecycle_state IN ('READY', 'BUSY') THEN 'DRAINING'::worker_lifecycle_state
        ELSE lifecycle_state
    END,
    updated_at = $1
WHERE id = $2
  AND epoch = $3
`

type MarkWorkerDrainingAfterFailureParams struct {
	DecidedAt   pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
}

func (q *Queries) MarkWorkerDrainingAfterFailure(ctx context.Context, arg MarkWorkerDrainingAfterFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkerDrainingAfterFailure, arg.DecidedAt, arg.WorkerID, arg.WorkerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWorkerLostAfterFailure = `-- name: MarkWorkerLostAfterFailure :execrows
UPDATE workers
SET lifecycle_state = CASE
        WHEN lifecycle_state IN ('READY', 'BUSY') THEN 'DRAINING'::worker_lifecycle_state
        ELSE lifecycle_state
    END,
    reachability_condition = 'OFFLINE',
    updated_at = $1
WHERE id = $2
  AND epoch = $3
`

type MarkWorkerLostAfterFailureParams struct {
	DecidedAt   pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
}

func (q *Queries) MarkWorkerLostAfterFailure(ctx context.Context, arg MarkWorkerLostAfterFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkerLostAfterFailure, arg.DecidedAt, arg.WorkerID, arg.WorkerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWorkerReusableAfterFailure = `-- name: MarkWorkerReusableAfterFailure :execrows
UPDATE workers
SET lifecycle_state = CASE
        WHEN lifecycle_state = 'BUSY' THEN 'READY'::worker_lifecycle_state
        ELSE lifecycle_state
    END,
    updated_at = $1
WHERE id = $2
  AND epoch = $3
  AND reachability_condition = 'HEALTHY'
`

type MarkWorkerReusableAfterFailureParams struct {
	DecidedAt   pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
}

func (q *Queries) MarkWorkerReusableAfterFailure(ctx context.Context, arg MarkWorkerReusableAfterFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkerReusableAfterFailure, arg.DecidedAt, arg.WorkerID, arg.WorkerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveProjectRunningToRetryWait = `-- name: MoveProjectRunningToRetryWait :execrows
UPDATE projects
SET running_count = running_count - 1,
    queued_count = queued_count + 1,
    retry_wait_count = retry_wait_count + 1
WHERE organization_id = $1
  AND id = $2
  AND running_count > 0
`

type MoveProjectRunningToRetryWaitParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) MoveProjectRunningToRetryWait(ctx context.Context, arg MoveProjectRunningToRetryWaitParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveProjectRunningToRetryWait, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseFailureCreditReservation = `-- name: ReleaseFailureCreditReservation :execrows
UPDATE credit_reservations
SET state = 'RELEASED',
    updated_at = $1
WHERE id = $2
  AND job_id = $3
  AND state = 'RESERVED'
`

type ReleaseFailureCreditReservationParams struct {
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	CreditReservationID uuid.UUID          `db:"credit_reservation_id" json:"credit_reservation_id"`
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
}

func (q *Queries) ReleaseFailureCreditReservation(ctx context.Context, arg ReleaseFailureCreditReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseFailureCreditReservation, arg.DecidedAt, arg.CreditReservationID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseOrganizationCreditForFailure = `-- name: ReleaseOrganizationCreditForFailure :execrows
UPDATE organization_credit_accounts
SET reserved_minor = reserved_minor - $1,
    version = version + 1,
    updated_at = $2
WHERE organization_id = $3
  AND currency = $4
  AND reserved_minor >= $1
`

type ReleaseOrganizationCreditForFailureParams struct {
	AmountMinor    int64              `db:"amount_minor" json:"amount_minor"`
	DecidedAt      pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Currency       string             `db:"currency" json:"currency"`
}

func (q *Queries) ReleaseOrganizationCreditForFailure(ctx context.Context, arg ReleaseOrganizationCreditForFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOrganizationCreditForFailure,
		arg.AmountMinor,
		arg.DecidedAt,
		arg.OrganizationID,
		arg.Currency,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeExecutionLeaseForFailure = `-- name: RevokeExecutionLeaseForFailure :execrows
UPDATE attempt_leases
SET revoked_at = $1,
    updated_at = $1
WHERE id = $2
  AND attempt_id = $3
  AND worker_id = $4
  AND worker_epoch = $5
  AND fence = $6
  AND phase = 'EXECUTION'
  AND owner_kind = 'WORKER'
  AND revoked_at IS NULL
`

type RevokeExecutionLeaseForFailureParams struct {
	DecidedAt   pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	LeaseID     uuid.UUID          `db:"lease_id" json:"lease_id"`
	AttemptID   uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence       int64              `db:"fence" json:"fence"`
}

func (q *Queries) RevokeExecutionLeaseForFailure(ctx context.Context, arg RevokeExecutionLeaseForFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeExecutionLeaseForFailure,
		arg.DecidedAt,
		arg.LeaseID,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExecutionRetryEvidence = `-- name: UpdateExecutionRetryEvidence :execrows
UPDATE execution_retry_evidence
SET excluded_workers = $1,
    failure_fingerprints = $2,
    updated_at = $3
WHERE job_id = $4
`

type UpdateExecutionRetryEvidenceParams struct {
	ExcludedWorkers     []byte             `db:"excluded_workers" json:"excluded_workers"`
	FailureFingerprints []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
}

func (q *Queries) UpdateExecutionRetryEvidence(ctx context.Context, arg UpdateExecutionRetryEvidenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExecutionRetryEvidence,
		arg.ExcludedWorkers,
		arg.FailureFingerprints,
		arg.DecidedAt,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExecutionRetryEvidenceForJobExpiry = `-- name: UpdateExecutionRetryEvidenceForJobExpiry :execrows
UPDATE execution_retry_evidence
SET failure_fingerprints = $1,
    updated_at = $2
WHERE job_id = $3
`

type UpdateExecutionRetryEvidenceForJobExpiryParams struct {
	FailureFingerprints []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
}

func (q *Queries) UpdateExecutionRetryEvidenceForJobExpiry(ctx context.Context, arg UpdateExecutionRetryEvidenceForJobExpiryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExecutionRetryEvidenceForJobExpiry, arg.FailureFingerprints, arg.DecidedAt, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRetryRuntimeForFailure = `-- name: UpdateRetryRuntimeForFailure :execrows
UPDATE retry_runtime_states
SET compute_seconds_consumed = $1,
    next_retry_at = $2,
    last_failure_class = $3,
    version = version + 1,
    updated_at = $4
WHERE job_id = $5
  AND version = $6
  AND compute_seconds_consumed = $7
`

type UpdateRetryRuntimeForFailureParams struct {
	TotalComputeSeconds    int64              `db:"total_compute_seconds" json:"total_compute_seconds"`
	NextRetryAt            pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	FailureClass           *string            `db:"failure_class" json:"failure_class"`
	DecidedAt              pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID                  uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion        int64              `db:"expected_version" json:"expected_version"`
	PreviousComputeSeconds int64              `db:"previous_compute_seconds" json:"previous_compute_seconds"`
}

func (q *Queries) UpdateRetryRuntimeForFailure(ctx context.Context, arg UpdateRetryRuntimeForFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRetryRuntimeForFailure,
		arg.TotalComputeSeconds,
		arg.NextRetryAt,
		arg.FailureClass,
		arg.DecidedAt,
		arg.JobID,
		arg.ExpectedVersion,
		arg.PreviousComputeSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRetryRuntimeForJobExpiry = `-- name: UpdateRetryRuntimeForJobExpiry :execrows
UPDATE retry_runtime_states
SET next_retry_at = NULL,
    last_failure_class = 'JOB_EXPIRED',
    version = version + 1,
    updated_at = $1
WHERE job_id = $2
  AND version = $3
`

type UpdateRetryRuntimeForJobExpiryParams struct {
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion int64              `db:"expected_version" json:"expected_version"`
}

func (q *Queries) UpdateRetryRuntimeForJobExpiry(ctx context.Context, arg UpdateRetryRuntimeForJobExpiryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRetryRuntimeForJobExpiry, arg.DecidedAt, arg.JobID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
