// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finalization.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeStageGraphAttemptForVisibleCompletion = `-- name: CompleteStageGraphAttemptForVisibleCompletion :one
SELECT vela_complete_stage_graph_visible_completion_attempt(
    $1, $2, $3
)
`

type CompleteStageGraphAttemptForVisibleCompletionParams struct {
	AttemptID   uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	Fence       int64              `db:"fence" json:"fence"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) CompleteStageGraphAttemptForVisibleCompletion(ctx context.Context, arg CompleteStageGraphAttemptForVisibleCompletionParams) (bool, error) {
	row := q.db.QueryRow(ctx, completeStageGraphAttemptForVisibleCompletion, arg.AttemptID, arg.Fence, arg.CompletedAt)
	var vela_complete_stage_graph_visible_completion_attempt bool
	err := row.Scan(&vela_complete_stage_graph_visible_completion_attempt)
	return vela_complete_stage_graph_visible_completion_attempt, err
}

const completeStageGraphFinalizationClaim = `-- name: CompleteStageGraphFinalizationClaim :execrows
UPDATE stage_graph_finalization_claims
SET state = 'COMPLETED',
    completed_at = $1,
    updated_at = $1
WHERE id = $2
  AND attempt_id = $3
  AND attempt_fence = $4
  AND owner_id = $5
  AND state = 'ACTIVE'
`

type CompleteStageGraphFinalizationClaimParams struct {
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ClaimID      uuid.UUID          `db:"claim_id" json:"claim_id"`
	AttemptID    uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence int64              `db:"attempt_fence" json:"attempt_fence"`
	OwnerID      string             `db:"owner_id" json:"owner_id"`
}

func (q *Queries) CompleteStageGraphFinalizationClaim(ctx context.Context, arg CompleteStageGraphFinalizationClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeStageGraphFinalizationClaim,
		arg.CompletedAt,
		arg.ClaimID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeVisibleCompletionCreditReservation = `-- name: ConsumeVisibleCompletionCreditReservation :execrows
UPDATE credit_reservations
SET state = 'CONSUMED',
    updated_at = $1
WHERE id = $2
  AND job_id = $3
  AND state = 'RESERVED'
`

type ConsumeVisibleCompletionCreditReservationParams struct {
	CompletedAt         pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreditReservationID uuid.UUID          `db:"credit_reservation_id" json:"credit_reservation_id"`
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
}

func (q *Queries) ConsumeVisibleCompletionCreditReservation(ctx context.Context, arg ConsumeVisibleCompletionCreditReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVisibleCompletionCreditReservation, arg.CompletedAt, arg.CreditReservationID, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decrementProjectRunningForVisibleCompletion = `-- name: DecrementProjectRunningForVisibleCompletion :execrows
UPDATE projects
SET running_count = running_count - 1
WHERE organization_id = $1
  AND id = $2
  AND running_count > 0
`

type DecrementProjectRunningForVisibleCompletionParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) DecrementProjectRunningForVisibleCompletion(ctx context.Context, arg DecrementProjectRunningForVisibleCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementProjectRunningForVisibleCompletion, arg.OrganizationID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStageGraphFinalizationClaims = `-- name: ExpireStageGraphFinalizationClaims :exec
UPDATE stage_graph_finalization_claims
SET state = 'EXPIRED',
    expired_at = $1,
    updated_at = $1
WHERE state = 'ACTIVE'
  AND expires_at <= $1
`

func (q *Queries) ExpireStageGraphFinalizationClaims(ctx context.Context, expiredAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireStageGraphFinalizationClaims, expiredAt)
	return err
}

const findActiveStageGraphFinalizationClaim = `-- name: FindActiveStageGraphFinalizationClaim :one
SELECT
    claim.id AS claim_id,
    claim.organization_id,
    claim.project_id,
    claim.job_id,
    claim.attempt_id,
    claim.attempt_fence,
    claim.final_stage_run_id,
    claim.final_stage_artifact_id,
    claim.exact_object_version,
    claim.owner_id,
    claim.token_digest,
    claim.signing_key_id,
    claim.output_set_digest,
    claim.issued_at,
    claim.expires_at,
    attempt.finalization_started_at,
    attempt.finalization_deadline_at,
    job.version AS job_version,
    artifact.object_key,
    artifact.content_type,
    artifact.sha256,
    artifact.size_bytes,
    artifact.stage_interface_revision_id,
    artifact.expires_at AS artifact_expires_at
FROM stage_graph_finalization_claims AS claim
JOIN attempts AS attempt ON attempt.id = claim.attempt_id
JOIN jobs AS job ON job.id = claim.job_id
JOIN stage_artifacts AS artifact ON artifact.id = claim.final_stage_artifact_id
WHERE claim.owner_id = $1
  AND claim.state = 'ACTIVE'
  AND claim.expires_at > $2
  AND attempt.state = 'FINALIZING'
  AND attempt.graph_state = 'FINALIZING'
  AND attempt.fence = claim.attempt_fence
  AND attempt.finalization_deadline_at > $2
  AND job.state = 'FINALIZING'
  AND job.current_fence = claim.attempt_fence
  AND job.job_expires_at > $2
  AND artifact.state = 'COMMITTED'
  AND artifact.object_version = claim.exact_object_version
ORDER BY claim.issued_at, claim.id
LIMIT 1
FOR UPDATE OF claim, attempt, job
`

type FindActiveStageGraphFinalizationClaimParams struct {
	OwnerID    string             `db:"owner_id" json:"owner_id"`
	ObservedAt pgtype.Timestamptz `db:"observed_at" json:"observed_at"`
}

type FindActiveStageGraphFinalizationClaimRow struct {
	ClaimID                  uuid.UUID          `db:"claim_id" json:"claim_id"`
	OrganizationID           uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                    uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID                uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence             int64              `db:"attempt_fence" json:"attempt_fence"`
	FinalStageRunID          uuid.UUID          `db:"final_stage_run_id" json:"final_stage_run_id"`
	FinalStageArtifactID     uuid.UUID          `db:"final_stage_artifact_id" json:"final_stage_artifact_id"`
	ExactObjectVersion       string             `db:"exact_object_version" json:"exact_object_version"`
	OwnerID                  string             `db:"owner_id" json:"owner_id"`
	TokenDigest              []byte             `db:"token_digest" json:"token_digest"`
	SigningKeyID             string             `db:"signing_key_id" json:"signing_key_id"`
	OutputSetDigest          []byte             `db:"output_set_digest" json:"output_set_digest"`
	IssuedAt                 pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	FinalizationStartedAt    pgtype.Timestamptz `db:"finalization_started_at" json:"finalization_started_at"`
	FinalizationDeadlineAt   pgtype.Timestamptz `db:"finalization_deadline_at" json:"finalization_deadline_at"`
	JobVersion               int64              `db:"job_version" json:"job_version"`
	ObjectKey                string             `db:"object_key" json:"object_key"`
	ContentType              string             `db:"content_type" json:"content_type"`
	Sha256                   []byte             `db:"sha256" json:"sha256"`
	SizeBytes                int64              `db:"size_bytes" json:"size_bytes"`
	StageInterfaceRevisionID uuid.UUID          `db:"stage_interface_revision_id" json:"stage_interface_revision_id"`
	ArtifactExpiresAt        pgtype.Timestamptz `db:"artifact_expires_at" json:"artifact_expires_at"`
}

func (q *Queries) FindActiveStageGraphFinalizationClaim(ctx context.Context, arg FindActiveStageGraphFinalizationClaimParams) (FindActiveStageGraphFinalizationClaimRow, error) {
	row := q.db.QueryRow(ctx, findActiveStageGraphFinalizationClaim, arg.OwnerID, arg.ObservedAt)
	var i FindActiveStageGraphFinalizationClaimRow
	err := row.Scan(
		&i.ClaimID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.JobID,
		&i.AttemptID,
		&i.AttemptFence,
		&i.FinalStageRunID,
		&i.FinalStageArtifactID,
		&i.ExactObjectVersion,
		&i.OwnerID,
		&i.TokenDigest,
		&i.SigningKeyID,
		&i.OutputSetDigest,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.FinalizationStartedAt,
		&i.FinalizationDeadlineAt,
		&i.JobVersion,
		&i.ObjectKey,
		&i.ContentType,
		&i.Sha256,
		&i.SizeBytes,
		&i.StageInterfaceRevisionID,
		&i.ArtifactExpiresAt,
	)
	return i, err
}

const getPostgresTime = `-- name: GetPostgresTime :one
SELECT transaction_timestamp()::timestamptz AS transaction_time
`

func (q *Queries) GetPostgresTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPostgresTime)
	var transaction_time pgtype.Timestamptz
	err := row.Scan(&transaction_time)
	return transaction_time, err
}

const insertArtifactAccessGrant = `-- name: InsertArtifactAccessGrant :exec
INSERT INTO artifact_access_grants (
    id,
    organization_id,
    project_id,
    job_id,
    artifact_set_id,
    eligible_at,
    retention_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type InsertArtifactAccessGrantParams struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	OrganizationID     uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID          uuid.UUID          `db:"project_id" json:"project_id"`
	JobID              uuid.UUID          `db:"job_id" json:"job_id"`
	ArtifactSetID      uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	EligibleAt         pgtype.Timestamptz `db:"eligible_at" json:"eligible_at"`
	RetentionExpiresAt pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
}

func (q *Queries) InsertArtifactAccessGrant(ctx context.Context, arg InsertArtifactAccessGrantParams) error {
	_, err := q.db.Exec(ctx, insertArtifactAccessGrant,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.ArtifactSetID,
		arg.EligibleAt,
		arg.RetentionExpiresAt,
	)
	return err
}

const insertArtifactSet = `-- name: InsertArtifactSet :exec
INSERT INTO artifact_sets (
    id,
    organization_id,
    project_id,
    job_id,
    attempt_id,
    attempt_fence,
    manifest_sha256,
    retention_policy_revision,
    retention_expires_at,
    committed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
`

type InsertArtifactSetParams struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	OrganizationID          uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID               uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence            int64              `db:"attempt_fence" json:"attempt_fence"`
	ManifestSha256          []byte             `db:"manifest_sha256" json:"manifest_sha256"`
	RetentionPolicyRevision string             `db:"retention_policy_revision" json:"retention_policy_revision"`
	RetentionExpiresAt      pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	CommittedAt             pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
}

func (q *Queries) InsertArtifactSet(ctx context.Context, arg InsertArtifactSetParams) error {
	_, err := q.db.Exec(ctx, insertArtifactSet,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.ManifestSha256,
		arg.RetentionPolicyRevision,
		arg.RetentionExpiresAt,
		arg.CommittedAt,
	)
	return err
}

const insertArtifactSetItem = `-- name: InsertArtifactSetItem :exec
INSERT INTO artifact_set_items (
    organization_id,
    project_id,
    job_id,
    attempt_id,
    attempt_fence,
    artifact_set_id,
    artifact_id,
    kind,
    ordinal,
    object_key,
    object_version_id,
    size_bytes,
    sha256,
    content_type,
    validation_receipt,
    verified_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
`

type InsertArtifactSetItemParams struct {
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID         uuid.UUID          `db:"project_id" json:"project_id"`
	JobID             uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID         uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence      int64              `db:"attempt_fence" json:"attempt_fence"`
	ArtifactSetID     uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	ArtifactID        uuid.UUID          `db:"artifact_id" json:"artifact_id"`
	Kind              ArtifactKind       `db:"kind" json:"kind"`
	Ordinal           int32              `db:"ordinal" json:"ordinal"`
	ObjectKey         string             `db:"object_key" json:"object_key"`
	ObjectVersionID   string             `db:"object_version_id" json:"object_version_id"`
	SizeBytes         int64              `db:"size_bytes" json:"size_bytes"`
	Sha256            []byte             `db:"sha256" json:"sha256"`
	ContentType       string             `db:"content_type" json:"content_type"`
	ValidationReceipt []byte             `db:"validation_receipt" json:"validation_receipt"`
	VerifiedAt        pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
}

func (q *Queries) InsertArtifactSetItem(ctx context.Context, arg InsertArtifactSetItemParams) error {
	_, err := q.db.Exec(ctx, insertArtifactSetItem,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.ArtifactSetID,
		arg.ArtifactID,
		arg.Kind,
		arg.Ordinal,
		arg.ObjectKey,
		arg.ObjectVersionID,
		arg.SizeBytes,
		arg.Sha256,
		arg.ContentType,
		arg.ValidationReceipt,
		arg.VerifiedAt,
	)
	return err
}

const insertStageGraphFinalizationClaim = `-- name: InsertStageGraphFinalizationClaim :exec
INSERT INTO stage_graph_finalization_claims (
    id, organization_id, project_id, job_id, attempt_id, attempt_fence,
    final_stage_run_id, final_stage_artifact_id, exact_object_version,
    owner_id, token_digest, signing_key_id, output_set_digest, issued_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8,
    $9, $10, $11,
    $12, $13,
    $14, $15
)
`

type InsertStageGraphFinalizationClaimParams struct {
	ClaimID              uuid.UUID          `db:"claim_id" json:"claim_id"`
	OrganizationID       uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID            uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID            uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence         int64              `db:"attempt_fence" json:"attempt_fence"`
	FinalStageRunID      uuid.UUID          `db:"final_stage_run_id" json:"final_stage_run_id"`
	FinalStageArtifactID uuid.UUID          `db:"final_stage_artifact_id" json:"final_stage_artifact_id"`
	ExactObjectVersion   string             `db:"exact_object_version" json:"exact_object_version"`
	OwnerID              string             `db:"owner_id" json:"owner_id"`
	TokenDigest          []byte             `db:"token_digest" json:"token_digest"`
	SigningKeyID         string             `db:"signing_key_id" json:"signing_key_id"`
	OutputSetDigest      []byte             `db:"output_set_digest" json:"output_set_digest"`
	IssuedAt             pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) InsertStageGraphFinalizationClaim(ctx context.Context, arg InsertStageGraphFinalizationClaimParams) error {
	_, err := q.db.Exec(ctx, insertStageGraphFinalizationClaim,
		arg.ClaimID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.FinalStageRunID,
		arg.FinalStageArtifactID,
		arg.ExactObjectVersion,
		arg.OwnerID,
		arg.TokenDigest,
		arg.SigningKeyID,
		arg.OutputSetDigest,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertStageGraphFinalizationClaimOutput = `-- name: InsertStageGraphFinalizationClaimOutput :exec
INSERT INTO stage_graph_finalization_claim_outputs (
    claim_id, organization_id, project_id, attempt_id, output_key,
    artifact_kind, ordinal, stage_run_id, stage_artifact_id,
    stage_interface_revision_id, exact_object_version
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
`

type InsertStageGraphFinalizationClaimOutputParams struct {
	ClaimID                  uuid.UUID    `db:"claim_id" json:"claim_id"`
	OrganizationID           uuid.UUID    `db:"organization_id" json:"organization_id"`
	ProjectID                uuid.UUID    `db:"project_id" json:"project_id"`
	AttemptID                uuid.UUID    `db:"attempt_id" json:"attempt_id"`
	OutputKey                string       `db:"output_key" json:"output_key"`
	ArtifactKind             ArtifactKind `db:"artifact_kind" json:"artifact_kind"`
	Ordinal                  int32        `db:"ordinal" json:"ordinal"`
	StageRunID               uuid.UUID    `db:"stage_run_id" json:"stage_run_id"`
	StageArtifactID          uuid.UUID    `db:"stage_artifact_id" json:"stage_artifact_id"`
	StageInterfaceRevisionID uuid.UUID    `db:"stage_interface_revision_id" json:"stage_interface_revision_id"`
	ExactObjectVersion       string       `db:"exact_object_version" json:"exact_object_version"`
}

func (q *Queries) InsertStageGraphFinalizationClaimOutput(ctx context.Context, arg InsertStageGraphFinalizationClaimOutputParams) error {
	_, err := q.db.Exec(ctx, insertStageGraphFinalizationClaimOutput,
		arg.ClaimID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.AttemptID,
		arg.OutputKey,
		arg.ArtifactKind,
		arg.Ordinal,
		arg.StageRunID,
		arg.StageArtifactID,
		arg.StageInterfaceRevisionID,
		arg.ExactObjectVersion,
	)
	return err
}

const insertStageGraphVisibleCompletion = `-- name: InsertStageGraphVisibleCompletion :exec
INSERT INTO visible_completions (
    id,
    organization_id,
    project_id,
    job_id,
    attempt_id,
    attempt_fence,
    authority_stage_graph_finalization_claim_id,
    artifact_set_id,
    charge_id,
    candidate_sha256,
    job_version,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type InsertStageGraphVisibleCompletionParams struct {
	ID                                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID                         uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                              uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                                  uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID                              uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence                           int64              `db:"attempt_fence" json:"attempt_fence"`
	AuthorityStageGraphFinalizationClaimID uuid.NullUUID      `db:"authority_stage_graph_finalization_claim_id" json:"authority_stage_graph_finalization_claim_id"`
	ArtifactSetID                          uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	ChargeID                               uuid.UUID          `db:"charge_id" json:"charge_id"`
	CandidateSha256                        []byte             `db:"candidate_sha256" json:"candidate_sha256"`
	JobVersion                             int64              `db:"job_version" json:"job_version"`
	CompletedAt                            pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) InsertStageGraphVisibleCompletion(ctx context.Context, arg InsertStageGraphVisibleCompletionParams) error {
	_, err := q.db.Exec(ctx, insertStageGraphVisibleCompletion,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.AuthorityStageGraphFinalizationClaimID,
		arg.ArtifactSetID,
		arg.ChargeID,
		arg.CandidateSha256,
		arg.JobVersion,
		arg.CompletedAt,
	)
	return err
}

const insertVerifiedStageGraphArtifact = `-- name: InsertVerifiedStageGraphArtifact :exec
INSERT INTO artifacts (
    id, organization_id, project_id, job_id, attempt_id, attempt_fence,
    kind, ordinal, object_key, expected_content_type, object_version_id,
    size_bytes, sha256, content_type, uploaded_at, verification_id,
    verification_request_hash, validation_receipt, verified_at, state,
    expires_at, source_stage_artifact_id, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $10, $14,
    $15, $16,
    $17, $14, 'VERIFIED',
    $18, $19, $14
)
`

type InsertVerifiedStageGraphArtifactParams struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	OrganizationID          uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID               uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence            int64              `db:"attempt_fence" json:"attempt_fence"`
	Kind                    ArtifactKind       `db:"kind" json:"kind"`
	Ordinal                 int32              `db:"ordinal" json:"ordinal"`
	ObjectKey               string             `db:"object_key" json:"object_key"`
	ContentType             string             `db:"content_type" json:"content_type"`
	ObjectVersionID         *string            `db:"object_version_id" json:"object_version_id"`
	SizeBytes               *int64             `db:"size_bytes" json:"size_bytes"`
	Sha256                  []byte             `db:"sha256" json:"sha256"`
	VerifiedAt              pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	VerificationID          uuid.NullUUID      `db:"verification_id" json:"verification_id"`
	VerificationRequestHash []byte             `db:"verification_request_hash" json:"verification_request_hash"`
	ValidationReceipt       []byte             `db:"validation_receipt" json:"validation_receipt"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SourceStageArtifactID   uuid.NullUUID      `db:"source_stage_artifact_id" json:"source_stage_artifact_id"`
}

func (q *Queries) InsertVerifiedStageGraphArtifact(ctx context.Context, arg InsertVerifiedStageGraphArtifactParams) error {
	_, err := q.db.Exec(ctx, insertVerifiedStageGraphArtifact,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.Kind,
		arg.Ordinal,
		arg.ObjectKey,
		arg.ContentType,
		arg.ObjectVersionID,
		arg.SizeBytes,
		arg.Sha256,
		arg.VerifiedAt,
		arg.VerificationID,
		arg.VerificationRequestHash,
		arg.ValidationReceipt,
		arg.ExpiresAt,
		arg.SourceStageArtifactID,
	)
	return err
}

const insertVisibleCompletion = `-- name: InsertVisibleCompletion :exec
INSERT INTO visible_completions (
    id,
    organization_id,
    project_id,
    job_id,
    attempt_id,
    attempt_fence,
    authority_lease_id,
    artifact_set_id,
    charge_id,
    candidate_sha256,
    job_version,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type InsertVisibleCompletionParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	JobID            uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID        uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence     int64              `db:"attempt_fence" json:"attempt_fence"`
	AuthorityLeaseID uuid.NullUUID      `db:"authority_lease_id" json:"authority_lease_id"`
	ArtifactSetID    uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	ChargeID         uuid.UUID          `db:"charge_id" json:"charge_id"`
	CandidateSha256  []byte             `db:"candidate_sha256" json:"candidate_sha256"`
	JobVersion       int64              `db:"job_version" json:"job_version"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) InsertVisibleCompletion(ctx context.Context, arg InsertVisibleCompletionParams) error {
	_, err := q.db.Exec(ctx, insertVisibleCompletion,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.AttemptID,
		arg.AttemptFence,
		arg.AuthorityLeaseID,
		arg.ArtifactSetID,
		arg.ChargeID,
		arg.CandidateSha256,
		arg.JobVersion,
		arg.CompletedAt,
	)
	return err
}

const insertVisibleCompletionCharge = `-- name: InsertVisibleCompletionCharge :exec
INSERT INTO charges (
    id,
    organization_id,
    project_id,
    job_id,
    credit_reservation_id,
    cancellation_id,
    artifact_set_id,
    reason,
    amount_minor,
    currency,
    posted_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NULL,
    $6,
    'VISIBLE_COMPLETION',
    $7,
    $8,
    $9
)
`

type InsertVisibleCompletionChargeParams struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	OrganizationID      uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID           uuid.UUID          `db:"project_id" json:"project_id"`
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
	CreditReservationID uuid.UUID          `db:"credit_reservation_id" json:"credit_reservation_id"`
	ArtifactSetID       uuid.NullUUID      `db:"artifact_set_id" json:"artifact_set_id"`
	AmountMinor         int64              `db:"amount_minor" json:"amount_minor"`
	Currency            string             `db:"currency" json:"currency"`
	PostedAt            pgtype.Timestamptz `db:"posted_at" json:"posted_at"`
}

func (q *Queries) InsertVisibleCompletionCharge(ctx context.Context, arg InsertVisibleCompletionChargeParams) error {
	_, err := q.db.Exec(ctx, insertVisibleCompletionCharge,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.CreditReservationID,
		arg.ArtifactSetID,
		arg.AmountMinor,
		arg.Currency,
		arg.PostedAt,
	)
	return err
}

const insertVisibleCompletionOutboxEvent = `-- name: InsertVisibleCompletionOutboxEvent :exec
INSERT INTO outbox_events (
    event_id,
    organization_id,
    project_id,
    aggregate_type,
    aggregate_id,
    aggregate_version,
    event_type,
    schema_version,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    'Job',
    $4,
    $5,
    $6,
    1,
    $7,
    $8
)
`

type InsertVisibleCompletionOutboxEventParams struct {
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	JobVersion     int64              `db:"job_version" json:"job_version"`
	EventType      string             `db:"event_type" json:"event_type"`
	Payload        []byte             `db:"payload" json:"payload"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) InsertVisibleCompletionOutboxEvent(ctx context.Context, arg InsertVisibleCompletionOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertVisibleCompletionOutboxEvent,
		arg.EventID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.JobVersion,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listCommittedArtifactSetItems = `-- name: ListCommittedArtifactSetItems :many
SELECT
    artifact_id,
    kind,
    ordinal,
    object_key,
    object_version_id,
    size_bytes,
    sha256,
    content_type,
    validation_receipt,
    verified_at
FROM artifact_set_items
WHERE artifact_set_id = $1
ORDER BY CASE kind WHEN 'VIDEO' THEN 0 ELSE 1 END, ordinal
`

type ListCommittedArtifactSetItemsRow struct {
	ArtifactID        uuid.UUID          `db:"artifact_id" json:"artifact_id"`
	Kind              ArtifactKind       `db:"kind" json:"kind"`
	Ordinal           int32              `db:"ordinal" json:"ordinal"`
	ObjectKey         string             `db:"object_key" json:"object_key"`
	ObjectVersionID   string             `db:"object_version_id" json:"object_version_id"`
	SizeBytes         int64              `db:"size_bytes" json:"size_bytes"`
	Sha256            []byte             `db:"sha256" json:"sha256"`
	ContentType       string             `db:"content_type" json:"content_type"`
	ValidationReceipt []byte             `db:"validation_receipt" json:"validation_receipt"`
	VerifiedAt        pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
}

func (q *Queries) ListCommittedArtifactSetItems(ctx context.Context, artifactSetID uuid.UUID) ([]ListCommittedArtifactSetItemsRow, error) {
	rows, err := q.db.Query(ctx, listCommittedArtifactSetItems, artifactSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommittedArtifactSetItemsRow{}
	for rows.Next() {
		var i ListCommittedArtifactSetItemsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.Kind,
			&i.Ordinal,
			&i.ObjectKey,
			&i.ObjectVersionID,
			&i.SizeBytes,
			&i.Sha256,
			&i.ContentType,
			&i.ValidationReceipt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionArtifactsForUpdate = `-- name: ListCompletionArtifactsForUpdate :many
SELECT
    id,
    organization_id,
    project_id,
    job_id,
    attempt_id,
    attempt_fence,
    kind,
    ordinal,
    object_key,
    object_version_id,
    size_bytes,
    sha256,
    content_type,
    validation_receipt,
    verified_at,
    state
FROM artifacts
WHERE attempt_id = $1
  AND attempt_fence = $2
ORDER BY CASE kind WHEN 'VIDEO' THEN 0 ELSE 1 END, ordinal
FOR UPDATE
`

type ListCompletionArtifactsForUpdateParams struct {
	AttemptID    uuid.UUID `db:"attempt_id" json:"attempt_id"`
	AttemptFence int64     `db:"attempt_fence" json:"attempt_fence"`
}

type ListCompletionArtifactsForUpdateRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID         uuid.UUID          `db:"project_id" json:"project_id"`
	JobID             uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID         uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence      int64              `db:"attempt_fence" json:"attempt_fence"`
	Kind              ArtifactKind       `db:"kind" json:"kind"`
	Ordinal           int32              `db:"ordinal" json:"ordinal"`
	ObjectKey         string             `db:"object_key" json:"object_key"`
	ObjectVersionID   *string            `db:"object_version_id" json:"object_version_id"`
	SizeBytes         *int64             `db:"size_bytes" json:"size_bytes"`
	Sha256            []byte             `db:"sha256" json:"sha256"`
	ContentType       *string            `db:"content_type" json:"content_type"`
	ValidationReceipt []byte             `db:"validation_receipt" json:"validation_receipt"`
	VerifiedAt        pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	State             ArtifactState      `db:"state" json:"state"`
}

func (q *Queries) ListCompletionArtifactsForUpdate(ctx context.Context, arg ListCompletionArtifactsForUpdateParams) ([]ListCompletionArtifactsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listCompletionArtifactsForUpdate, arg.AttemptID, arg.AttemptFence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletionArtifactsForUpdateRow{}
	for rows.Next() {
		var i ListCompletionArtifactsForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.JobID,
			&i.AttemptID,
			&i.AttemptFence,
			&i.Kind,
			&i.Ordinal,
			&i.ObjectKey,
			&i.ObjectVersionID,
			&i.SizeBytes,
			&i.Sha256,
			&i.ContentType,
			&i.ValidationReceipt,
			&i.VerifiedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageGraphFinalizationClaimOutputs = `-- name: ListStageGraphFinalizationClaimOutputs :many
SELECT
    output.output_key,
    output.artifact_kind,
    output.ordinal,
    output.stage_run_id,
    output.stage_artifact_id,
    output.stage_interface_revision_id,
    output.exact_object_version,
    artifact.object_key,
    artifact.content_type,
    artifact.sha256,
    artifact.size_bytes,
    artifact.expires_at
FROM stage_graph_finalization_claim_outputs AS output
JOIN stage_artifacts AS artifact
  ON artifact.id = output.stage_artifact_id
 AND artifact.stage_interface_revision_id = output.stage_interface_revision_id
 AND artifact.object_version = output.exact_object_version
 AND artifact.state = 'COMMITTED'
WHERE output.claim_id = $1
ORDER BY output.output_key
`

type ListStageGraphFinalizationClaimOutputsRow struct {
	OutputKey                string             `db:"output_key" json:"output_key"`
	ArtifactKind             ArtifactKind       `db:"artifact_kind" json:"artifact_kind"`
	Ordinal                  int32              `db:"ordinal" json:"ordinal"`
	StageRunID               uuid.UUID          `db:"stage_run_id" json:"stage_run_id"`
	StageArtifactID          uuid.UUID          `db:"stage_artifact_id" json:"stage_artifact_id"`
	StageInterfaceRevisionID uuid.UUID          `db:"stage_interface_revision_id" json:"stage_interface_revision_id"`
	ExactObjectVersion       string             `db:"exact_object_version" json:"exact_object_version"`
	ObjectKey                string             `db:"object_key" json:"object_key"`
	ContentType              string             `db:"content_type" json:"content_type"`
	Sha256                   []byte             `db:"sha256" json:"sha256"`
	SizeBytes                int64              `db:"size_bytes" json:"size_bytes"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ListStageGraphFinalizationClaimOutputs(ctx context.Context, claimID uuid.UUID) ([]ListStageGraphFinalizationClaimOutputsRow, error) {
	rows, err := q.db.Query(ctx, listStageGraphFinalizationClaimOutputs, claimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageGraphFinalizationClaimOutputsRow{}
	for rows.Next() {
		var i ListStageGraphFinalizationClaimOutputsRow
		if err := rows.Scan(
			&i.OutputKey,
			&i.ArtifactKind,
			&i.Ordinal,
			&i.StageRunID,
			&i.StageArtifactID,
			&i.StageInterfaceRevisionID,
			&i.ExactObjectVersion,
			&i.ObjectKey,
			&i.ContentType,
			&i.Sha256,
			&i.SizeBytes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStageGraphFinalizationOutputs = `-- name: ListStageGraphFinalizationOutputs :many
SELECT
    output.output_key,
    output.interface_revision_id AS stage_interface_revision_id,
    run.id AS stage_run_id,
    artifact.id AS stage_artifact_id,
    artifact.object_key,
    artifact.object_version,
    artifact.content_type,
    artifact.sha256,
    artifact.size_bytes,
    artifact.expires_at
FROM stage_runs AS run
JOIN execution_graph_outputs AS output
  ON output.execution_graph_revision_id = run.execution_graph_revision_id
 AND output.source_stage_key = run.stage_key
JOIN stage_run_output_bindings AS binding
  ON binding.attempt_id = run.attempt_id
 AND binding.stage_run_id = run.id
 AND binding.output_port = output.source_port
 AND binding.stage_interface_revision_id = output.interface_revision_id
JOIN stage_artifacts AS artifact
  ON artifact.id = binding.stage_artifact_id
WHERE run.attempt_id = $1
  AND run.state = 'SUCCEEDED'
  AND output.required
  AND artifact.state = 'COMMITTED'
ORDER BY output.output_key
`

type ListStageGraphFinalizationOutputsRow struct {
	OutputKey                string             `db:"output_key" json:"output_key"`
	StageInterfaceRevisionID uuid.UUID          `db:"stage_interface_revision_id" json:"stage_interface_revision_id"`
	StageRunID               uuid.UUID          `db:"stage_run_id" json:"stage_run_id"`
	StageArtifactID          uuid.UUID          `db:"stage_artifact_id" json:"stage_artifact_id"`
	ObjectKey                string             `db:"object_key" json:"object_key"`
	ObjectVersion            string             `db:"object_version" json:"object_version"`
	ContentType              string             `db:"content_type" json:"content_type"`
	Sha256                   []byte             `db:"sha256" json:"sha256"`
	SizeBytes                int64              `db:"size_bytes" json:"size_bytes"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ListStageGraphFinalizationOutputs(ctx context.Context, attemptID uuid.UUID) ([]ListStageGraphFinalizationOutputsRow, error) {
	rows, err := q.db.Query(ctx, listStageGraphFinalizationOutputs, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStageGraphFinalizationOutputsRow{}
	for rows.Next() {
		var i ListStageGraphFinalizationOutputsRow
		if err := rows.Scan(
			&i.OutputKey,
			&i.StageInterfaceRevisionID,
			&i.StageRunID,
			&i.StageArtifactID,
			&i.ObjectKey,
			&i.ObjectVersion,
			&i.ContentType,
			&i.Sha256,
			&i.SizeBytes,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNextStageGraphFinalizationCandidate = `-- name: LockNextStageGraphFinalizationCandidate :one
SELECT
    attempt.organization_id,
    attempt.project_id,
    attempt.job_id,
    attempt.id AS attempt_id,
    attempt.fence AS attempt_fence,
    attempt.finalization_started_at,
    attempt.finalization_deadline_at,
    job.version AS job_version,
    job.job_expires_at,
    run.id AS final_stage_run_id,
    artifact.id AS final_stage_artifact_id,
    artifact.object_key,
    artifact.object_version,
    artifact.content_type,
    artifact.sha256,
    artifact.size_bytes,
    artifact.stage_interface_revision_id,
    artifact.expires_at AS artifact_expires_at
FROM attempts AS attempt
JOIN jobs AS job ON job.id = attempt.job_id
JOIN stage_runs AS run ON run.attempt_id = attempt.id
JOIN stage_run_output_bindings AS binding
  ON binding.attempt_id = attempt.id
 AND binding.stage_run_id = run.id
JOIN stage_artifacts AS artifact ON artifact.id = binding.stage_artifact_id
WHERE attempt.state = 'FINALIZING'
  AND attempt.graph_state = 'FINALIZING'
  AND attempt.finalization_deadline_at > $1
  AND job.state = 'FINALIZING'
  AND job.current_fence = attempt.fence
  AND job.job_expires_at > $1
  AND run.state = 'SUCCEEDED'
  AND artifact.state = 'COMMITTED'
  AND artifact.expires_at > $1
  AND NOT EXISTS (
      SELECT 1
      FROM stage_dependencies AS outgoing
      WHERE outgoing.attempt_id = attempt.id
        AND outgoing.source_stage_run_id = run.id
  )
  AND NOT EXISTS (
      SELECT 1
      FROM stage_graph_finalization_claims AS active_claim
      WHERE active_claim.attempt_id = attempt.id
        AND active_claim.state = 'ACTIVE'
  )
ORDER BY attempt.finalization_started_at, attempt.id, run.id
LIMIT 1
FOR UPDATE OF attempt, job SKIP LOCKED
`

type LockNextStageGraphFinalizationCandidateRow struct {
	OrganizationID           uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                    uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID                uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence             int64              `db:"attempt_fence" json:"attempt_fence"`
	FinalizationStartedAt    pgtype.Timestamptz `db:"finalization_started_at" json:"finalization_started_at"`
	FinalizationDeadlineAt   pgtype.Timestamptz `db:"finalization_deadline_at" json:"finalization_deadline_at"`
	JobVersion               int64              `db:"job_version" json:"job_version"`
	JobExpiresAt             pgtype.Timestamptz `db:"job_expires_at" json:"job_expires_at"`
	FinalStageRunID          uuid.UUID          `db:"final_stage_run_id" json:"final_stage_run_id"`
	FinalStageArtifactID     uuid.UUID          `db:"final_stage_artifact_id" json:"final_stage_artifact_id"`
	ObjectKey                string             `db:"object_key" json:"object_key"`
	ObjectVersion            string             `db:"object_version" json:"object_version"`
	ContentType              string             `db:"content_type" json:"content_type"`
	Sha256                   []byte             `db:"sha256" json:"sha256"`
	SizeBytes                int64              `db:"size_bytes" json:"size_bytes"`
	StageInterfaceRevisionID uuid.UUID          `db:"stage_interface_revision_id" json:"stage_interface_revision_id"`
	ArtifactExpiresAt        pgtype.Timestamptz `db:"artifact_expires_at" json:"artifact_expires_at"`
}

func (q *Queries) LockNextStageGraphFinalizationCandidate(ctx context.Context, observedAt pgtype.Timestamptz) (LockNextStageGraphFinalizationCandidateRow, error) {
	row := q.db.QueryRow(ctx, lockNextStageGraphFinalizationCandidate, observedAt)
	var i LockNextStageGraphFinalizationCandidateRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ProjectID,
		&i.JobID,
		&i.AttemptID,
		&i.AttemptFence,
		&i.FinalizationStartedAt,
		&i.FinalizationDeadlineAt,
		&i.JobVersion,
		&i.JobExpiresAt,
		&i.FinalStageRunID,
		&i.FinalStageArtifactID,
		&i.ObjectKey,
		&i.ObjectVersion,
		&i.ContentType,
		&i.Sha256,
		&i.SizeBytes,
		&i.StageInterfaceRevisionID,
		&i.ArtifactExpiresAt,
	)
	return i, err
}

const lockStageGraphFinalizationCompletionAuthority = `-- name: LockStageGraphFinalizationCompletionAuthority :one
SELECT
    claim.id AS claim_id,
    claim.attempt_id,
    claim.attempt_fence,
    claim.owner_id,
    claim.token_digest,
    claim.signing_key_id,
    claim.output_set_digest,
    claim.state AS claim_state,
    claim.issued_at,
    claim.expires_at AS claim_expires_at,
    attempt.job_id,
    attempt.state AS attempt_state,
    attempt.graph_state,
    attempt.fence AS current_attempt_fence,
    attempt.ended_at AS attempt_ended_at,
    attempt.finalization_deadline_at,
    job.organization_id,
    job.project_id,
    job.state AS job_state,
    job.version AS job_version,
    job.current_fence,
    job.job_expires_at,
    job.retention_artifact_days,
    retention_policy.stable_id AS retention_policy_revision,
    job.pricing_quantity AS generation_count,
    job.request_content_deleted_at,
    reservation.id AS credit_reservation_id,
    reservation.state AS credit_reservation_state,
    reservation.amount_minor,
    reservation.currency,
    output_spec.width AS expected_width,
    output_spec.height AS expected_height,
    output_spec.duration_milliseconds AS expected_duration_milliseconds,
    output_spec.frame_rate_milli AS expected_frame_rate_milli,
    output_spec.codec AS expected_codec,
    output_spec.container AS expected_container,
    completion.id AS completion_id,
    completion.authority_lease_id AS completion_authority_lease_id,
    completion.authority_stage_graph_finalization_claim_id AS
        completion_authority_stage_graph_finalization_claim_id,
    completion.candidate_sha256,
    completion.artifact_set_id,
    completion.charge_id,
    completion.job_version AS completion_job_version,
    completion.completed_at,
    artifact_set.manifest_sha256,
    artifact_set.retention_expires_at
FROM stage_graph_finalization_claims AS claim
JOIN attempts AS attempt ON attempt.id = claim.attempt_id
JOIN jobs AS job ON job.id = claim.job_id
JOIN retention_policy_revisions AS retention_policy
  ON retention_policy.id = job.retention_policy_revision_id
JOIN credit_reservations AS reservation ON reservation.job_id = job.id
JOIN output_specs AS output_spec ON output_spec.id = job.output_spec_id
LEFT JOIN visible_completions AS completion ON completion.job_id = job.id
LEFT JOIN artifact_sets AS artifact_set ON artifact_set.id = completion.artifact_set_id
WHERE claim.id = $1
  AND claim.attempt_id = $2
  AND claim.attempt_fence = $3
LIMIT 1
FOR UPDATE OF claim, attempt, job
`

type LockStageGraphFinalizationCompletionAuthorityParams struct {
	ClaimID      uuid.UUID `db:"claim_id" json:"claim_id"`
	AttemptID    uuid.UUID `db:"attempt_id" json:"attempt_id"`
	AttemptFence int64     `db:"attempt_fence" json:"attempt_fence"`
}

type LockStageGraphFinalizationCompletionAuthorityRow struct {
	ClaimID                                          uuid.UUID                        `db:"claim_id" json:"claim_id"`
	AttemptID                                        uuid.UUID                        `db:"attempt_id" json:"attempt_id"`
	AttemptFence                                     int64                            `db:"attempt_fence" json:"attempt_fence"`
	OwnerID                                          string                           `db:"owner_id" json:"owner_id"`
	TokenDigest                                      []byte                           `db:"token_digest" json:"token_digest"`
	SigningKeyID                                     string                           `db:"signing_key_id" json:"signing_key_id"`
	OutputSetDigest                                  []byte                           `db:"output_set_digest" json:"output_set_digest"`
	ClaimState                                       StageGraphFinalizationClaimState `db:"claim_state" json:"claim_state"`
	IssuedAt                                         pgtype.Timestamptz               `db:"issued_at" json:"issued_at"`
	ClaimExpiresAt                                   pgtype.Timestamptz               `db:"claim_expires_at" json:"claim_expires_at"`
	JobID                                            uuid.UUID                        `db:"job_id" json:"job_id"`
	AttemptState                                     AttemptState                     `db:"attempt_state" json:"attempt_state"`
	GraphState                                       *GraphAttemptState               `db:"graph_state" json:"graph_state"`
	CurrentAttemptFence                              int64                            `db:"current_attempt_fence" json:"current_attempt_fence"`
	AttemptEndedAt                                   pgtype.Timestamptz               `db:"attempt_ended_at" json:"attempt_ended_at"`
	FinalizationDeadlineAt                           pgtype.Timestamptz               `db:"finalization_deadline_at" json:"finalization_deadline_at"`
	OrganizationID                                   uuid.UUID                        `db:"organization_id" json:"organization_id"`
	ProjectID                                        uuid.UUID                        `db:"project_id" json:"project_id"`
	JobState                                         JobState                         `db:"job_state" json:"job_state"`
	JobVersion                                       int64                            `db:"job_version" json:"job_version"`
	CurrentFence                                     int64                            `db:"current_fence" json:"current_fence"`
	JobExpiresAt                                     pgtype.Timestamptz               `db:"job_expires_at" json:"job_expires_at"`
	RetentionArtifactDays                            int32                            `db:"retention_artifact_days" json:"retention_artifact_days"`
	RetentionPolicyRevision                          string                           `db:"retention_policy_revision" json:"retention_policy_revision"`
	GenerationCount                                  int32                            `db:"generation_count" json:"generation_count"`
	RequestContentDeletedAt                          pgtype.Timestamptz               `db:"request_content_deleted_at" json:"request_content_deleted_at"`
	CreditReservationID                              uuid.UUID                        `db:"credit_reservation_id" json:"credit_reservation_id"`
	CreditReservationState                           CreditReservationState           `db:"credit_reservation_state" json:"credit_reservation_state"`
	AmountMinor                                      int64                            `db:"amount_minor" json:"amount_minor"`
	Currency                                         string                           `db:"currency" json:"currency"`
	ExpectedWidth                                    int32                            `db:"expected_width" json:"expected_width"`
	ExpectedHeight                                   int32                            `db:"expected_height" json:"expected_height"`
	ExpectedDurationMilliseconds                     int32                            `db:"expected_duration_milliseconds" json:"expected_duration_milliseconds"`
	ExpectedFrameRateMilli                           int32                            `db:"expected_frame_rate_milli" json:"expected_frame_rate_milli"`
	ExpectedCodec                                    string                           `db:"expected_codec" json:"expected_codec"`
	ExpectedContainer                                string                           `db:"expected_container" json:"expected_container"`
	CompletionID                                     uuid.NullUUID                    `db:"completion_id" json:"completion_id"`
	CompletionAuthorityLeaseID                       uuid.NullUUID                    `db:"completion_authority_lease_id" json:"completion_authority_lease_id"`
	CompletionAuthorityStageGraphFinalizationClaimID uuid.NullUUID                    `db:"completion_authority_stage_graph_finalization_claim_id" json:"completion_authority_stage_graph_finalization_claim_id"`
	CandidateSha256                                  []byte                           `db:"candidate_sha256" json:"candidate_sha256"`
	ArtifactSetID                                    uuid.NullUUID                    `db:"artifact_set_id" json:"artifact_set_id"`
	ChargeID                                         uuid.NullUUID                    `db:"charge_id" json:"charge_id"`
	CompletionJobVersion                             *int64                           `db:"completion_job_version" json:"completion_job_version"`
	CompletedAt                                      pgtype.Timestamptz               `db:"completed_at" json:"completed_at"`
	ManifestSha256                                   []byte                           `db:"manifest_sha256" json:"manifest_sha256"`
	RetentionExpiresAt                               pgtype.Timestamptz               `db:"retention_expires_at" json:"retention_expires_at"`
}

func (q *Queries) LockStageGraphFinalizationCompletionAuthority(ctx context.Context, arg LockStageGraphFinalizationCompletionAuthorityParams) (LockStageGraphFinalizationCompletionAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockStageGraphFinalizationCompletionAuthority, arg.ClaimID, arg.AttemptID, arg.AttemptFence)
	var i LockStageGraphFinalizationCompletionAuthorityRow
	err := row.Scan(
		&i.ClaimID,
		&i.AttemptID,
		&i.AttemptFence,
		&i.OwnerID,
		&i.TokenDigest,
		&i.SigningKeyID,
		&i.OutputSetDigest,
		&i.ClaimState,
		&i.IssuedAt,
		&i.ClaimExpiresAt,
		&i.JobID,
		&i.AttemptState,
		&i.GraphState,
		&i.CurrentAttemptFence,
		&i.AttemptEndedAt,
		&i.FinalizationDeadlineAt,
		&i.OrganizationID,
		&i.ProjectID,
		&i.JobState,
		&i.JobVersion,
		&i.CurrentFence,
		&i.JobExpiresAt,
		&i.RetentionArtifactDays,
		&i.RetentionPolicyRevision,
		&i.GenerationCount,
		&i.RequestContentDeletedAt,
		&i.CreditReservationID,
		&i.CreditReservationState,
		&i.AmountMinor,
		&i.Currency,
		&i.ExpectedWidth,
		&i.ExpectedHeight,
		&i.ExpectedDurationMilliseconds,
		&i.ExpectedFrameRateMilli,
		&i.ExpectedCodec,
		&i.ExpectedContainer,
		&i.CompletionID,
		&i.CompletionAuthorityLeaseID,
		&i.CompletionAuthorityStageGraphFinalizationClaimID,
		&i.CandidateSha256,
		&i.ArtifactSetID,
		&i.ChargeID,
		&i.CompletionJobVersion,
		&i.CompletedAt,
		&i.ManifestSha256,
		&i.RetentionExpiresAt,
	)
	return i, err
}

const lockVisibleCompletionCreditReservation = `-- name: LockVisibleCompletionCreditReservation :one
SELECT id, state, amount_minor, currency
FROM credit_reservations
WHERE id = $1
  AND job_id = $2
FOR UPDATE
`

type LockVisibleCompletionCreditReservationParams struct {
	CreditReservationID uuid.UUID `db:"credit_reservation_id" json:"credit_reservation_id"`
	JobID               uuid.UUID `db:"job_id" json:"job_id"`
}

type LockVisibleCompletionCreditReservationRow struct {
	ID          uuid.UUID              `db:"id" json:"id"`
	State       CreditReservationState `db:"state" json:"state"`
	AmountMinor int64                  `db:"amount_minor" json:"amount_minor"`
	Currency    string                 `db:"currency" json:"currency"`
}

func (q *Queries) LockVisibleCompletionCreditReservation(ctx context.Context, arg LockVisibleCompletionCreditReservationParams) (LockVisibleCompletionCreditReservationRow, error) {
	row := q.db.QueryRow(ctx, lockVisibleCompletionCreditReservation, arg.CreditReservationID, arg.JobID)
	var i LockVisibleCompletionCreditReservationRow
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.AmountMinor,
		&i.Currency,
	)
	return i, err
}

const lockVisibleCompletionOrganizationCredit = `-- name: LockVisibleCompletionOrganizationCredit :one
SELECT currency, reserved_minor, unsettled_posted_minor
FROM organization_credit_accounts
WHERE organization_id = $1
FOR UPDATE
`

type LockVisibleCompletionOrganizationCreditRow struct {
	Currency             string `db:"currency" json:"currency"`
	ReservedMinor        int64  `db:"reserved_minor" json:"reserved_minor"`
	UnsettledPostedMinor int64  `db:"unsettled_posted_minor" json:"unsettled_posted_minor"`
}

func (q *Queries) LockVisibleCompletionOrganizationCredit(ctx context.Context, organizationID uuid.UUID) (LockVisibleCompletionOrganizationCreditRow, error) {
	row := q.db.QueryRow(ctx, lockVisibleCompletionOrganizationCredit, organizationID)
	var i LockVisibleCompletionOrganizationCreditRow
	err := row.Scan(&i.Currency, &i.ReservedMinor, &i.UnsettledPostedMinor)
	return i, err
}

const lockVisibleCompletionProject = `-- name: LockVisibleCompletionProject :one
SELECT running_count
FROM projects
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type LockVisibleCompletionProjectParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) LockVisibleCompletionProject(ctx context.Context, arg LockVisibleCompletionProjectParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockVisibleCompletionProject, arg.OrganizationID, arg.ProjectID)
	var running_count int32
	err := row.Scan(&running_count)
	return running_count, err
}

const markArtifactCommitted = `-- name: MarkArtifactCommitted :execrows
UPDATE artifacts
SET state = 'COMMITTED',
    retention_expires_at = $1,
    updated_at = $2
WHERE id = $3
  AND attempt_id = $4
  AND attempt_fence = $5
  AND state = 'VERIFIED'
`

type MarkArtifactCommittedParams struct {
	RetentionExpiresAt pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	CommittedAt        pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	ArtifactID         uuid.UUID          `db:"artifact_id" json:"artifact_id"`
	AttemptID          uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence       int64              `db:"attempt_fence" json:"attempt_fence"`
}

func (q *Queries) MarkArtifactCommitted(ctx context.Context, arg MarkArtifactCommittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markArtifactCommitted,
		arg.RetentionExpiresAt,
		arg.CommittedAt,
		arg.ArtifactID,
		arg.AttemptID,
		arg.AttemptFence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markJobSucceeded = `-- name: MarkJobSucceeded :one
UPDATE jobs
SET state = 'SUCCEEDED',
    result_artifact_set_id = $1,
    version = version + 1,
    updated_at = $2
WHERE id = $3
  AND version = $4
  AND current_fence = $5
  AND state = 'FINALIZING'
RETURNING version
`

type MarkJobSucceededParams struct {
	ArtifactSetID   uuid.NullUUID      `db:"artifact_set_id" json:"artifact_set_id"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	ExpectedVersion int64              `db:"expected_version" json:"expected_version"`
	Fence           int64              `db:"fence" json:"fence"`
}

func (q *Queries) MarkJobSucceeded(ctx context.Context, arg MarkJobSucceededParams) (int64, error) {
	row := q.db.QueryRow(ctx, markJobSucceeded,
		arg.ArtifactSetID,
		arg.CompletedAt,
		arg.JobID,
		arg.ExpectedVersion,
		arg.Fence,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const postVisibleCompletionOrganizationCredit = `-- name: PostVisibleCompletionOrganizationCredit :execrows
UPDATE organization_credit_accounts
SET reserved_minor = reserved_minor - $1,
    unsettled_posted_minor = unsettled_posted_minor + $1,
    version = version + 1,
    updated_at = $2
WHERE organization_id = $3
  AND currency = $4
  AND reserved_minor >= $1
`

type PostVisibleCompletionOrganizationCreditParams struct {
	AmountMinor    int64              `db:"amount_minor" json:"amount_minor"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Currency       string             `db:"currency" json:"currency"`
}

func (q *Queries) PostVisibleCompletionOrganizationCredit(ctx context.Context, arg PostVisibleCompletionOrganizationCreditParams) (int64, error) {
	result, err := q.db.Exec(ctx, postVisibleCompletionOrganizationCredit,
		arg.AmountMinor,
		arg.CompletedAt,
		arg.OrganizationID,
		arg.Currency,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
