// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: heartbeat.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vivym/vela/internal/execution"
)

const getAttemptProgressForHeartbeat = `-- name: GetAttemptProgressForHeartbeat :one
SELECT
    heartbeat_sequence,
    request_hash,
    execution_phase,
    progress_updated_at
FROM attempt_progress
WHERE attempt_id = $1
FOR UPDATE
`

type GetAttemptProgressForHeartbeatRow struct {
	HeartbeatSequence int64              `db:"heartbeat_sequence" json:"heartbeat_sequence"`
	RequestHash       []byte             `db:"request_hash" json:"request_hash"`
	ExecutionPhase    execution.Phase    `db:"execution_phase" json:"execution_phase"`
	ProgressUpdatedAt pgtype.Timestamptz `db:"progress_updated_at" json:"progress_updated_at"`
}

func (q *Queries) GetAttemptProgressForHeartbeat(ctx context.Context, attemptID uuid.UUID) (GetAttemptProgressForHeartbeatRow, error) {
	row := q.db.QueryRow(ctx, getAttemptProgressForHeartbeat, attemptID)
	var i GetAttemptProgressForHeartbeatRow
	err := row.Scan(
		&i.HeartbeatSequence,
		&i.RequestHash,
		&i.ExecutionPhase,
		&i.ProgressUpdatedAt,
	)
	return i, err
}

const lockExecutionLeaseRenewalProtocol = `-- name: LockExecutionLeaseRenewalProtocol :one
SELECT vela_lock_execution_lease_renewal_protocol()
`

func (q *Queries) LockExecutionLeaseRenewalProtocol(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockExecutionLeaseRenewalProtocol)
	var vela_lock_execution_lease_renewal_protocol bool
	err := row.Scan(&vela_lock_execution_lease_renewal_protocol)
	return vela_lock_execution_lease_renewal_protocol, err
}

const lockExecutionLeaseWrites = `-- name: LockExecutionLeaseWrites :exec
LOCK TABLE attempt_leases IN ROW EXCLUSIVE MODE
`

func (q *Queries) LockExecutionLeaseWrites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockExecutionLeaseWrites)
	return err
}

const lockHeartbeatAuthority = `-- name: LockHeartbeatAuthority :one
SELECT
    l.id AS lease_id,
    l.phase AS lease_phase,
    l.token_digest,
    l.expires_at AS lease_expires_at,
    l.revoked_at AS lease_revoked_at,
    a.id AS attempt_id,
    a.job_id,
    a.state AS attempt_state,
    a.worker_id,
    a.worker_epoch,
    a.fence,
    j.organization_id,
    j.project_id,
    j.state AS job_state,
    j.execution_phase AS job_execution_phase,
    j.version AS job_version,
    j.current_fence,
    j.job_expires_at,
    a.finalization_deadline_at,
    cr.state AS credit_reservation_state
FROM attempt_leases AS l
JOIN attempts AS a ON a.id = l.attempt_id
JOIN jobs AS j ON j.id = a.job_id
JOIN credit_reservations AS cr ON cr.job_id = j.id
WHERE l.attempt_id = $1
  AND l.worker_id = $2
  AND l.worker_epoch = $3
  AND l.fence = $4
  AND l.phase IN ('EXECUTION', 'FINALIZATION')
  AND l.owner_kind = 'WORKER'
  AND l.owner_id = $5
  AND l.revoked_at IS NULL
  AND a.worker_id = $2
  AND a.worker_epoch = $3
  AND a.fence = $4
LIMIT 1
FOR UPDATE OF l, a, j, cr
`

type LockHeartbeatAuthorityParams struct {
	AttemptID   uuid.UUID `db:"attempt_id" json:"attempt_id"`
	WorkerID    uuid.UUID `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64     `db:"worker_epoch" json:"worker_epoch"`
	Fence       int64     `db:"fence" json:"fence"`
	OwnerID     string    `db:"owner_id" json:"owner_id"`
}

type LockHeartbeatAuthorityRow struct {
	LeaseID                uuid.UUID              `db:"lease_id" json:"lease_id"`
	LeasePhase             LeasePhase             `db:"lease_phase" json:"lease_phase"`
	TokenDigest            []byte                 `db:"token_digest" json:"token_digest"`
	LeaseExpiresAt         pgtype.Timestamptz     `db:"lease_expires_at" json:"lease_expires_at"`
	LeaseRevokedAt         pgtype.Timestamptz     `db:"lease_revoked_at" json:"lease_revoked_at"`
	AttemptID              uuid.UUID              `db:"attempt_id" json:"attempt_id"`
	JobID                  uuid.UUID              `db:"job_id" json:"job_id"`
	AttemptState           AttemptState           `db:"attempt_state" json:"attempt_state"`
	WorkerID               uuid.NullUUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch            *int64                 `db:"worker_epoch" json:"worker_epoch"`
	Fence                  int64                  `db:"fence" json:"fence"`
	OrganizationID         uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID              uuid.UUID              `db:"project_id" json:"project_id"`
	JobState               JobState               `db:"job_state" json:"job_state"`
	JobExecutionPhase      *execution.Phase       `db:"job_execution_phase" json:"job_execution_phase"`
	JobVersion             int64                  `db:"job_version" json:"job_version"`
	CurrentFence           int64                  `db:"current_fence" json:"current_fence"`
	JobExpiresAt           pgtype.Timestamptz     `db:"job_expires_at" json:"job_expires_at"`
	FinalizationDeadlineAt pgtype.Timestamptz     `db:"finalization_deadline_at" json:"finalization_deadline_at"`
	CreditReservationState CreditReservationState `db:"credit_reservation_state" json:"credit_reservation_state"`
}

func (q *Queries) LockHeartbeatAuthority(ctx context.Context, arg LockHeartbeatAuthorityParams) (LockHeartbeatAuthorityRow, error) {
	row := q.db.QueryRow(ctx, lockHeartbeatAuthority,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
		arg.OwnerID,
	)
	var i LockHeartbeatAuthorityRow
	err := row.Scan(
		&i.LeaseID,
		&i.LeasePhase,
		&i.TokenDigest,
		&i.LeaseExpiresAt,
		&i.LeaseRevokedAt,
		&i.AttemptID,
		&i.JobID,
		&i.AttemptState,
		&i.WorkerID,
		&i.WorkerEpoch,
		&i.Fence,
		&i.OrganizationID,
		&i.ProjectID,
		&i.JobState,
		&i.JobExecutionPhase,
		&i.JobVersion,
		&i.CurrentFence,
		&i.JobExpiresAt,
		&i.FinalizationDeadlineAt,
		&i.CreditReservationState,
	)
	return i, err
}

const markWorkerHeartbeat = `-- name: MarkWorkerHeartbeat :execrows
UPDATE workers
SET last_heartbeat_at = $1,
    updated_at = $1
WHERE id = $2
  AND epoch = $3
`

type MarkWorkerHeartbeatParams struct {
	HeartbeatAt pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	WorkerID    uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch int64              `db:"worker_epoch" json:"worker_epoch"`
}

func (q *Queries) MarkWorkerHeartbeat(ctx context.Context, arg MarkWorkerHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWorkerHeartbeat, arg.HeartbeatAt, arg.WorkerID, arg.WorkerEpoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewExecutionLease = `-- name: RenewExecutionLease :execrows
UPDATE attempt_leases
SET expires_at = $1,
    updated_at = $2
WHERE id = $3
  AND attempt_id = $4
  AND worker_id = $5
  AND worker_epoch = $6
  AND fence = $7
  AND phase = $8
  AND owner_kind = 'WORKER'
  AND revoked_at IS NULL
  AND expires_at = $9
`

type RenewExecutionLeaseParams struct {
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LeaseID           uuid.UUID          `db:"lease_id" json:"lease_id"`
	AttemptID         uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID          uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch       int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence             int64              `db:"fence" json:"fence"`
	LeasePhase        LeasePhase         `db:"lease_phase" json:"lease_phase"`
	PreviousExpiresAt pgtype.Timestamptz `db:"previous_expires_at" json:"previous_expires_at"`
}

func (q *Queries) RenewExecutionLease(ctx context.Context, arg RenewExecutionLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewExecutionLease,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.LeaseID,
		arg.AttemptID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
		arg.LeasePhase,
		arg.PreviousExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAttemptProgress = `-- name: UpsertAttemptProgress :execrows
INSERT INTO attempt_progress (
    attempt_id,
    organization_id,
    project_id,
    job_id,
    worker_id,
    worker_epoch,
    fence,
    heartbeat_sequence,
    request_hash,
    backend_stage,
    execution_phase,
    phase_progress,
    estimated_remaining_seconds,
    estimated_finish_at,
    gpu_health_summary,
    local_artifact_state,
    scratch_free_bytes,
    artifact_store_reachable,
    progress_updated_at,
    progress_valid_until,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $19
)
ON CONFLICT (attempt_id) DO UPDATE
SET heartbeat_sequence = EXCLUDED.heartbeat_sequence,
    request_hash = EXCLUDED.request_hash,
    backend_stage = EXCLUDED.backend_stage,
    execution_phase = EXCLUDED.execution_phase,
    phase_progress = EXCLUDED.phase_progress,
    estimated_remaining_seconds = EXCLUDED.estimated_remaining_seconds,
    estimated_finish_at = EXCLUDED.estimated_finish_at,
    gpu_health_summary = EXCLUDED.gpu_health_summary,
    local_artifact_state = EXCLUDED.local_artifact_state,
    scratch_free_bytes = EXCLUDED.scratch_free_bytes,
    artifact_store_reachable = EXCLUDED.artifact_store_reachable,
    progress_updated_at = EXCLUDED.progress_updated_at,
    progress_valid_until = EXCLUDED.progress_valid_until,
    updated_at = EXCLUDED.updated_at
WHERE attempt_progress.heartbeat_sequence < EXCLUDED.heartbeat_sequence
`

type UpsertAttemptProgressParams struct {
	AttemptID                 uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	OrganizationID            uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                 uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                     uuid.UUID          `db:"job_id" json:"job_id"`
	WorkerID                  uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch               int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence                     int64              `db:"fence" json:"fence"`
	HeartbeatSequence         int64              `db:"heartbeat_sequence" json:"heartbeat_sequence"`
	RequestHash               []byte             `db:"request_hash" json:"request_hash"`
	BackendStage              string             `db:"backend_stage" json:"backend_stage"`
	ExecutionPhase            execution.Phase    `db:"execution_phase" json:"execution_phase"`
	PhaseProgress             *float64           `db:"phase_progress" json:"phase_progress"`
	EstimatedRemainingSeconds *int64             `db:"estimated_remaining_seconds" json:"estimated_remaining_seconds"`
	EstimatedFinishAt         pgtype.Timestamptz `db:"estimated_finish_at" json:"estimated_finish_at"`
	GpuHealthSummary          []byte             `db:"gpu_health_summary" json:"gpu_health_summary"`
	LocalArtifactState        []byte             `db:"local_artifact_state" json:"local_artifact_state"`
	ScratchFreeBytes          int64              `db:"scratch_free_bytes" json:"scratch_free_bytes"`
	ArtifactStoreReachable    bool               `db:"artifact_store_reachable" json:"artifact_store_reachable"`
	ProgressUpdatedAt         pgtype.Timestamptz `db:"progress_updated_at" json:"progress_updated_at"`
	ProgressValidUntil        pgtype.Timestamptz `db:"progress_valid_until" json:"progress_valid_until"`
}

func (q *Queries) UpsertAttemptProgress(ctx context.Context, arg UpsertAttemptProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAttemptProgress,
		arg.AttemptID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.JobID,
		arg.WorkerID,
		arg.WorkerEpoch,
		arg.Fence,
		arg.HeartbeatSequence,
		arg.RequestHash,
		arg.BackendStage,
		arg.ExecutionPhase,
		arg.PhaseProgress,
		arg.EstimatedRemainingSeconds,
		arg.EstimatedFinishAt,
		arg.GpuHealthSummary,
		arg.LocalArtifactState,
		arg.ScratchFreeBytes,
		arg.ArtifactStoreReachable,
		arg.ProgressUpdatedAt,
		arg.ProgressValidUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
