// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogState string

const (
	CatalogStateREGISTERED CatalogState = "REGISTERED"
	CatalogStateVALIDATING CatalogState = "VALIDATING"
	CatalogStateCERTIFIED  CatalogState = "CERTIFIED"
	CatalogStateCANARY     CatalogState = "CANARY"
	CatalogStateACTIVE     CatalogState = "ACTIVE"
	CatalogStateDRAINING   CatalogState = "DRAINING"
	CatalogStateRETIRED    CatalogState = "RETIRED"
	CatalogStateINVALID    CatalogState = "INVALID"
)

func (e *CatalogState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogState(s)
	case string:
		*e = CatalogState(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogState: %T", src)
	}
	return nil
}

type NullCatalogState struct {
	CatalogState CatalogState `json:"catalog_state"`
	Valid        bool         `json:"valid"` // Valid is true if CatalogState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogState) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogState), nil
}

type CreditReservationState string

const (
	CreditReservationStateRESERVED CreditReservationState = "RESERVED"
	CreditReservationStateCONSUMED CreditReservationState = "CONSUMED"
	CreditReservationStateRELEASED CreditReservationState = "RELEASED"
)

func (e *CreditReservationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditReservationState(s)
	case string:
		*e = CreditReservationState(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditReservationState: %T", src)
	}
	return nil
}

type NullCreditReservationState struct {
	CreditReservationState CreditReservationState `json:"credit_reservation_state"`
	Valid                  bool                   `json:"valid"` // Valid is true if CreditReservationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditReservationState) Scan(value interface{}) error {
	if value == nil {
		ns.CreditReservationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditReservationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditReservationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditReservationState), nil
}

type JobState string

const (
	JobStateQUEUED     JobState = "QUEUED"
	JobStateASSIGNED   JobState = "ASSIGNED"
	JobStateRUNNING    JobState = "RUNNING"
	JobStateFINALIZING JobState = "FINALIZING"
	JobStateRETRYWAIT  JobState = "RETRY_WAIT"
	JobStateCANCELING  JobState = "CANCELING"
	JobStateSUCCEEDED  JobState = "SUCCEEDED"
	JobStateFAILED     JobState = "FAILED"
	JobStateCANCELED   JobState = "CANCELED"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState `json:"job_state"`
	Valid    bool     `json:"valid"` // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type PrincipalKind string

const (
	PrincipalKindHUMAN   PrincipalKind = "HUMAN"
	PrincipalKindSERVICE PrincipalKind = "SERVICE"
)

func (e *PrincipalKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalKind(s)
	case string:
		*e = PrincipalKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalKind: %T", src)
	}
	return nil
}

type NullPrincipalKind struct {
	PrincipalKind PrincipalKind `json:"principal_kind"`
	Valid         bool          `json:"valid"` // Valid is true if PrincipalKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalKind) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalKind), nil
}

type Credential struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	OrganizationID       uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID            uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID          uuid.UUID          `db:"principal_id" json:"principal_id"`
	SecretDigest         []byte             `db:"secret_digest" json:"secret_digest"`
	Scopes               []string           `db:"scopes" json:"scopes"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedByPrincipalID uuid.UUID          `db:"created_by_principal_id" json:"created_by_principal_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CreditReservation struct {
	ID             uuid.UUID              `db:"id" json:"id"`
	OrganizationID uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID              `db:"project_id" json:"project_id"`
	JobID          uuid.UUID              `db:"job_id" json:"job_id"`
	AmountMinor    int64                  `db:"amount_minor" json:"amount_minor"`
	Currency       string                 `db:"currency" json:"currency"`
	State          CreditReservationState `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
}

type CustomerOrganization struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ExecutionProfileRevision struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ModelRevisionID uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	WorkerPoolID    uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	StableID        string             `db:"stable_id" json:"stable_id"`
	Revision        int32              `db:"revision" json:"revision"`
	State           CatalogState       `db:"state" json:"state"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GenerationPresetRevision struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	ModelRevisionID            uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	StableID                   string             `db:"stable_id" json:"stable_id"`
	Revision                   int32              `db:"revision" json:"revision"`
	State                      CatalogState       `db:"state" json:"state"`
	CertifiedP95ComputeSeconds int32              `db:"certified_p95_compute_seconds" json:"certified_p95_compute_seconds"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type IdempotencyResult struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    []byte             `db:"request_hash" json:"request_hash"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InboxReceipt struct {
	ConsumerName     string             `db:"consumer_name" json:"consumer_name"`
	EventID          uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	AggregateType    string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID      uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateVersion int64              `db:"aggregate_version" json:"aggregate_version"`
	EventType        string             `db:"event_type" json:"event_type"`
	ConsumedAt       pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type Job struct {
	ID                                        uuid.UUID          `db:"id" json:"id"`
	OrganizationID                            uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                                 uuid.UUID          `db:"project_id" json:"project_id"`
	CreatedByPrincipalID                      uuid.UUID          `db:"created_by_principal_id" json:"created_by_principal_id"`
	State                                     JobState           `db:"state" json:"state"`
	Version                                   int64              `db:"version" json:"version"`
	ModelRevisionID                           uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID                uuid.UUID          `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	ServiceClassRevisionID                    uuid.UUID          `db:"service_class_revision_id" json:"service_class_revision_id"`
	OutputSpecID                              uuid.UUID          `db:"output_spec_id" json:"output_spec_id"`
	WorkerPoolID                              uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	RequestHash                               []byte             `db:"request_hash" json:"request_hash"`
	RequestContent                            []byte             `db:"request_content" json:"request_content"`
	RequestContentExpiresAt                   pgtype.Timestamptz `db:"request_content_expires_at" json:"request_content_expires_at"`
	PricingRateCardRevisionID                 uuid.UUID          `db:"pricing_rate_card_revision_id" json:"pricing_rate_card_revision_id"`
	PricingRateLineID                         uuid.UUID          `db:"pricing_rate_line_id" json:"pricing_rate_line_id"`
	PricingUnitAmountMinor                    int64              `db:"pricing_unit_amount_minor" json:"pricing_unit_amount_minor"`
	PricingQuantity                           int32              `db:"pricing_quantity" json:"pricing_quantity"`
	PricingQuotedAmountMinor                  int64              `db:"pricing_quoted_amount_minor" json:"pricing_quoted_amount_minor"`
	PricingCurrency                           string             `db:"pricing_currency" json:"pricing_currency"`
	ExecutionMaxAttempts                      int32              `db:"execution_max_attempts" json:"execution_max_attempts"`
	ExecutionMaxTotalComputeSeconds           int64              `db:"execution_max_total_compute_seconds" json:"execution_max_total_compute_seconds"`
	ExecutionMaxFinalizationSecondsPerAttempt int32              `db:"execution_max_finalization_seconds_per_attempt" json:"execution_max_finalization_seconds_per_attempt"`
	ExecutionRetryBackoffPolicy               []byte             `db:"execution_retry_backoff_policy" json:"execution_retry_backoff_policy"`
	ExecutionRetryableFailureClasses          []string           `db:"execution_retryable_failure_classes" json:"execution_retryable_failure_classes"`
	ExecutionCircuitBreakerPolicy             []byte             `db:"execution_circuit_breaker_policy" json:"execution_circuit_breaker_policy"`
	JobExpiresAt                              pgtype.Timestamptz `db:"job_expires_at" json:"job_expires_at"`
	CreatedAt                                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ModelRevision struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	StableID    string             `db:"stable_id" json:"stable_id"`
	Revision    int32              `db:"revision" json:"revision"`
	State       CatalogState       `db:"state" json:"state"`
	ContentHash string             `db:"content_hash" json:"content_hash"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OrganizationCreditAccount struct {
	OrganizationID           uuid.UUID          `db:"organization_id" json:"organization_id"`
	Currency                 string             `db:"currency" json:"currency"`
	ContractCreditLimitMinor int64              `db:"contract_credit_limit_minor" json:"contract_credit_limit_minor"`
	ReservedMinor            int64              `db:"reserved_minor" json:"reserved_minor"`
	UnsettledPostedMinor     int64              `db:"unsettled_posted_minor" json:"unsettled_posted_minor"`
	Version                  int64              `db:"version" json:"version"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OutboxEvent struct {
	EventID          uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	AggregateType    string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID      uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateVersion int64              `db:"aggregate_version" json:"aggregate_version"`
	EventType        string             `db:"event_type" json:"event_type"`
	SchemaVersion    int32              `db:"schema_version" json:"schema_version"`
	Payload          []byte             `db:"payload" json:"payload"`
	OccurredAt       pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	AvailableAt      pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishAttempts  int32              `db:"publish_attempts" json:"publish_attempts"`
	ClaimedBy        *string            `db:"claimed_by" json:"claimed_by"`
	ClaimToken       uuid.NullUUID      `db:"claim_token" json:"claim_token"`
	ClaimExpiresAt   pgtype.Timestamptz `db:"claim_expires_at" json:"claim_expires_at"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	BrokerStream     *string            `db:"broker_stream" json:"broker_stream"`
	BrokerSequence   *int64             `db:"broker_sequence" json:"broker_sequence"`
	LastError        *string            `db:"last_error" json:"last_error"`
}

type OutputSpec struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	StableID             string             `db:"stable_id" json:"stable_id"`
	Revision             int32              `db:"revision" json:"revision"`
	State                CatalogState       `db:"state" json:"state"`
	Width                int32              `db:"width" json:"width"`
	Height               int32              `db:"height" json:"height"`
	DurationMilliseconds int32              `db:"duration_milliseconds" json:"duration_milliseconds"`
	FrameRateMilli       int32              `db:"frame_rate_milli" json:"frame_rate_milli"`
	Codec                string             `db:"codec" json:"codec"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Principal struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Kind           PrincipalKind      `db:"kind" json:"kind"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProfileCertification struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	ModelRevisionID            uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID uuid.UUID          `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	OutputSpecID               uuid.UUID          `db:"output_spec_id" json:"output_spec_id"`
	ExecutionProfileRevisionID uuid.UUID          `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	State                      CatalogState       `db:"state" json:"state"`
	EvidenceDigest             string             `db:"evidence_digest" json:"evidence_digest"`
	CertifiedAt                pgtype.Timestamptz `db:"certified_at" json:"certified_at"`
	InvalidatedAt              pgtype.Timestamptz `db:"invalidated_at" json:"invalidated_at"`
}

type Project struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	QueuedLimit       int32              `db:"queued_limit" json:"queued_limit"`
	QueuedCount       int32              `db:"queued_count" json:"queued_count"`
	RunningLimit      int32              `db:"running_limit" json:"running_limit"`
	RunningCount      int32              `db:"running_count" json:"running_count"`
	RetryAfterSeconds int32              `db:"retry_after_seconds" json:"retry_after_seconds"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RateCardLine struct {
	ID                         uuid.UUID `db:"id" json:"id"`
	RateCardRevisionID         uuid.UUID `db:"rate_card_revision_id" json:"rate_card_revision_id"`
	ModelRevisionID            uuid.UUID `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID uuid.UUID `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	ServiceClassRevisionID     uuid.UUID `db:"service_class_revision_id" json:"service_class_revision_id"`
	OutputSpecID               uuid.UUID `db:"output_spec_id" json:"output_spec_id"`
	UnitAmountMinor            int64     `db:"unit_amount_minor" json:"unit_amount_minor"`
	Currency                   string    `db:"currency" json:"currency"`
}

type RateCardRevision struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Revision    int32              `db:"revision" json:"revision"`
	State       CatalogState       `db:"state" json:"state"`
	EffectiveAt pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RetryRuntimeState struct {
	JobID                       uuid.UUID          `db:"job_id" json:"job_id"`
	OrganizationID              uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                   uuid.UUID          `db:"project_id" json:"project_id"`
	AttemptsStarted             int32              `db:"attempts_started" json:"attempts_started"`
	ComputeSecondsConsumed      int64              `db:"compute_seconds_consumed" json:"compute_seconds_consumed"`
	FinalizationSecondsConsumed int64              `db:"finalization_seconds_consumed" json:"finalization_seconds_consumed"`
	FinalizationRetryCount      int32              `db:"finalization_retry_count" json:"finalization_retry_count"`
	NextRetryAt                 pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	ExcludedWorkers             []byte             `db:"excluded_workers" json:"excluded_workers"`
	FailureFingerprints         []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	CircuitBreakerState         []byte             `db:"circuit_breaker_state" json:"circuit_breaker_state"`
	LastFailureClass            *string            `db:"last_failure_class" json:"last_failure_class"`
	Version                     int64              `db:"version" json:"version"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ServiceClassRevision struct {
	ID                               uuid.UUID          `db:"id" json:"id"`
	StableID                         string             `db:"stable_id" json:"stable_id"`
	Revision                         int32              `db:"revision" json:"revision"`
	State                            CatalogState       `db:"state" json:"state"`
	QueueRetryAllowanceSeconds       int32              `db:"queue_retry_allowance_seconds" json:"queue_retry_allowance_seconds"`
	MaxAttempts                      int32              `db:"max_attempts" json:"max_attempts"`
	MaxTotalComputeMultiplierMilli   int32              `db:"max_total_compute_multiplier_milli" json:"max_total_compute_multiplier_milli"`
	MaxFinalizationSecondsPerAttempt int32              `db:"max_finalization_seconds_per_attempt" json:"max_finalization_seconds_per_attempt"`
	RetryBackoffPolicy               []byte             `db:"retry_backoff_policy" json:"retry_backoff_policy"`
	RetryableFailureClasses          []string           `db:"retryable_failure_classes" json:"retryable_failure_classes"`
	CircuitBreakerPolicy             []byte             `db:"circuit_breaker_policy" json:"circuit_breaker_policy"`
	CreatedAt                        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ServicePrincipal struct {
	PrincipalID    uuid.UUID          `db:"principal_id" json:"principal_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalKind  PrincipalKind      `db:"principal_kind" json:"principal_kind"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VelaPrivateRequestContext struct {
	BackendPid     int32              `db:"backend_pid" json:"backend_pid"`
	TransactionID  pgtype.Uint64      `db:"transaction_id" json:"transaction_id"`
	CredentialID   uuid.UUID          `db:"credential_id" json:"credential_id"`
	RequiredScope  string             `db:"required_scope" json:"required_scope"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID    uuid.UUID          `db:"principal_id" json:"principal_id"`
	EstablishedAt  pgtype.Timestamptz `db:"established_at" json:"established_at"`
}

type WorkerPool struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	StableID          string             `db:"stable_id" json:"stable_id"`
	AdmissionOpen     bool               `db:"admission_open" json:"admission_open"`
	QueuedLimit       int32              `db:"queued_limit" json:"queued_limit"`
	QueuedCount       int32              `db:"queued_count" json:"queued_count"`
	RetryAfterSeconds int32              `db:"retry_after_seconds" json:"retry_after_seconds"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
