// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/vivym/vela/internal/execution"
)

type ArtifactKind string

const (
	ArtifactKindVIDEO     ArtifactKind = "VIDEO"
	ArtifactKindTHUMBNAIL ArtifactKind = "THUMBNAIL"
)

func (e *ArtifactKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactKind(s)
	case string:
		*e = ArtifactKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactKind: %T", src)
	}
	return nil
}

type NullArtifactKind struct {
	ArtifactKind ArtifactKind `json:"artifact_kind"`
	Valid        bool         `json:"valid"` // Valid is true if ArtifactKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactKind) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactKind), nil
}

type ArtifactState string

const (
	ArtifactStateSTAGING   ArtifactState = "STAGING"
	ArtifactStateUPLOADED  ArtifactState = "UPLOADED"
	ArtifactStateVERIFIED  ArtifactState = "VERIFIED"
	ArtifactStateCOMMITTED ArtifactState = "COMMITTED"
	ArtifactStateEXPIRED   ArtifactState = "EXPIRED"
	ArtifactStateDELETED   ArtifactState = "DELETED"
)

func (e *ArtifactState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactState(s)
	case string:
		*e = ArtifactState(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactState: %T", src)
	}
	return nil
}

type NullArtifactState struct {
	ArtifactState ArtifactState `json:"artifact_state"`
	Valid         bool          `json:"valid"` // Valid is true if ArtifactState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactState) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactState), nil
}

type ArtifactUploadState string

const (
	ArtifactUploadStateINITIATED ArtifactUploadState = "INITIATED"
	ArtifactUploadStateUPLOADING ArtifactUploadState = "UPLOADING"
	ArtifactUploadStateUPLOADED  ArtifactUploadState = "UPLOADED"
	ArtifactUploadStateVERIFIED  ArtifactUploadState = "VERIFIED"
	ArtifactUploadStateABORTED   ArtifactUploadState = "ABORTED"
	ArtifactUploadStateEXPIRED   ArtifactUploadState = "EXPIRED"
)

func (e *ArtifactUploadState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactUploadState(s)
	case string:
		*e = ArtifactUploadState(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactUploadState: %T", src)
	}
	return nil
}

type NullArtifactUploadState struct {
	ArtifactUploadState ArtifactUploadState `json:"artifact_upload_state"`
	Valid               bool                `json:"valid"` // Valid is true if ArtifactUploadState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactUploadState) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactUploadState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactUploadState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactUploadState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactUploadState), nil
}

type AttemptState string

const (
	AttemptStateASSIGNED   AttemptState = "ASSIGNED"
	AttemptStateRUNNING    AttemptState = "RUNNING"
	AttemptStateFINALIZING AttemptState = "FINALIZING"
	AttemptStateSUCCEEDED  AttemptState = "SUCCEEDED"
	AttemptStateFAILED     AttemptState = "FAILED"
	AttemptStateLOST       AttemptState = "LOST"
	AttemptStateCANCELED   AttemptState = "CANCELED"
)

func (e *AttemptState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttemptState(s)
	case string:
		*e = AttemptState(s)
	default:
		return fmt.Errorf("unsupported scan type for AttemptState: %T", src)
	}
	return nil
}

type NullAttemptState struct {
	AttemptState AttemptState `json:"attempt_state"`
	Valid        bool         `json:"valid"` // Valid is true if AttemptState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttemptState) Scan(value interface{}) error {
	if value == nil {
		ns.AttemptState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttemptState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttemptState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttemptState), nil
}

type CancellationDecision string

const (
	CancellationDecisionCANCELED         CancellationDecision = "CANCELED"
	CancellationDecisionCANCELING        CancellationDecision = "CANCELING"
	CancellationDecisionALREADYSUCCEEDED CancellationDecision = "ALREADY_SUCCEEDED"
	CancellationDecisionALREADYFAILED    CancellationDecision = "ALREADY_FAILED"
)

func (e *CancellationDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CancellationDecision(s)
	case string:
		*e = CancellationDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for CancellationDecision: %T", src)
	}
	return nil
}

type NullCancellationDecision struct {
	CancellationDecision CancellationDecision `json:"cancellation_decision"`
	Valid                bool                 `json:"valid"` // Valid is true if CancellationDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCancellationDecision) Scan(value interface{}) error {
	if value == nil {
		ns.CancellationDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CancellationDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCancellationDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CancellationDecision), nil
}

type CancellationStopSource string

const (
	CancellationStopSourceACKNOWLEDGED               CancellationStopSource = "ACKNOWLEDGED"
	CancellationStopSourceLEASEEXPIREDRECONCILIATION CancellationStopSource = "LEASE_EXPIRED_RECONCILIATION"
)

func (e *CancellationStopSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CancellationStopSource(s)
	case string:
		*e = CancellationStopSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CancellationStopSource: %T", src)
	}
	return nil
}

type NullCancellationStopSource struct {
	CancellationStopSource CancellationStopSource `json:"cancellation_stop_source"`
	Valid                  bool                   `json:"valid"` // Valid is true if CancellationStopSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCancellationStopSource) Scan(value interface{}) error {
	if value == nil {
		ns.CancellationStopSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CancellationStopSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCancellationStopSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CancellationStopSource), nil
}

type CatalogState string

const (
	CatalogStateREGISTERED CatalogState = "REGISTERED"
	CatalogStateVALIDATING CatalogState = "VALIDATING"
	CatalogStateCERTIFIED  CatalogState = "CERTIFIED"
	CatalogStateCANARY     CatalogState = "CANARY"
	CatalogStateACTIVE     CatalogState = "ACTIVE"
	CatalogStateDRAINING   CatalogState = "DRAINING"
	CatalogStateRETIRED    CatalogState = "RETIRED"
	CatalogStateINVALID    CatalogState = "INVALID"
)

func (e *CatalogState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CatalogState(s)
	case string:
		*e = CatalogState(s)
	default:
		return fmt.Errorf("unsupported scan type for CatalogState: %T", src)
	}
	return nil
}

type NullCatalogState struct {
	CatalogState CatalogState `json:"catalog_state"`
	Valid        bool         `json:"valid"` // Valid is true if CatalogState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCatalogState) Scan(value interface{}) error {
	if value == nil {
		ns.CatalogState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CatalogState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCatalogState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CatalogState), nil
}

type ChargeReason string

const (
	ChargeReasonVISIBLECOMPLETION    ChargeReason = "VISIBLE_COMPLETION"
	ChargeReasonCUSTOMERCANCELLATION ChargeReason = "CUSTOMER_CANCELLATION"
)

func (e *ChargeReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChargeReason(s)
	case string:
		*e = ChargeReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ChargeReason: %T", src)
	}
	return nil
}

type NullChargeReason struct {
	ChargeReason ChargeReason `json:"charge_reason"`
	Valid        bool         `json:"valid"` // Valid is true if ChargeReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChargeReason) Scan(value interface{}) error {
	if value == nil {
		ns.ChargeReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChargeReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChargeReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChargeReason), nil
}

type CreditReservationState string

const (
	CreditReservationStateRESERVED CreditReservationState = "RESERVED"
	CreditReservationStateCONSUMED CreditReservationState = "CONSUMED"
	CreditReservationStateRELEASED CreditReservationState = "RELEASED"
)

func (e *CreditReservationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditReservationState(s)
	case string:
		*e = CreditReservationState(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditReservationState: %T", src)
	}
	return nil
}

type NullCreditReservationState struct {
	CreditReservationState CreditReservationState `json:"credit_reservation_state"`
	Valid                  bool                   `json:"valid"` // Valid is true if CreditReservationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditReservationState) Scan(value interface{}) error {
	if value == nil {
		ns.CreditReservationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditReservationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditReservationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditReservationState), nil
}

type ExecutionFailureSource string

const (
	ExecutionFailureSourceWORKERREPORTED                ExecutionFailureSource = "WORKER_REPORTED"
	ExecutionFailureSourceEXECUTIONLEASEEXPIRED         ExecutionFailureSource = "EXECUTION_LEASE_EXPIRED"
	ExecutionFailureSourceJOBEXPIRED                    ExecutionFailureSource = "JOB_EXPIRED"
	ExecutionFailureSourceFINALIZATIONDEADLINEEXPIRED   ExecutionFailureSource = "FINALIZATION_DEADLINE_EXPIRED"
	ExecutionFailureSourceARTIFACTRECOVERYUNRECOVERABLE ExecutionFailureSource = "ARTIFACT_RECOVERY_UNRECOVERABLE"
)

func (e *ExecutionFailureSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionFailureSource(s)
	case string:
		*e = ExecutionFailureSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionFailureSource: %T", src)
	}
	return nil
}

type NullExecutionFailureSource struct {
	ExecutionFailureSource ExecutionFailureSource `json:"execution_failure_source"`
	Valid                  bool                   `json:"valid"` // Valid is true if ExecutionFailureSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionFailureSource) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionFailureSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionFailureSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionFailureSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionFailureSource), nil
}

type ExecutionPhase string

const (
	ExecutionPhaseQUEUED     ExecutionPhase = "QUEUED"
	ExecutionPhasePREPARING  ExecutionPhase = "PREPARING"
	ExecutionPhaseGENERATING ExecutionPhase = "GENERATING"
	ExecutionPhaseFINALIZING ExecutionPhase = "FINALIZING"
	ExecutionPhaseRETRYWAIT  ExecutionPhase = "RETRY_WAIT"
)

func (e *ExecutionPhase) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionPhase(s)
	case string:
		*e = ExecutionPhase(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionPhase: %T", src)
	}
	return nil
}

type NullExecutionPhase struct {
	ExecutionPhase ExecutionPhase `json:"execution_phase"`
	Valid          bool           `json:"valid"` // Valid is true if ExecutionPhase is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionPhase) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionPhase, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionPhase.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionPhase) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionPhase), nil
}

type InvoiceExportState string

const (
	InvoiceExportStatePENDING  InvoiceExportState = "PENDING"
	InvoiceExportStateCLAIMED  InvoiceExportState = "CLAIMED"
	InvoiceExportStateEXPORTED InvoiceExportState = "EXPORTED"
)

func (e *InvoiceExportState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceExportState(s)
	case string:
		*e = InvoiceExportState(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceExportState: %T", src)
	}
	return nil
}

type NullInvoiceExportState struct {
	InvoiceExportState InvoiceExportState `json:"invoice_export_state"`
	Valid              bool               `json:"valid"` // Valid is true if InvoiceExportState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceExportState) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceExportState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceExportState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceExportState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceExportState), nil
}

type JobState string

const (
	JobStateQUEUED     JobState = "QUEUED"
	JobStateASSIGNED   JobState = "ASSIGNED"
	JobStateRUNNING    JobState = "RUNNING"
	JobStateFINALIZING JobState = "FINALIZING"
	JobStateRETRYWAIT  JobState = "RETRY_WAIT"
	JobStateCANCELING  JobState = "CANCELING"
	JobStateSUCCEEDED  JobState = "SUCCEEDED"
	JobStateFAILED     JobState = "FAILED"
	JobStateCANCELED   JobState = "CANCELED"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState `json:"job_state"`
	Valid    bool     `json:"valid"` // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type LeaseOwnerKind string

const (
	LeaseOwnerKindWORKER     LeaseOwnerKind = "WORKER"
	LeaseOwnerKindRECONCILER LeaseOwnerKind = "RECONCILER"
)

func (e *LeaseOwnerKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaseOwnerKind(s)
	case string:
		*e = LeaseOwnerKind(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaseOwnerKind: %T", src)
	}
	return nil
}

type NullLeaseOwnerKind struct {
	LeaseOwnerKind LeaseOwnerKind `json:"lease_owner_kind"`
	Valid          bool           `json:"valid"` // Valid is true if LeaseOwnerKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaseOwnerKind) Scan(value interface{}) error {
	if value == nil {
		ns.LeaseOwnerKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaseOwnerKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaseOwnerKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaseOwnerKind), nil
}

type LeasePhase string

const (
	LeasePhaseEXECUTION    LeasePhase = "EXECUTION"
	LeasePhaseFINALIZATION LeasePhase = "FINALIZATION"
)

func (e *LeasePhase) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeasePhase(s)
	case string:
		*e = LeasePhase(s)
	default:
		return fmt.Errorf("unsupported scan type for LeasePhase: %T", src)
	}
	return nil
}

type NullLeasePhase struct {
	LeasePhase LeasePhase `json:"lease_phase"`
	Valid      bool       `json:"valid"` // Valid is true if LeasePhase is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeasePhase) Scan(value interface{}) error {
	if value == nil {
		ns.LeasePhase, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeasePhase.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeasePhase) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeasePhase), nil
}

type PrincipalKind string

const (
	PrincipalKindHUMAN   PrincipalKind = "HUMAN"
	PrincipalKindSERVICE PrincipalKind = "SERVICE"
)

func (e *PrincipalKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalKind(s)
	case string:
		*e = PrincipalKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalKind: %T", src)
	}
	return nil
}

type NullPrincipalKind struct {
	PrincipalKind PrincipalKind `json:"principal_kind"`
	Valid         bool          `json:"valid"` // Valid is true if PrincipalKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalKind) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalKind), nil
}

type RetryDisposition string

const (
	RetryDispositionRETRYWAIT RetryDisposition = "RETRY_WAIT"
	RetryDispositionFAILED    RetryDisposition = "FAILED"
)

func (e *RetryDisposition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetryDisposition(s)
	case string:
		*e = RetryDisposition(s)
	default:
		return fmt.Errorf("unsupported scan type for RetryDisposition: %T", src)
	}
	return nil
}

type NullRetryDisposition struct {
	RetryDisposition RetryDisposition `json:"retry_disposition"`
	Valid            bool             `json:"valid"` // Valid is true if RetryDisposition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetryDisposition) Scan(value interface{}) error {
	if value == nil {
		ns.RetryDisposition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetryDisposition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetryDisposition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetryDisposition), nil
}

type SchedulerDispatchState string

const (
	SchedulerDispatchStateCLAIMED   SchedulerDispatchState = "CLAIMED"
	SchedulerDispatchStateCOMMITTED SchedulerDispatchState = "COMMITTED"
	SchedulerDispatchStateABANDONED SchedulerDispatchState = "ABANDONED"
)

func (e *SchedulerDispatchState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulerDispatchState(s)
	case string:
		*e = SchedulerDispatchState(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulerDispatchState: %T", src)
	}
	return nil
}

type NullSchedulerDispatchState struct {
	SchedulerDispatchState SchedulerDispatchState `json:"scheduler_dispatch_state"`
	Valid                  bool                   `json:"valid"` // Valid is true if SchedulerDispatchState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulerDispatchState) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulerDispatchState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulerDispatchState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulerDispatchState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulerDispatchState), nil
}

type SchedulerLane string

const (
	SchedulerLaneRETRY     SchedulerLane = "RETRY"
	SchedulerLanePROTECTED SchedulerLane = "PROTECTED"
	SchedulerLaneNORMAL    SchedulerLane = "NORMAL"
)

func (e *SchedulerLane) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulerLane(s)
	case string:
		*e = SchedulerLane(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulerLane: %T", src)
	}
	return nil
}

type NullSchedulerLane struct {
	SchedulerLane SchedulerLane `json:"scheduler_lane"`
	Valid         bool          `json:"valid"` // Valid is true if SchedulerLane is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulerLane) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulerLane, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulerLane.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulerLane) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulerLane), nil
}

type WorkerLifecycleState string

const (
	WorkerLifecycleStateREGISTERING WorkerLifecycleState = "REGISTERING"
	WorkerLifecycleStateWARMING     WorkerLifecycleState = "WARMING"
	WorkerLifecycleStateREADY       WorkerLifecycleState = "READY"
	WorkerLifecycleStateBUSY        WorkerLifecycleState = "BUSY"
	WorkerLifecycleStateDRAINING    WorkerLifecycleState = "DRAINING"
	WorkerLifecycleStateRECOVERING  WorkerLifecycleState = "RECOVERING"
	WorkerLifecycleStateQUARANTINED WorkerLifecycleState = "QUARANTINED"
)

func (e *WorkerLifecycleState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerLifecycleState(s)
	case string:
		*e = WorkerLifecycleState(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerLifecycleState: %T", src)
	}
	return nil
}

type NullWorkerLifecycleState struct {
	WorkerLifecycleState WorkerLifecycleState `json:"worker_lifecycle_state"`
	Valid                bool                 `json:"valid"` // Valid is true if WorkerLifecycleState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerLifecycleState) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerLifecycleState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerLifecycleState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerLifecycleState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerLifecycleState), nil
}

type WorkerProfileReadinessState string

const (
	WorkerProfileReadinessStateWARM           WorkerProfileReadinessState = "WARM"
	WorkerProfileReadinessStatePREWARMALLOWED WorkerProfileReadinessState = "PREWARM_ALLOWED"
)

func (e *WorkerProfileReadinessState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerProfileReadinessState(s)
	case string:
		*e = WorkerProfileReadinessState(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerProfileReadinessState: %T", src)
	}
	return nil
}

type NullWorkerProfileReadinessState struct {
	WorkerProfileReadinessState WorkerProfileReadinessState `json:"worker_profile_readiness_state"`
	Valid                       bool                        `json:"valid"` // Valid is true if WorkerProfileReadinessState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerProfileReadinessState) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerProfileReadinessState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerProfileReadinessState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerProfileReadinessState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerProfileReadinessState), nil
}

type WorkerReachabilityCondition string

const (
	WorkerReachabilityConditionHEALTHY WorkerReachabilityCondition = "HEALTHY"
	WorkerReachabilityConditionSUSPECT WorkerReachabilityCondition = "SUSPECT"
	WorkerReachabilityConditionOFFLINE WorkerReachabilityCondition = "OFFLINE"
)

func (e *WorkerReachabilityCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkerReachabilityCondition(s)
	case string:
		*e = WorkerReachabilityCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkerReachabilityCondition: %T", src)
	}
	return nil
}

type NullWorkerReachabilityCondition struct {
	WorkerReachabilityCondition WorkerReachabilityCondition `json:"worker_reachability_condition"`
	Valid                       bool                        `json:"valid"` // Valid is true if WorkerReachabilityCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkerReachabilityCondition) Scan(value interface{}) error {
	if value == nil {
		ns.WorkerReachabilityCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkerReachabilityCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkerReachabilityCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkerReachabilityCondition), nil
}

type Artifact struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	OrganizationID          uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID               uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence            int64              `db:"attempt_fence" json:"attempt_fence"`
	Kind                    ArtifactKind       `db:"kind" json:"kind"`
	Ordinal                 int32              `db:"ordinal" json:"ordinal"`
	ObjectKey               string             `db:"object_key" json:"object_key"`
	ExpectedContentType     string             `db:"expected_content_type" json:"expected_content_type"`
	ObjectVersionID         *string            `db:"object_version_id" json:"object_version_id"`
	SizeBytes               *int64             `db:"size_bytes" json:"size_bytes"`
	Sha256                  []byte             `db:"sha256" json:"sha256"`
	ContentType             *string            `db:"content_type" json:"content_type"`
	UploadedAt              pgtype.Timestamptz `db:"uploaded_at" json:"uploaded_at"`
	VerificationID          uuid.NullUUID      `db:"verification_id" json:"verification_id"`
	VerificationRequestHash []byte             `db:"verification_request_hash" json:"verification_request_hash"`
	ValidationReceipt       []byte             `db:"validation_receipt" json:"validation_receipt"`
	VerifiedAt              pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	RetentionExpiresAt      pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	State                   ArtifactState      `db:"state" json:"state"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ArtifactAccessGrant struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	OrganizationID     uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID          uuid.UUID          `db:"project_id" json:"project_id"`
	JobID              uuid.UUID          `db:"job_id" json:"job_id"`
	ArtifactSetID      uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	EligibleAt         pgtype.Timestamptz `db:"eligible_at" json:"eligible_at"`
	RetentionExpiresAt pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	RevokedAt          pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ArtifactSet struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	OrganizationID          uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID               uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence            int64              `db:"attempt_fence" json:"attempt_fence"`
	ManifestSha256          []byte             `db:"manifest_sha256" json:"manifest_sha256"`
	RetentionPolicyRevision string             `db:"retention_policy_revision" json:"retention_policy_revision"`
	RetentionExpiresAt      pgtype.Timestamptz `db:"retention_expires_at" json:"retention_expires_at"`
	CommittedAt             pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ArtifactSetItem struct {
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID         uuid.UUID          `db:"project_id" json:"project_id"`
	JobID             uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID         uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence      int64              `db:"attempt_fence" json:"attempt_fence"`
	ArtifactSetID     uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	ArtifactID        uuid.UUID          `db:"artifact_id" json:"artifact_id"`
	Kind              ArtifactKind       `db:"kind" json:"kind"`
	Ordinal           int32              `db:"ordinal" json:"ordinal"`
	ObjectKey         string             `db:"object_key" json:"object_key"`
	ObjectVersionID   string             `db:"object_version_id" json:"object_version_id"`
	SizeBytes         int64              `db:"size_bytes" json:"size_bytes"`
	Sha256            []byte             `db:"sha256" json:"sha256"`
	ContentType       string             `db:"content_type" json:"content_type"`
	ValidationReceipt []byte             `db:"validation_receipt" json:"validation_receipt"`
	VerifiedAt        pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ArtifactUpload struct {
	ID                      uuid.UUID           `db:"id" json:"id"`
	OrganizationID          uuid.UUID           `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID           `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID           `db:"job_id" json:"job_id"`
	AttemptID               uuid.UUID           `db:"attempt_id" json:"attempt_id"`
	AttemptFence            int64               `db:"attempt_fence" json:"attempt_fence"`
	ArtifactID              uuid.UUID           `db:"artifact_id" json:"artifact_id"`
	State                   ArtifactUploadState `db:"state" json:"state"`
	MultipartUploadID       *string             `db:"multipart_upload_id" json:"multipart_upload_id"`
	CompletedParts          []byte              `db:"completed_parts" json:"completed_parts"`
	ObjectVersionID         *string             `db:"object_version_id" json:"object_version_id"`
	SizeBytes               *int64              `db:"size_bytes" json:"size_bytes"`
	Sha256                  []byte              `db:"sha256" json:"sha256"`
	ContentType             *string             `db:"content_type" json:"content_type"`
	CompletionRequestHash   []byte              `db:"completion_request_hash" json:"completion_request_hash"`
	UploadedAt              pgtype.Timestamptz  `db:"uploaded_at" json:"uploaded_at"`
	VerificationID          uuid.NullUUID       `db:"verification_id" json:"verification_id"`
	VerificationRequestHash []byte              `db:"verification_request_hash" json:"verification_request_hash"`
	ValidationReceipt       []byte              `db:"validation_receipt" json:"validation_receipt"`
	VerifiedAt              pgtype.Timestamptz  `db:"verified_at" json:"verified_at"`
	RetryCount              int32               `db:"retry_count" json:"retry_count"`
	NextRetryAt             pgtype.Timestamptz  `db:"next_retry_at" json:"next_retry_at"`
	ClaimID                 uuid.NullUUID       `db:"claim_id" json:"claim_id"`
	ClaimOwnerKind          *LeaseOwnerKind     `db:"claim_owner_kind" json:"claim_owner_kind"`
	ClaimOwnerID            *string             `db:"claim_owner_id" json:"claim_owner_id"`
	ClaimExpiresAt          pgtype.Timestamptz  `db:"claim_expires_at" json:"claim_expires_at"`
	ExpiresAt               pgtype.Timestamptz  `db:"expires_at" json:"expires_at"`
	Version                 int64               `db:"version" json:"version"`
	CreatedAt               pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}

type Attempt struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	OrganizationID             uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                  uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                      uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptNumber              int32              `db:"attempt_number" json:"attempt_number"`
	ExecutionProfileRevisionID uuid.UUID          `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	WorkerPoolID               uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	WorkerID                   uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch                int64              `db:"worker_epoch" json:"worker_epoch"`
	State                      AttemptState       `db:"state" json:"state"`
	Fence                      int64              `db:"fence" json:"fence"`
	AssignedAt                 pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	StartedAt                  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinalizationStartedAt      pgtype.Timestamptz `db:"finalization_started_at" json:"finalization_started_at"`
	FinalizationDeadlineAt     pgtype.Timestamptz `db:"finalization_deadline_at" json:"finalization_deadline_at"`
	EndedAt                    pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SchedulerDispatchIntentID  uuid.NullUUID      `db:"scheduler_dispatch_intent_id" json:"scheduler_dispatch_intent_id"`
}

type AttemptLease struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID              uuid.UUID          `db:"project_id" json:"project_id"`
	AttemptID              uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID               uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch            int64              `db:"worker_epoch" json:"worker_epoch"`
	Phase                  LeasePhase         `db:"phase" json:"phase"`
	OwnerKind              LeaseOwnerKind     `db:"owner_kind" json:"owner_kind"`
	OwnerID                string             `db:"owner_id" json:"owner_id"`
	Fence                  int64              `db:"fence" json:"fence"`
	TokenDigest            []byte             `db:"token_digest" json:"token_digest"`
	SigningKeyID           string             `db:"signing_key_id" json:"signing_key_id"`
	IssuedAt               pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt              pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt              pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TokenClaimExpiresAt    pgtype.Timestamptz `db:"token_claim_expires_at" json:"token_claim_expires_at"`
	RenewalProtocolVersion int16              `db:"renewal_protocol_version" json:"renewal_protocol_version"`
}

type AttemptProgress struct {
	AttemptID                 uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	OrganizationID            uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                 uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                     uuid.UUID          `db:"job_id" json:"job_id"`
	WorkerID                  uuid.UUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch               int64              `db:"worker_epoch" json:"worker_epoch"`
	Fence                     int64              `db:"fence" json:"fence"`
	HeartbeatSequence         int64              `db:"heartbeat_sequence" json:"heartbeat_sequence"`
	RequestHash               []byte             `db:"request_hash" json:"request_hash"`
	BackendStage              string             `db:"backend_stage" json:"backend_stage"`
	ExecutionPhase            execution.Phase    `db:"execution_phase" json:"execution_phase"`
	PhaseProgress             *float64           `db:"phase_progress" json:"phase_progress"`
	EstimatedRemainingSeconds *int64             `db:"estimated_remaining_seconds" json:"estimated_remaining_seconds"`
	EstimatedFinishAt         pgtype.Timestamptz `db:"estimated_finish_at" json:"estimated_finish_at"`
	GpuHealthSummary          []byte             `db:"gpu_health_summary" json:"gpu_health_summary"`
	LocalArtifactState        []byte             `db:"local_artifact_state" json:"local_artifact_state"`
	ScratchFreeBytes          int64              `db:"scratch_free_bytes" json:"scratch_free_bytes"`
	ArtifactStoreReachable    bool               `db:"artifact_store_reachable" json:"artifact_store_reachable"`
	ProgressUpdatedAt         pgtype.Timestamptz `db:"progress_updated_at" json:"progress_updated_at"`
	ProgressValidUntil        pgtype.Timestamptz `db:"progress_valid_until" json:"progress_valid_until"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CancellationStopReceipt struct {
	ID                 uuid.UUID              `db:"id" json:"id"`
	OrganizationID     uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID          uuid.UUID              `db:"project_id" json:"project_id"`
	JobID              uuid.UUID              `db:"job_id" json:"job_id"`
	CancellationID     uuid.UUID              `db:"cancellation_id" json:"cancellation_id"`
	AttemptID          uuid.UUID              `db:"attempt_id" json:"attempt_id"`
	WorkerID           uuid.UUID              `db:"worker_id" json:"worker_id"`
	WorkerEpoch        int64                  `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence       int64                  `db:"attempt_fence" json:"attempt_fence"`
	CancellationFence  int64                  `db:"cancellation_fence" json:"cancellation_fence"`
	Source             CancellationStopSource `db:"source" json:"source"`
	TerminalJobVersion int64                  `db:"terminal_job_version" json:"terminal_job_version"`
	StoppedAt          pgtype.Timestamptz     `db:"stopped_at" json:"stopped_at"`
	CreatedAt          pgtype.Timestamptz     `db:"created_at" json:"created_at"`
}

type Charge struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	OrganizationID      uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID           uuid.UUID          `db:"project_id" json:"project_id"`
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
	CreditReservationID uuid.UUID          `db:"credit_reservation_id" json:"credit_reservation_id"`
	CancellationID      uuid.NullUUID      `db:"cancellation_id" json:"cancellation_id"`
	Reason              ChargeReason       `db:"reason" json:"reason"`
	AmountMinor         int64              `db:"amount_minor" json:"amount_minor"`
	Currency            string             `db:"currency" json:"currency"`
	State               string             `db:"state" json:"state"`
	PostedAt            pgtype.Timestamptz `db:"posted_at" json:"posted_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ArtifactSetID       uuid.NullUUID      `db:"artifact_set_id" json:"artifact_set_id"`
}

type Credential struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	OrganizationID       uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID            uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID          uuid.UUID          `db:"principal_id" json:"principal_id"`
	SecretDigest         []byte             `db:"secret_digest" json:"secret_digest"`
	Scopes               []string           `db:"scopes" json:"scopes"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedByPrincipalID uuid.UUID          `db:"created_by_principal_id" json:"created_by_principal_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CreditReservation struct {
	ID             uuid.UUID              `db:"id" json:"id"`
	OrganizationID uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID              `db:"project_id" json:"project_id"`
	JobID          uuid.UUID              `db:"job_id" json:"job_id"`
	AmountMinor    int64                  `db:"amount_minor" json:"amount_minor"`
	Currency       string                 `db:"currency" json:"currency"`
	State          CreditReservationState `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz     `db:"updated_at" json:"updated_at"`
}

type CustomerOrganization struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ExecutionFailureDecision struct {
	ID                         uuid.UUID              `db:"id" json:"id"`
	OrganizationID             uuid.UUID              `db:"organization_id" json:"organization_id"`
	ProjectID                  uuid.UUID              `db:"project_id" json:"project_id"`
	JobID                      uuid.UUID              `db:"job_id" json:"job_id"`
	AttemptID                  uuid.NullUUID          `db:"attempt_id" json:"attempt_id"`
	WorkerID                   uuid.NullUUID          `db:"worker_id" json:"worker_id"`
	WorkerEpoch                *int64                 `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence               *int64                 `db:"attempt_fence" json:"attempt_fence"`
	Source                     ExecutionFailureSource `db:"source" json:"source"`
	Disposition                RetryDisposition       `db:"disposition" json:"disposition"`
	AttemptState               *AttemptState          `db:"attempt_state" json:"attempt_state"`
	FailureClass               string                 `db:"failure_class" json:"failure_class"`
	FailureFingerprint         string                 `db:"failure_fingerprint" json:"failure_fingerprint"`
	RequestHash                []byte                 `db:"request_hash" json:"request_hash"`
	ErrorSummary               string                 `db:"error_summary" json:"error_summary"`
	BackendStage               string                 `db:"backend_stage" json:"backend_stage"`
	GpuUuids                   []byte                 `db:"gpu_uuids" json:"gpu_uuids"`
	InferenceBackendRevision   string                 `db:"inference_backend_revision" json:"inference_backend_revision"`
	RetryRecommended           bool                   `db:"retry_recommended" json:"retry_recommended"`
	WorkerReusable             bool                   `db:"worker_reusable" json:"worker_reusable"`
	AttemptComputeSeconds      int64                  `db:"attempt_compute_seconds" json:"attempt_compute_seconds"`
	TotalComputeSeconds        int64                  `db:"total_compute_seconds" json:"total_compute_seconds"`
	NextRetryAt                pgtype.Timestamptz     `db:"next_retry_at" json:"next_retry_at"`
	JobFence                   int64                  `db:"job_fence" json:"job_fence"`
	JobVersion                 int64                  `db:"job_version" json:"job_version"`
	DecidedAt                  pgtype.Timestamptz     `db:"decided_at" json:"decided_at"`
	CreatedAt                  pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	AttemptFinalizationSeconds int64                  `db:"attempt_finalization_seconds" json:"attempt_finalization_seconds"`
	TotalFinalizationSeconds   int64                  `db:"total_finalization_seconds" json:"total_finalization_seconds"`
	ArtifactID                 uuid.NullUUID          `db:"artifact_id" json:"artifact_id"`
	ArtifactUploadID           uuid.NullUUID          `db:"artifact_upload_id" json:"artifact_upload_id"`
	FinalizationFailureCode    *string                `db:"finalization_failure_code" json:"finalization_failure_code"`
}

type ExecutionLeaseRenewalProtocol struct {
	Singleton         bool               `db:"singleton" json:"singleton"`
	Enabled           bool               `db:"enabled" json:"enabled"`
	TransitionReceipt string             `db:"transition_receipt" json:"transition_receipt"`
	TransitionedAt    pgtype.Timestamptz `db:"transitioned_at" json:"transitioned_at"`
}

type ExecutionProfileRevision struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ModelRevisionID uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	WorkerPoolID    uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	StableID        string             `db:"stable_id" json:"stable_id"`
	Revision        int32              `db:"revision" json:"revision"`
	State           CatalogState       `db:"state" json:"state"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ExecutionRetryEvidence struct {
	JobID               uuid.UUID          `db:"job_id" json:"job_id"`
	OrganizationID      uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID           uuid.UUID          `db:"project_id" json:"project_id"`
	ExcludedWorkers     []byte             `db:"excluded_workers" json:"excluded_workers"`
	FailureFingerprints []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GenerationPresetRevision struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	ModelRevisionID            uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	StableID                   string             `db:"stable_id" json:"stable_id"`
	Revision                   int32              `db:"revision" json:"revision"`
	State                      CatalogState       `db:"state" json:"state"`
	CertifiedP95ComputeSeconds int32              `db:"certified_p95_compute_seconds" json:"certified_p95_compute_seconds"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type IdempotencyResult struct {
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    []byte             `db:"request_hash" json:"request_hash"`
	JobID          uuid.UUID          `db:"job_id" json:"job_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type InboxReceipt struct {
	ConsumerName     string             `db:"consumer_name" json:"consumer_name"`
	EventID          uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	AggregateType    string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID      uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateVersion int64              `db:"aggregate_version" json:"aggregate_version"`
	EventType        string             `db:"event_type" json:"event_type"`
	ConsumedAt       pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type InvoiceExport struct {
	ChargeID         uuid.UUID          `db:"charge_id" json:"charge_id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	JobID            uuid.UUID          `db:"job_id" json:"job_id"`
	RequestedEventID uuid.UUID          `db:"requested_event_id" json:"requested_event_id"`
	State            InvoiceExportState `db:"state" json:"state"`
	Attempts         int32              `db:"attempts" json:"attempts"`
	AvailableAt      pgtype.Timestamptz `db:"available_at" json:"available_at"`
	ClaimedBy        *string            `db:"claimed_by" json:"claimed_by"`
	ClaimToken       uuid.NullUUID      `db:"claim_token" json:"claim_token"`
	ClaimExpiresAt   pgtype.Timestamptz `db:"claim_expires_at" json:"claim_expires_at"`
	LastError        *string            `db:"last_error" json:"last_error"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InvoiceExportReceipt struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	OrganizationID           uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                uuid.UUID          `db:"project_id" json:"project_id"`
	JobID                    uuid.UUID          `db:"job_id" json:"job_id"`
	ChargeID                 uuid.UUID          `db:"charge_id" json:"charge_id"`
	ExternalInvoiceReference string             `db:"external_invoice_reference" json:"external_invoice_reference"`
	ExternalLineReference    string             `db:"external_line_reference" json:"external_line_reference"`
	ExportedAt               pgtype.Timestamptz `db:"exported_at" json:"exported_at"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Job struct {
	ID                                        uuid.UUID          `db:"id" json:"id"`
	OrganizationID                            uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                                 uuid.UUID          `db:"project_id" json:"project_id"`
	CreatedByPrincipalID                      uuid.UUID          `db:"created_by_principal_id" json:"created_by_principal_id"`
	State                                     JobState           `db:"state" json:"state"`
	Version                                   int64              `db:"version" json:"version"`
	ModelRevisionID                           uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID                uuid.UUID          `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	ServiceClassRevisionID                    uuid.UUID          `db:"service_class_revision_id" json:"service_class_revision_id"`
	OutputSpecID                              uuid.UUID          `db:"output_spec_id" json:"output_spec_id"`
	WorkerPoolID                              uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	RequestHash                               []byte             `db:"request_hash" json:"request_hash"`
	RequestContent                            []byte             `db:"request_content" json:"request_content"`
	RequestContentExpiresAt                   pgtype.Timestamptz `db:"request_content_expires_at" json:"request_content_expires_at"`
	PricingRateCardRevisionID                 uuid.UUID          `db:"pricing_rate_card_revision_id" json:"pricing_rate_card_revision_id"`
	PricingRateLineID                         uuid.UUID          `db:"pricing_rate_line_id" json:"pricing_rate_line_id"`
	PricingUnitAmountMinor                    int64              `db:"pricing_unit_amount_minor" json:"pricing_unit_amount_minor"`
	PricingQuantity                           int32              `db:"pricing_quantity" json:"pricing_quantity"`
	PricingQuotedAmountMinor                  int64              `db:"pricing_quoted_amount_minor" json:"pricing_quoted_amount_minor"`
	PricingCurrency                           string             `db:"pricing_currency" json:"pricing_currency"`
	ExecutionMaxAttempts                      int32              `db:"execution_max_attempts" json:"execution_max_attempts"`
	ExecutionMaxTotalComputeSeconds           int64              `db:"execution_max_total_compute_seconds" json:"execution_max_total_compute_seconds"`
	ExecutionMaxFinalizationSecondsPerAttempt int32              `db:"execution_max_finalization_seconds_per_attempt" json:"execution_max_finalization_seconds_per_attempt"`
	ExecutionRetryBackoffPolicy               []byte             `db:"execution_retry_backoff_policy" json:"execution_retry_backoff_policy"`
	ExecutionRetryableFailureClasses          []string           `db:"execution_retryable_failure_classes" json:"execution_retryable_failure_classes"`
	ExecutionCircuitBreakerPolicy             []byte             `db:"execution_circuit_breaker_policy" json:"execution_circuit_breaker_policy"`
	JobExpiresAt                              pgtype.Timestamptz `db:"job_expires_at" json:"job_expires_at"`
	CreatedAt                                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CurrentFence                              int64              `db:"current_fence" json:"current_fence"`
	BillableStartedAt                         pgtype.Timestamptz `db:"billable_started_at" json:"billable_started_at"`
	ExecutionPhase                            *execution.Phase   `db:"execution_phase" json:"execution_phase"`
	ResultArtifactSetID                       uuid.NullUUID      `db:"result_artifact_set_id" json:"result_artifact_set_id"`
}

type JobCancellationDecision struct {
	ID                      uuid.UUID            `db:"id" json:"id"`
	OrganizationID          uuid.UUID            `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID            `db:"project_id" json:"project_id"`
	JobID                   uuid.UUID            `db:"job_id" json:"job_id"`
	RequestedByPrincipalID  uuid.UUID            `db:"requested_by_principal_id" json:"requested_by_principal_id"`
	PreviousJobState        JobState             `db:"previous_job_state" json:"previous_job_state"`
	Decision                CancellationDecision `db:"decision" json:"decision"`
	Billable                bool                 `db:"billable" json:"billable"`
	AttemptID               uuid.NullUUID        `db:"attempt_id" json:"attempt_id"`
	WorkerID                uuid.NullUUID        `db:"worker_id" json:"worker_id"`
	WorkerEpoch             *int64               `db:"worker_epoch" json:"worker_epoch"`
	AttemptFence            *int64               `db:"attempt_fence" json:"attempt_fence"`
	AuthorityLeaseID        uuid.NullUUID        `db:"authority_lease_id" json:"authority_lease_id"`
	AuthorityLeasePhase     *LeasePhase          `db:"authority_lease_phase" json:"authority_lease_phase"`
	AuthorityLeaseOwnerKind *LeaseOwnerKind      `db:"authority_lease_owner_kind" json:"authority_lease_owner_kind"`
	AuthorityLeaseOwnerID   *string              `db:"authority_lease_owner_id" json:"authority_lease_owner_id"`
	AuthorityLeaseExpiresAt pgtype.Timestamptz   `db:"authority_lease_expires_at" json:"authority_lease_expires_at"`
	CancellationFence       int64                `db:"cancellation_fence" json:"cancellation_fence"`
	JobVersion              int64                `db:"job_version" json:"job_version"`
	DecidedAt               pgtype.Timestamptz   `db:"decided_at" json:"decided_at"`
	CreatedAt               pgtype.Timestamptz   `db:"created_at" json:"created_at"`
}

type JobRuntimePrediction struct {
	JobID                   uuid.UUID          `db:"job_id" json:"job_id"`
	OrganizationID          uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID               uuid.UUID          `db:"project_id" json:"project_id"`
	PredictedRuntimeSeconds int64              `db:"predicted_runtime_seconds" json:"predicted_runtime_seconds"`
	RetryRiskPenaltySeconds int32              `db:"retry_risk_penalty_seconds" json:"retry_risk_penalty_seconds"`
	Source                  string             `db:"source" json:"source"`
	SourceRevision          string             `db:"source_revision" json:"source_revision"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ModelRevision struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	StableID    string             `db:"stable_id" json:"stable_id"`
	Revision    int32              `db:"revision" json:"revision"`
	State       CatalogState       `db:"state" json:"state"`
	ContentHash string             `db:"content_hash" json:"content_hash"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OrganizationCapacityShare struct {
	WorkerPoolID   uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Weight         int32              `db:"weight" json:"weight"`
	RunningLimit   int32              `db:"running_limit" json:"running_limit"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OrganizationCreditAccount struct {
	OrganizationID           uuid.UUID          `db:"organization_id" json:"organization_id"`
	Currency                 string             `db:"currency" json:"currency"`
	ContractCreditLimitMinor int64              `db:"contract_credit_limit_minor" json:"contract_credit_limit_minor"`
	ReservedMinor            int64              `db:"reserved_minor" json:"reserved_minor"`
	UnsettledPostedMinor     int64              `db:"unsettled_posted_minor" json:"unsettled_posted_minor"`
	Version                  int64              `db:"version" json:"version"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OutboxEvent struct {
	EventID          uuid.UUID          `db:"event_id" json:"event_id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	AggregateType    string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID      uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	AggregateVersion int64              `db:"aggregate_version" json:"aggregate_version"`
	EventType        string             `db:"event_type" json:"event_type"`
	SchemaVersion    int32              `db:"schema_version" json:"schema_version"`
	Payload          []byte             `db:"payload" json:"payload"`
	OccurredAt       pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	AvailableAt      pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishAttempts  int32              `db:"publish_attempts" json:"publish_attempts"`
	ClaimedBy        *string            `db:"claimed_by" json:"claimed_by"`
	ClaimToken       uuid.NullUUID      `db:"claim_token" json:"claim_token"`
	ClaimExpiresAt   pgtype.Timestamptz `db:"claim_expires_at" json:"claim_expires_at"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	BrokerStream     *string            `db:"broker_stream" json:"broker_stream"`
	BrokerSequence   *int64             `db:"broker_sequence" json:"broker_sequence"`
	LastError        *string            `db:"last_error" json:"last_error"`
}

type OutputSpec struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	StableID             string             `db:"stable_id" json:"stable_id"`
	Revision             int32              `db:"revision" json:"revision"`
	State                CatalogState       `db:"state" json:"state"`
	Width                int32              `db:"width" json:"width"`
	Height               int32              `db:"height" json:"height"`
	DurationMilliseconds int32              `db:"duration_milliseconds" json:"duration_milliseconds"`
	FrameRateMilli       int32              `db:"frame_rate_milli" json:"frame_rate_milli"`
	Codec                string             `db:"codec" json:"codec"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Container            string             `db:"container" json:"container"`
	ThumbnailRequired    bool               `db:"thumbnail_required" json:"thumbnail_required"`
}

type Principal struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	Kind           PrincipalKind      `db:"kind" json:"kind"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProfileCertification struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	ModelRevisionID            uuid.UUID          `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID uuid.UUID          `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	OutputSpecID               uuid.UUID          `db:"output_spec_id" json:"output_spec_id"`
	ExecutionProfileRevisionID uuid.UUID          `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	State                      CatalogState       `db:"state" json:"state"`
	EvidenceDigest             string             `db:"evidence_digest" json:"evidence_digest"`
	CertifiedAt                pgtype.Timestamptz `db:"certified_at" json:"certified_at"`
	InvalidatedAt              pgtype.Timestamptz `db:"invalidated_at" json:"invalidated_at"`
}

type Project struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	OrganizationID    uuid.UUID          `db:"organization_id" json:"organization_id"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	QueuedLimit       int32              `db:"queued_limit" json:"queued_limit"`
	QueuedCount       int32              `db:"queued_count" json:"queued_count"`
	RunningLimit      int32              `db:"running_limit" json:"running_limit"`
	RunningCount      int32              `db:"running_count" json:"running_count"`
	RetryAfterSeconds int32              `db:"retry_after_seconds" json:"retry_after_seconds"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RetryWaitCount    int32              `db:"retry_wait_count" json:"retry_wait_count"`
}

type ProjectCapacityShare struct {
	WorkerPoolID   uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	Weight         int32              `db:"weight" json:"weight"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RateCardLine struct {
	ID                         uuid.UUID `db:"id" json:"id"`
	RateCardRevisionID         uuid.UUID `db:"rate_card_revision_id" json:"rate_card_revision_id"`
	ModelRevisionID            uuid.UUID `db:"model_revision_id" json:"model_revision_id"`
	GenerationPresetRevisionID uuid.UUID `db:"generation_preset_revision_id" json:"generation_preset_revision_id"`
	ServiceClassRevisionID     uuid.UUID `db:"service_class_revision_id" json:"service_class_revision_id"`
	OutputSpecID               uuid.UUID `db:"output_spec_id" json:"output_spec_id"`
	UnitAmountMinor            int64     `db:"unit_amount_minor" json:"unit_amount_minor"`
	Currency                   string    `db:"currency" json:"currency"`
}

type RateCardRevision struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	Revision    int32              `db:"revision" json:"revision"`
	State       CatalogState       `db:"state" json:"state"`
	EffectiveAt pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RetryRuntimeState struct {
	JobID                       uuid.UUID          `db:"job_id" json:"job_id"`
	OrganizationID              uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID                   uuid.UUID          `db:"project_id" json:"project_id"`
	AttemptsStarted             int32              `db:"attempts_started" json:"attempts_started"`
	ComputeSecondsConsumed      int64              `db:"compute_seconds_consumed" json:"compute_seconds_consumed"`
	FinalizationSecondsConsumed int64              `db:"finalization_seconds_consumed" json:"finalization_seconds_consumed"`
	FinalizationRetryCount      int32              `db:"finalization_retry_count" json:"finalization_retry_count"`
	NextRetryAt                 pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	ExcludedWorkers             []byte             `db:"excluded_workers" json:"excluded_workers"`
	FailureFingerprints         []byte             `db:"failure_fingerprints" json:"failure_fingerprints"`
	CircuitBreakerState         []byte             `db:"circuit_breaker_state" json:"circuit_breaker_state"`
	LastFailureClass            *string            `db:"last_failure_class" json:"last_failure_class"`
	Version                     int64              `db:"version" json:"version"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SchedulerDispatchIntent struct {
	ID                         uuid.UUID              `db:"id" json:"id"`
	SchedulerID                string                 `db:"scheduler_id" json:"scheduler_id"`
	WorkerPoolID               uuid.UUID              `db:"worker_pool_id" json:"worker_pool_id"`
	OrganizationID             uuid.UUID              `db:"organization_id" json:"organization_id"`
	ServiceClassRevisionID     uuid.UUID              `db:"service_class_revision_id" json:"service_class_revision_id"`
	ProjectID                  uuid.UUID              `db:"project_id" json:"project_id"`
	JobID                      uuid.UUID              `db:"job_id" json:"job_id"`
	ExpectedJobVersion         int64                  `db:"expected_job_version" json:"expected_job_version"`
	ExecutionProfileRevisionID uuid.UUID              `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	WorkerID                   uuid.UUID              `db:"worker_id" json:"worker_id"`
	WorkerEpoch                int64                  `db:"worker_epoch" json:"worker_epoch"`
	Lane                       SchedulerLane          `db:"lane" json:"lane"`
	PredictedRuntimeSeconds    int64                  `db:"predicted_runtime_seconds" json:"predicted_runtime_seconds"`
	PredictedStartAt           pgtype.Timestamptz     `db:"predicted_start_at" json:"predicted_start_at"`
	PredictedFinishAt          pgtype.Timestamptz     `db:"predicted_finish_at" json:"predicted_finish_at"`
	JobOrderScore              int64                  `db:"job_order_score" json:"job_order_score"`
	WorkerScore                int64                  `db:"worker_score" json:"worker_score"`
	State                      SchedulerDispatchState `db:"state" json:"state"`
	ClaimedAt                  pgtype.Timestamptz     `db:"claimed_at" json:"claimed_at"`
	ClaimExpiresAt             pgtype.Timestamptz     `db:"claim_expires_at" json:"claim_expires_at"`
	CommittedAt                pgtype.Timestamptz     `db:"committed_at" json:"committed_at"`
	AbandonedAt                pgtype.Timestamptz     `db:"abandoned_at" json:"abandoned_at"`
	AbandonReason              *string                `db:"abandon_reason" json:"abandon_reason"`
	CreatedAt                  pgtype.Timestamptz     `db:"created_at" json:"created_at"`
}

type SchedulerDispatchProtocolState struct {
	Singleton             bool               `db:"singleton" json:"singleton"`
	RequireDispatchIntent bool               `db:"require_dispatch_intent" json:"require_dispatch_intent"`
	ProtocolVersion       int32              `db:"protocol_version" json:"protocol_version"`
	TransitionReceipt     *string            `db:"transition_receipt" json:"transition_receipt"`
	TransitionedAt        pgtype.Timestamptz `db:"transitioned_at" json:"transitioned_at"`
}

type SchedulerDispatchProtocolTransition struct {
	ProtocolVersion       int32              `db:"protocol_version" json:"protocol_version"`
	RequireDispatchIntent bool               `db:"require_dispatch_intent" json:"require_dispatch_intent"`
	TransitionReceipt     string             `db:"transition_receipt" json:"transition_receipt"`
	TransitionedAt        pgtype.Timestamptz `db:"transitioned_at" json:"transitioned_at"`
}

type SchedulerOrganizationDeficit struct {
	WorkerPoolID   uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	DeficitSeconds pgtype.Numeric     `db:"deficit_seconds" json:"deficit_seconds"`
	Version        int64              `db:"version" json:"version"`
	LastSelectedAt pgtype.Timestamptz `db:"last_selected_at" json:"last_selected_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SchedulerProjectDeficit struct {
	WorkerPoolID           uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
	ServiceClassRevisionID uuid.UUID          `db:"service_class_revision_id" json:"service_class_revision_id"`
	ProjectID              uuid.UUID          `db:"project_id" json:"project_id"`
	DeficitSeconds         pgtype.Numeric     `db:"deficit_seconds" json:"deficit_seconds"`
	Version                int64              `db:"version" json:"version"`
	LastSelectedAt         pgtype.Timestamptz `db:"last_selected_at" json:"last_selected_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SchedulerServiceClassDeficit struct {
	WorkerPoolID           uuid.UUID          `db:"worker_pool_id" json:"worker_pool_id"`
	OrganizationID         uuid.UUID          `db:"organization_id" json:"organization_id"`
	ServiceClassRevisionID uuid.UUID          `db:"service_class_revision_id" json:"service_class_revision_id"`
	DeficitSeconds         pgtype.Numeric     `db:"deficit_seconds" json:"deficit_seconds"`
	Version                int64              `db:"version" json:"version"`
	LastSelectedAt         pgtype.Timestamptz `db:"last_selected_at" json:"last_selected_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ServiceClassRevision struct {
	ID                                  uuid.UUID          `db:"id" json:"id"`
	StableID                            string             `db:"stable_id" json:"stable_id"`
	Revision                            int32              `db:"revision" json:"revision"`
	State                               CatalogState       `db:"state" json:"state"`
	QueueRetryAllowanceSeconds          int32              `db:"queue_retry_allowance_seconds" json:"queue_retry_allowance_seconds"`
	MaxAttempts                         int32              `db:"max_attempts" json:"max_attempts"`
	MaxTotalComputeMultiplierMilli      int32              `db:"max_total_compute_multiplier_milli" json:"max_total_compute_multiplier_milli"`
	MaxFinalizationSecondsPerAttempt    int32              `db:"max_finalization_seconds_per_attempt" json:"max_finalization_seconds_per_attempt"`
	RetryBackoffPolicy                  []byte             `db:"retry_backoff_policy" json:"retry_backoff_policy"`
	RetryableFailureClasses             []string           `db:"retryable_failure_classes" json:"retryable_failure_classes"`
	CircuitBreakerPolicy                []byte             `db:"circuit_breaker_policy" json:"circuit_breaker_policy"`
	CreatedAt                           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	QueueWeight                         int32              `db:"queue_weight" json:"queue_weight"`
	MaxQueueWaitBeforeProtectionSeconds int32              `db:"max_queue_wait_before_protection_seconds" json:"max_queue_wait_before_protection_seconds"`
	MaxAgingCreditSeconds               int32              `db:"max_aging_credit_seconds" json:"max_aging_credit_seconds"`
	MaxExpiryUrgencyCreditSeconds       int32              `db:"max_expiry_urgency_credit_seconds" json:"max_expiry_urgency_credit_seconds"`
	MaxRetryRiskPenaltySeconds          int32              `db:"max_retry_risk_penalty_seconds" json:"max_retry_risk_penalty_seconds"`
}

type ServicePrincipal struct {
	PrincipalID    uuid.UUID          `db:"principal_id" json:"principal_id"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalKind  PrincipalKind      `db:"principal_kind" json:"principal_kind"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type VelaPrivateRequestContext struct {
	BackendPid     int32              `db:"backend_pid" json:"backend_pid"`
	TransactionID  pgtype.Uint64      `db:"transaction_id" json:"transaction_id"`
	CredentialID   uuid.UUID          `db:"credential_id" json:"credential_id"`
	RequiredScope  string             `db:"required_scope" json:"required_scope"`
	OrganizationID uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID      uuid.UUID          `db:"project_id" json:"project_id"`
	PrincipalID    uuid.UUID          `db:"principal_id" json:"principal_id"`
	EstablishedAt  pgtype.Timestamptz `db:"established_at" json:"established_at"`
}

type VelaRequestExecutionLeaseRenewalProtocol struct {
	Enabled bool `db:"enabled" json:"enabled"`
}

type VelaRequestJobProgress struct {
	JobID             uuid.UUID          `db:"job_id" json:"job_id"`
	PhaseProgress     float64            `db:"phase_progress" json:"phase_progress"`
	EstimatedFinishAt pgtype.Timestamptz `db:"estimated_finish_at" json:"estimated_finish_at"`
	ProgressUpdatedAt pgtype.Timestamptz `db:"progress_updated_at" json:"progress_updated_at"`
}

type VelaRequestJobRuntime struct {
	JobID           uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptsStarted int32              `db:"attempts_started" json:"attempts_started"`
	NextRetryAt     pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
}

type VisibleCompletion struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	OrganizationID   uuid.UUID          `db:"organization_id" json:"organization_id"`
	ProjectID        uuid.UUID          `db:"project_id" json:"project_id"`
	JobID            uuid.UUID          `db:"job_id" json:"job_id"`
	AttemptID        uuid.UUID          `db:"attempt_id" json:"attempt_id"`
	AttemptFence     int64              `db:"attempt_fence" json:"attempt_fence"`
	AuthorityLeaseID uuid.UUID          `db:"authority_lease_id" json:"authority_lease_id"`
	ArtifactSetID    uuid.UUID          `db:"artifact_set_id" json:"artifact_set_id"`
	ChargeID         uuid.UUID          `db:"charge_id" json:"charge_id"`
	CandidateSha256  []byte             `db:"candidate_sha256" json:"candidate_sha256"`
	JobVersion       int64              `db:"job_version" json:"job_version"`
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Worker struct {
	ID                    uuid.UUID                   `db:"id" json:"id"`
	WorkerPoolID          uuid.UUID                   `db:"worker_pool_id" json:"worker_pool_id"`
	SpiffeID              string                      `db:"spiffe_id" json:"spiffe_id"`
	Epoch                 int64                       `db:"epoch" json:"epoch"`
	LifecycleState        WorkerLifecycleState        `db:"lifecycle_state" json:"lifecycle_state"`
	ReachabilityCondition WorkerReachabilityCondition `db:"reachability_condition" json:"reachability_condition"`
	CreatedAt             pgtype.Timestamptz          `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz          `db:"updated_at" json:"updated_at"`
	LastHeartbeatAt       pgtype.Timestamptz          `db:"last_heartbeat_at" json:"last_heartbeat_at"`
}

type WorkerEpoch struct {
	WorkerID     uuid.UUID          `db:"worker_id" json:"worker_id"`
	Epoch        int64              `db:"epoch" json:"epoch"`
	RegisteredAt pgtype.Timestamptz `db:"registered_at" json:"registered_at"`
}

type WorkerPool struct {
	ID                         uuid.UUID          `db:"id" json:"id"`
	StableID                   string             `db:"stable_id" json:"stable_id"`
	AdmissionOpen              bool               `db:"admission_open" json:"admission_open"`
	QueuedLimit                int32              `db:"queued_limit" json:"queued_limit"`
	QueuedCount                int32              `db:"queued_count" json:"queued_count"`
	RetryAfterSeconds          int32              `db:"retry_after_seconds" json:"retry_after_seconds"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RetryWaitCount             int32              `db:"retry_wait_count" json:"retry_wait_count"`
	SchedulerQuantumSeconds    int32              `db:"scheduler_quantum_seconds" json:"scheduler_quantum_seconds"`
	SchedulerMaxDeficitSeconds int64              `db:"scheduler_max_deficit_seconds" json:"scheduler_max_deficit_seconds"`
	RetryRunningLimit          int32              `db:"retry_running_limit" json:"retry_running_limit"`
}

type WorkerProfileReadiness struct {
	WorkerID                     uuid.UUID                   `db:"worker_id" json:"worker_id"`
	WorkerEpoch                  int64                       `db:"worker_epoch" json:"worker_epoch"`
	ExecutionProfileRevisionID   uuid.UUID                   `db:"execution_profile_revision_id" json:"execution_profile_revision_id"`
	Readiness                    WorkerProfileReadinessState `db:"readiness" json:"readiness"`
	ModelColdStartPenaltySeconds int32                       `db:"model_cold_start_penalty_seconds" json:"model_cold_start_penalty_seconds"`
	LocalityPenaltySeconds       int32                       `db:"locality_penalty_seconds" json:"locality_penalty_seconds"`
	HealthRiskPenaltySeconds     int32                       `db:"health_risk_penalty_seconds" json:"health_risk_penalty_seconds"`
	UpdatedAt                    pgtype.Timestamptz          `db:"updated_at" json:"updated_at"`
}
