// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelJob(ctx context.Context, arg CancelJobParams) (CancelJobRow, error)
	ClaimOutboxEvents(ctx context.Context, arg ClaimOutboxEventsParams) ([]ClaimOutboxEventsRow, error)
	CompleteStageGraphAttemptForVisibleCompletion(ctx context.Context, arg CompleteStageGraphAttemptForVisibleCompletionParams) (bool, error)
	CompleteStageGraphFinalizationClaim(ctx context.Context, arg CompleteStageGraphFinalizationClaimParams) (int64, error)
	ConsumeVisibleCompletionCreditReservation(ctx context.Context, arg ConsumeVisibleCompletionCreditReservationParams) (int64, error)
	DecrementProjectRunningForVisibleCompletion(ctx context.Context, arg DecrementProjectRunningForVisibleCompletionParams) (int64, error)
	ExpireStageGraphFinalizationClaims(ctx context.Context, expiredAt pgtype.Timestamptz) error
	FindActiveStageGraphFinalizationClaim(ctx context.Context, arg FindActiveStageGraphFinalizationClaimParams) (FindActiveStageGraphFinalizationClaimRow, error)
	GetIdempotencyResult(ctx context.Context, arg GetIdempotencyResultParams) (GetIdempotencyResultRow, error)
	GetJob(ctx context.Context, arg GetJobParams) (GetJobRow, error)
	GetPostgresTime(ctx context.Context) (pgtype.Timestamptz, error)
	IncrementProjectQueued(ctx context.Context, arg IncrementProjectQueuedParams) (int64, error)
	InsertArtifactAccessGrant(ctx context.Context, arg InsertArtifactAccessGrantParams) error
	InsertArtifactSet(ctx context.Context, arg InsertArtifactSetParams) error
	InsertArtifactSetItem(ctx context.Context, arg InsertArtifactSetItemParams) error
	InsertCreditReservation(ctx context.Context, arg InsertCreditReservationParams) error
	InsertIdempotencyResult(ctx context.Context, arg InsertIdempotencyResultParams) error
	InsertJob(ctx context.Context, arg InsertJobParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	InsertRetryRuntimeState(ctx context.Context, arg InsertRetryRuntimeStateParams) error
	InsertStageGraphFinalizationClaim(ctx context.Context, arg InsertStageGraphFinalizationClaimParams) error
	InsertStageGraphFinalizationClaimOutput(ctx context.Context, arg InsertStageGraphFinalizationClaimOutputParams) error
	InsertStageGraphVisibleCompletion(ctx context.Context, arg InsertStageGraphVisibleCompletionParams) error
	InsertVerifiedStageGraphArtifact(ctx context.Context, arg InsertVerifiedStageGraphArtifactParams) error
	InsertVisibleCompletion(ctx context.Context, arg InsertVisibleCompletionParams) error
	InsertVisibleCompletionCharge(ctx context.Context, arg InsertVisibleCompletionChargeParams) error
	InsertVisibleCompletionOutboxEvent(ctx context.Context, arg InsertVisibleCompletionOutboxEventParams) error
	InstantiateAdmittedStageGraph(ctx context.Context, arg InstantiateAdmittedStageGraphParams) (InstantiateAdmittedStageGraphRow, error)
	IsArtifactMultipartUploadRecorded(ctx context.Context, arg IsArtifactMultipartUploadRecordedParams) (bool, error)
	ListCommittedArtifactSetItems(ctx context.Context, artifactSetID uuid.UUID) ([]ListCommittedArtifactSetItemsRow, error)
	ListCompletionArtifactsForUpdate(ctx context.Context, arg ListCompletionArtifactsForUpdateParams) ([]ListCompletionArtifactsForUpdateRow, error)
	ListReadableArtifactSet(ctx context.Context, arg ListReadableArtifactSetParams) ([]ListReadableArtifactSetRow, error)
	ListStageGraphFinalizationClaimOutputs(ctx context.Context, claimID uuid.UUID) ([]ListStageGraphFinalizationClaimOutputsRow, error)
	ListStageGraphFinalizationOutputs(ctx context.Context, attemptID uuid.UUID) ([]ListStageGraphFinalizationOutputsRow, error)
	ListSucceededArtifactSetForCancellation(ctx context.Context, arg ListSucceededArtifactSetForCancellationParams) ([]ListSucceededArtifactSetForCancellationRow, error)
	LockCreditAccount(ctx context.Context, organizationID uuid.UUID) (LockCreditAccountRow, error)
	LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) (interface{}, error)
	LockNextStageGraphFinalizationCandidate(ctx context.Context, observedAt pgtype.Timestamptz) (LockNextStageGraphFinalizationCandidateRow, error)
	LockProjectForAdmission(ctx context.Context, arg LockProjectForAdmissionParams) (LockProjectForAdmissionRow, error)
	LockStageGraphFinalizationCompletionAuthority(ctx context.Context, arg LockStageGraphFinalizationCompletionAuthorityParams) (LockStageGraphFinalizationCompletionAuthorityRow, error)
	LockStageGraphReadyCapacityPath(ctx context.Context, arg LockStageGraphReadyCapacityPathParams) (LockStageGraphReadyCapacityPathRow, error)
	LockVisibleCompletionCreditReservation(ctx context.Context, arg LockVisibleCompletionCreditReservationParams) (LockVisibleCompletionCreditReservationRow, error)
	LockVisibleCompletionOrganizationCredit(ctx context.Context, organizationID uuid.UUID) (LockVisibleCompletionOrganizationCreditRow, error)
	LockVisibleCompletionProject(ctx context.Context, arg LockVisibleCompletionProjectParams) (int32, error)
	MarkArtifactCommitted(ctx context.Context, arg MarkArtifactCommittedParams) (int64, error)
	MarkJobSucceeded(ctx context.Context, arg MarkJobSucceededParams) (int64, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int64, error)
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error)
	PostVisibleCompletionOrganizationCredit(ctx context.Context, arg PostVisibleCompletionOrganizationCreditParams) (int64, error)
	RecordInboxReceipt(ctx context.Context, arg RecordInboxReceiptParams) (uuid.UUID, error)
	ReserveOrganizationCredit(ctx context.Context, arg ReserveOrganizationCreditParams) (int64, error)
	ResolveActiveSKU(ctx context.Context, arg ResolveActiveSKUParams) (ResolveActiveSKURow, error)
	ResolveStageJobExecutionRoute(ctx context.Context, arg ResolveStageJobExecutionRouteParams) (ResolveStageJobExecutionRouteRow, error)
	SetArtifactRequestContext(ctx context.Context, arg SetArtifactRequestContextParams) (SetArtifactRequestContextRow, error)
	SetCancellationRequestContext(ctx context.Context, arg SetCancellationRequestContextParams) (SetCancellationRequestContextRow, error)
	SetRequestContext(ctx context.Context, arg SetRequestContextParams) (SetRequestContextRow, error)
}

var _ Querier = (*Queries)(nil)
