apiVersion: v1
kind: Service
metadata:
  name: vela-fleet-admission
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-fleet-controller
    app.kubernetes.io/part-of: vela
spec:
  selector:
    app.kubernetes.io/name: vela-fleet-controller
  ports:
    - name: admission
      port: 443
      protocol: TCP
      targetPort: 9443
