apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vela-system
resources:
  - namespace.yaml
  - workerpool-crd.yaml
  - service-account.yaml
  - rbac.yaml
  - desired-revisions.yaml
  - deployment.yaml
  - disruption-budget.yaml
  - admission-service.yaml
  - validating-webhook.yaml
