apiVersion: v1
kind: ServiceAccount
metadata:
  name: vela-fleet-controller
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vela-fleet-controller
    app.kubernetes.io/part-of: vela
automountServiceAccountToken: true
