server {
    listen 80;
    listen [::]:80;
    server_name ragflow.marslab.ic;
    return 308 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ragflow.marslab.ic;

    ssl_certificate     /etc/nginx/ssl/ragflow.marslab.ic/current/tls.crt;
    ssl_certificate_key /etc/nginx/ssl/ragflow.marslab.ic/current/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 128m;
    proxy_connect_timeout 5s;
    proxy_send_timeout 3600s;
    proxy_read_timeout 3600s;
    proxy_buffering off;

    location / {
        proxy_pass https://127.0.0.1:30443;
        proxy_http_version 1.1;
        proxy_ssl_server_name on;
        proxy_ssl_name ragflow.marslab.ic;
        proxy_ssl_verify on;
        proxy_ssl_trusted_certificate /etc/nginx/ssl/ragflow.marslab.ic/current/ca.crt;
        proxy_ssl_verify_depth 2;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Connection "";
        proxy_request_buffering off;
    }
}
