apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vela-observability
resources:
  - pod-monitor.yaml
configMapGenerator:
  - name: vela-slo-alert-rules
    files:
      - rules.yaml
      - rule-tests.yaml
  - name: vela-slo-dashboard
    files:
      - dashboard.json
  - name: vela-slo-contract
    files:
      - observability-contract.json
generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/part-of: vela
    app.kubernetes.io/component: observability
